### ISSUE TITLE
May I ask if dspy supports multimodal models, such as VLM models like gpt4 vision?

### ISSUE THREAD

**Issue by haojj-xpeng** [stanfordnlp/dspy#1003]
May I ask if dspy supports multimodal models, such as VLM models like gpt4 vision?

If you could provide examples, that would be even better.

**Comment by tom-doerr** [comment]
There's a PR that is not yet merged to add support for GPT4 Vision: https://github.com/stanfordnlp/dspy/pull/682

**Comment by okhat** [comment]
in progress, will take a month or two

**Comment by ieBoytsov** [comment]
> in progress, will take a month or two

Thanks @okhat ! My team at Wayfair is looking forward for VLMs support, especially a compatibility with google gemini-vision family.

**Comment by R-Prady** [comment]
Same here looking forward to vertex ai Gemini multimodal

**Comment by xkpacx** [comment]
My team is also keen to test DSPy with Gemini 1.5 Flash

**Comment by AyushPibit1234** [comment]
My team is eager to use the vision support with GPT-4o for data extraction task.

**Comment by xlows1206** [comment]
same here
