### ISSUE TITLE
Error when trying to use BootstrapFinetuning

### ISSUE THREAD

**Issue by aleksandarmanev01** [stanfordnlp/dspy#1005]
Hi everyone,

I'm trying to perform `BootstrapFinetuning` on a DSPy program, but I keep getting a `ModuleNotFoundError`:
![Screenshot from 2024-05-10](https://github.com/stanfordnlp/dspy/assets/100955280/6c6c3cb7-8ef1-4146-9231-56c788d4eb38)

I'm following the provided code in the cheatsheet (https://dspy-docs.vercel.app/docs/cheatsheet). Any ideas how to fix that?

**Comment by tom-doerr** [comment]
Same issue: https://github.com/stanfordnlp/dspy/issues/1013

**Comment by okhat** [comment]
pip install evaluate?

**Comment by okhat** [comment]
closing in favor of 1013
