### ISSUE TITLE
BootstrapFewShotVision

### ISSUE THREAD

**Issue by tom-doerr** [stanfordnlp/dspy#1016]
Is there interest in a BootstrapFewShotVision module? 
It could bootstrap examples for vision models using image generation models and be added similar to other components:
```
dspy.settings.configure(lm=turbo, rm=colbert, ig=sd_xl)
```
If this is something that could be merged I would look into it.

**Comment by tom-doerr** [comment]
Yes please! I have multiple tasks where I need something like this

**Comment by okhat** [comment]
I sent them this issue. Ping me if you don't hear from us within 2-3 days! Closing the issue for now.

**Comment by myfatemi04** [comment]
Following, am also interested in using Dspy for vision models!

**Comment by sahil02235** [comment]
Hey @myfatemi04 , 
Omar and the team are working on dspy for the vision. Sorry for the lat reply. Can I have your email so that we can have the meeting with the team regarding the project. It will be nice if you join the project. 

Thanks,
Sahil

**Comment by tom-doerr** [comment]
@sahil02235 tom.doerr@tum.de

**Comment by myfatemi04** [comment]
@sahil02235 I’m gsk6me@virginia.edu

**Comment by sahil02235** [comment]
Thanks guys, will send you the invite .

**Comment by JerryLu991223** [comment]
Also interested in applying dspy on vision tasks. May I know the latest progress for the vision part?
