### ISSUE TITLE
[feature request] support gpt-4o

### ISSUE THREAD

**Issue by arnoni** [stanfordnlp/dspy#1037]
Hi all,

As GPT-4 was released, is there a way to use it within DSPy?

10x.

**Comment by tom-doerr** [comment]
I would expect that you can use it just like the other OpenAi models: https://dspy-docs.vercel.app/docs/building-blocks/language_models

**Comment by okhat** [comment]
yes, nothing new is needed.

**Comment by gad2103** [comment]
This isn't true. I'm getting signature issues with json that I wasn't getting using 3-4 families of the model.

**Comment by gad2103** [comment]
@tom-doerr i don't have the errors anymore. the output of the signature definitely behaves differently with json parsing. for example the augmented demos no longer return valid json but escaped json.
\`\`\`json
{
  "first_name": "john",
  "last_name": "carter"
}
\`\`\`

this formatting with `json` inline only happens when i use `4o` as the model.

**Comment by gad2103** [comment]
to be a little clearer, here is part of my compiled program that shows the issue
>
      {
        "augmented": true,
        "first_name": "a n d r e a",
        "last_name": "v o n d",
        "reasoning": "```json\n{\n  \"first_name\": \"andrea\",\n  \"last_name\": \"bond\"\n}\n```",
        "correction": "```json\n{\n  \"first_name\": \"andrea\",\n  \"last_name\": \"bond\"\n}\n```"
      },
      {
        "first_name": "Jonathan",
        "last_name": "lonstein l o n s t e i n",
        "correction": "{\"first_name\":\"jonathan\",\"last_name\":\"lonstein\"}"
      },

**Comment by gad2103** [comment]
@tom-doerr any ideas on how to fix? i would appreciate your help. thanks

**Comment by tom-doerr** [comment]
Could you just new lines and backslash? 
```
out_str.replace('\n', '').replace('\','')
```
Don't think this is an issue with DSPy itself.

**Comment by gad2103** [comment]
@tom-doerr it's not the slashes its the literal `json` in the field value. that was not happening prior to gpt4o.

**Comment by Xargonus** [comment]
For me, gpt4o started working with the new experimental generations (version 2.4.12) `dspy.configure(experimental=True)`
