### ISSUE TITLE
'Import dspy' doesn't work when repo is cloned as a TLD inside your workspace

### ISSUE THREAD

**Issue by isaacbmiller** [stanfordnlp/dspy#1039]
Situation:
I want to use DSPy in a project locally with the changes from #1029 so that I can use VLLM properly.

I cloned the repo into my working folder, so my directory looks like:
```
project/
    main.py
    dspy/
```
I then switched to the #1029 branch, and ran `pip install -e .` inside of the dspy folder. This all works fine

The issue is that when inside `main.py`, if I use `import dspy`, it will import the top-level module rather than the actual DSPy module. The top-level module has no access to any of DSPy's actual functions.

A solution for me was to rename the dspy folder to anything else so that `import dspy` targets the actual module rather than the folder.

I don't know what the project-level fix is here or if there is some way to force the import to ignore the local file. Regardless, I thought it was worth nothing.

I can work on this myself in a week, but for now, I am creating this issue in case anyone else runs into it.

**Comment by tom-doerr** [comment]
It seems to me that's just how python works. As far as I know local files and folders will always be prioritized over installed packages.

**Comment by isaacbmiller** [comment]
Yeah you're totally right @tom-doerr.

Lol the correct solution is to make a subfolder. Oops!

Correct structure is:
```
project/
    src/
        main.py
    dspy/
```
