### ISSUE TITLE
Retrieval error

### ISSUE THREAD

**Issue by salam020** [stanfordnlp/dspy#104]
I downloaded the notebook on my computer and tried to run it. I did not change anything regarding the retrieval model but this line gives me a weird error...
`topK_passages = retrieve(dev_example.question).passages`

The error:
JSONDecodeError                           Traceback (most recent call last)
File [~/.conda/envs/dspy-env/lib/python3.11/site-packages/requests/models.py:971](https://vscode-remote+ssh-002dremote-002b10-002e60-002e90-002e131.vscode-resource.vscode-cdn.net/home/salam/DSPy-AES/~/.conda/envs/dspy-env/lib/python3.11/site-packages/requests/models.py:971), in Response.json(self, **kwargs)
    970 try:
--> 971     return complexjson.loads(self.text, **kwargs)
    972 except JSONDecodeError as e:
    973     # Catch JSON-related errors and raise as requests.JSONDecodeError
    974     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError

File [~/.conda/envs/dspy-env/lib/python3.11/json/__init__.py:346](https://vscode-remote+ssh-002dremote-002b10-002e60-002e90-002e131.vscode-resource.vscode-cdn.net/home/salam/DSPy-AES/~/.conda/envs/dspy-env/lib/python3.11/json/__init__.py:346), in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    343 if (cls is None and object_hook is None and
    344         parse_int is None and parse_float is None and
    345         parse_constant is None and object_pairs_hook is None and not kw):
--> 346     return _default_decoder.decode(s)
    347 if cls is None:

File [~/.conda/envs/dspy-env/lib/python3.11/json/decoder.py:337](https://vscode-remote+ssh-002dremote-002b10-002e60-002e90-002e131.vscode-resource.vscode-cdn.net/home/salam/DSPy-AES/~/.conda/envs/dspy-env/lib/python3.11/json/decoder.py:337), in JSONDecoder.decode(self, s, _w)
    333 """Return the Python representation of ``s`` (a ``str`` instance
    334 containing a JSON document).
    335 
    336 """
--> 337 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338 end = _w(s, end).end()

File [~/.conda/envs/dspy-env/lib/python3.11/json/decoder.py:355](https://vscode-remote+ssh-002dremote-002b10-002e60-002e90-002e131.vscode-resource.vscode-cdn.net/home/salam/DSPy-AES/~/.conda/envs/dspy-env/lib/python3.11/json/decoder.py:355), in JSONDecoder.raw_decode(self, s, idx)
...
    973     # Catch JSON-related errors and raise as requests.JSONDecodeError
    974     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
--> 975     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Any idea how I can resolve this?

**Comment by okhat** [comment]
Hmm that's weird.

I just tried installing from scratch too and everything works fine for me.

Can you do the following in a terminal:

```bash
pip install dspy-ai
```

then

```bash
python
```

then

```python
import dspy
dspy.settings.configure(rm=dspy.ColBERTv2(url='http://20.102.90.50:2017/wiki17_abstracts'))
dspy.Retrieve(k=1)("query")
```

The last line should return the top-1 passage for this query.

**Comment by okhat** [comment]
If it doesn't, please print the full error trace here.

**Comment by salam020** [comment]
Thanks for the prompt response
I am still getting the same issue.

>>> import dspy
>>> dspy.settings.configure(rm=dspy.ColBERTv2(url='http://20.102.90.50:2017/wiki17_abstracts'))
>>> dspy.Retrieve(k=1)("query")
Traceback (most recent call last):
  File "/home/salam/.conda/envs/dspy-env/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/salam/.conda/envs/dspy-env/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/salam/.conda/envs/dspy-env/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/salam/.conda/envs/dspy-env/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/salam/.conda/envs/dspy-env/lib/python3.11/site-packages/dspy/retrieve/retrieve.py", line 25, in __call__
    return self.forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/salam/.conda/envs/dspy-env/lib/python3.11/site-packages/dspy/retrieve/retrieve.py", line 30, in forward
    passages = dsp.retrieveEnsemble(queries, k=self.k)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/salam/.conda/envs/dspy-env/lib/python3.11/site-packages/dsp/primitives/search.py", line 50, in retrieveEnsemble
    return retrieve(queries[0], k)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/salam/.conda/envs/dspy-env/lib/python3.11/site-packages/dsp/primitives/search.py", line 9, in retrieve
    passages = dsp.settings.rm(query, k=k, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/salam/.conda/envs/dspy-env/lib/python3.11/site-packages/dsp/modules/colbertv2.py", line 30, in __call__
    topk: list[dict[str, Any]] = colbertv2_get_request(self.url, query, k)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/salam/.conda/envs/dspy-env/lib/python3.11/site-packages/dsp/modules/cache_utils.py", line 16, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/salam/.conda/envs/dspy-env/lib/python3.11/site-packages/dsp/modules/colbertv2.py", line 55, in colbertv2_get_request_v2_wrapped
    return colbertv2_get_request_v2(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/salam/.conda/envs/dspy-env/lib/python3.11/site-packages/joblib/memory.py", line 655, in __call__
    return self._cached_call(args, kwargs)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/salam/.conda/envs/dspy-env/lib/python3.11/site-packages/joblib/memory.py", line 598, in _cached_call
    out, metadata = self.call(*args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/salam/.conda/envs/dspy-env/lib/python3.11/site-packages/joblib/memory.py", line 856, in call
    output = self.func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/salam/.conda/envs/dspy-env/lib/python3.11/site-packages/dsp/modules/colbertv2.py", line 47, in colbertv2_get_request_v2
    topk = res.json()["topk"][:k]
           ^^^^^^^^^^
  File "/home/salam/.conda/envs/dspy-env/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by okhat** [comment]
Hmm maybe we need to check if this is due to Python 3.11 on your end.

Before that though, does the Google Colab notebook work for you? Can you use the retriever in it?

**Comment by okhat** [comment]
Can you also try this from a different internet connection? There’s a small chance that the server had an issue with the IP for some reason, hence the failure to parse the response…

**Comment by salam020** [comment]
Yes, Google Colab works.
I tried a different network but I still get the same issue.
Maybe the connection is indeed the problem because I am using a server and I can only connect to it using a VPN.
I will check if a different Python version works.
Thanks!

**Comment by SaiSatwik** [comment]
File "/nlp-search-service/main.py", line 36, in __call__
    res = res.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


Seeing this error very frequently. When I use jupyter notebook I couldn't see this error manytimes (but seeing sometime though, reexecuting cell resolving it) but when I use through python code, I am seeing this error.

I am using python 3.9

**Comment by arnavsinghvi11** [comment]
Hi @SaiSatwik,

I believe this could be due to library version mismatches due to differing Python versions. 

Have you tried running your code on Google Colab instead of jupyter notebook? Colab currently uses Python 3.10.12 and might have different dependencies, particularly with the requests library I presume (since that is where your error comes from for retrieval). This may also explain the earlier issues occurring on Python 3.11.

**Comment by okhat** [comment]
@arnavsinghvi11 I'm wondering if this can happen if the server receives too many requests at once?

@SaiSatwik are you sending several requests in parallel (num_threads is large) or just one at a time?

**Comment by YunzeSong** [comment]
Same Question. I haved run successfully in my local jupyter notebooks, but failed in python files.
