### ISSUE TITLE
When will i18n be supported?

### ISSUE THREAD

**Issue by Gierry** [stanfordnlp/dspy#1055]
When will i18n be supported? For instance, in Chinese, Japanese, German, or French, I see that all the supporting phrases are in English, with no language settings available.

**Comment by tom-doerr** [comment]
Is it really an issue? Software development is in English and it's not obvious to me that having instructions in English and processed text in another language is meaningfully harmful to performance. I'm not a maintainer though

**Comment by arnavsinghvi11** [comment]
Tagging #729 for related commentary on using DSPy with different languages -  Internal signatures can be configurable to different languages.
