### ISSUE TITLE
Can't instantiate a module with a Signature.

### ISSUE THREAD

**Issue by TheodorosGalanos** [stanfordnlp/dspy#106]
Hello!

I have starting delving into DSPy, really amazing work!

I am having some issues getting a module to work with a simple Signature.

The code looks something like this:

```python
class MetadataExtraction(dspy.Signature):
    """Extract correct and relevant metadata from document excerpts"""

    excerpt = dspy.InputField()
    title = dspy.OutputField(desc="A concise title that summarizes all of the main themes and ideas found in the excerpt using a maximum of 30 words.", format=str)

class Enrichment(dspy.Module):
    def __init__(self):
        super().__init__()
        self.metadata = MetadataExtraction # have also tried MetadataExtraction()

    def forward(self, excerpt):
        prediction = self.metadata(excerpt=excerpt)
        return dspy.Prediction(excerpt=excerpt, title=prediction.title)
```

When trying to compile and run the above I get the following error:
`TypeError: TemplateV2.__call__() got an unexpected keyword argument 'excerpt'`

Interestingly, when I do `self.metadata = dspy.ChainOfThought(MetadataExtraction)` in the module definition, it works.

I'd love to understand what I'm doing wrong and whether there is a way to make this work without chain of thought.

Regards,
Theodore.

**Comment by okhat** [comment]
Thanks for opening the issue! The fix is simple. Just use dspy.Predict instead of dspy.ChainOfThought — you can’t use the signature directly

**Comment by okhat** [comment]
btw format=str may not be that necessary… not sure if you found it important to add for some reason I’m unaware of

**Comment by TheodorosGalanos** [comment]
Thank you so much, I knew I had misunderstood something!

The format was me experimenting with what's possible. With pydantic + OAI function call API we can do things like List[str] and such, so wanted to see if that would be possible.

This brings me to another issue (support of multiple outputs), but I will maybe start a new thread for that.

Thanks again!
