### ISSUE TITLE
Can DSPY use GPU when compiling a program? Compilation stuck at 65% and would not progress

### ISSUE THREAD

**Issue by johnhuichen** [stanfordnlp/dspy#1076]
I am running intro.ipynb locally on jupyter lab. Compile progressed to 65% and stopped doing anything. 

I also noticed that during compilation my GPU (RTX-3090) is not being used at all

![Screenshot from 2024-05-29 15-44-14](https://github.com/stanfordnlp/dspy/assets/15637790/acdd40a0-639d-417e-9b1e-e3836986d10f)

**Comment by tom-doerr** [comment]
What are you using as the language model backend? It might be that at 65% a particularly long text was sent to the language model server and the server subsequently crashed when running out of VRAM. In case you are running a local server you could also post the server log.

**Comment by okhat** [comment]
I think nothing is stuck. I can't see this in the screenshot (did you truncate the bottom of the screen? it may have important print outs). It's probably stopped after 65% because that was enough to bootstrap the number of examples it needed. This is a common confusion.

**Comment by johnhuichen** [comment]
> What are you using as the language model backend? It might be that at 65% a particularly long text was sent to the language model server and the server subsequently crashed when running out of VRAM. In case you are running a local server you could also post the server log.

Sorry I thought I replied to this but turns out I did not.

I was running llama3 7B in the back. When I was training using DSPY, I also ran a process to monitor GPU usage `watch -n 0.5 nvidia-smi`. The GPU was hardly used.

**Comment by abhisheklomsh** [comment]
Same issue for me, GPU not being utilised while compilation
