### ISSUE TITLE
Hard-coded output field name in metrics.py causes crash if output field is named anything other than 'answer'

### ISSUE THREAD

**Issue by drawal1** [stanfordnlp/dspy#108]
To replicate, just use a different variable name for the dspy.OutputField. For example:
```
class SignatureGenerateQuery(dspy.Signature):
    """Generate query"""
    nl_query = dspy.InputField(desc="a natural language query on the db data")
    xml_query = dspy.OutputField(desc="an XML query corresponding to the nl query")
```

Here's the relevant code snippet from metrics.py, that clearly shows the problem:
```
def answer_exact_match(example, pred, trace=None, frac=1.0):
    return dsp.answer_match(pred.answer, [example.answer], frac=frac)

answer_exact_match_str = dsp.answer_match

def answer_passage_match(example, pred, trace=None):
    return dsp.passage_match(pred.context, [example.answer])
```

**Comment by okhat** [comment]
Thanks for opening this. for context, that’s just a utility — it’s tied to answers because that’s the one setting where this particular form of “exact match” (with specific normalization tricks etc) originates.

do you actually want to check exact match with xml? I don’t think this will work well

**Comment by okhat** [comment]
For context, the utility function is called answer_exact_match hence it checks the answer. It’s not general purpose — you may want to write a different one for xml

**Comment by drawal1** [comment]
@okhat You might have misunderstood the question. Its not about xml or rewriting the function. I fixed the problem as follows:

In metrics.py:
```
def answer_exact_match(example_answer, pred_answer, trace=None, frac=1.0):
    return dsp.answer_match(pred_answer, [example_answer], frac=frac)

answer_exact_match_str = dsp.answer_match

def answer_passage_match(example_answer, pred_context, trace=None):
    return dsp.passage_match(pred_context, [example_answer])
```

In program.py:
```
def validate_context_and_answer(example, pred, trace=None):
    """
        # Validation logic: check that the predicted answer is correct.
        # Also check that the retrieved context does actually contain that answer.
    """
    answer_em = dspy.evaluate.answer_exact_match(example.xml_query, pred.xml_query)
    answer_pm = dspy.evaluate.answer_passage_match(example.context, pred.xml_query)
    return answer_em and answer_pm
```

If you agree with this change, I can submit a pull request

**Comment by okhat** [comment]
Thanks! I see your point. But we already have a function that does this, it’s answer_exact_match_str, which takes strings — the function that’s specific to .answer is like that intentionally
