### ISSUE TITLE
KNN For Few Shot Examples

### ISSUE THREAD

**Issue by danielmachlab** [stanfordnlp/dspy#109]
I would like to open a PR to introduce KNN few-shot functionality to DSPy, similar to how DSP had previously supported it. I've observed for my use case that KNN to select few-shot examples significantly boost performance.

I initially considered introducing a new `Teleprompt` such as `KNNFewShot()`. But after reading through existing `Teleprompt`s such as `BootstrapFewShot`,  it seems this might not be the correct approach. This is because demos for KNN are dependent on each individual example in the `devset` that is being labeled by `Evaluate.__call__()` in `dspy/evaluate/evaluate.py`. And it doesn't seem `Teleprompt`s should be passed the `devset` given the existing design pattern.

@okhat is my understanding correct in that KNN shouldn't be implemented in a `Teleprompt`? If so, would a DSPy-conformant approach be to create a new class like `Evaluate`, but with KNN support for tailored examples? If not, would the approach be to create a `Teleprompt` that accepts the `devset` and identifies the correct demos for each example?

**Comment by okhat** [comment]
Thanks for opening this, @danielmachlab!

I'll be working on this.

This will be a teleprompter indeed, but the teleprompter will build a _new_ program that will find the knn examples, annotate them, then pass them as demos to the original program.

**Comment by okhat** [comment]
Definitely don't change `Evaluate` for this. This modification should change the program itself, not the utility functions like Evaluators.

**Comment by danielmachlab** [comment]
@okhat Thanks for the response! Do you have an eta on the PR? Also, what exactly do you mean by the new program would _annotate_ the examples?

**Comment by okhat** [comment]
Seems all good on this? closing
