### ISSUE TITLE
Can we have custom evaluator?

### ISSUE THREAD

**Issue by hasalams** [stanfordnlp/dspy#110]
I have a Q&A task, and I want to use a teleprompter to compile the Baleen program. 

Instead of using the validation metric `validate_cotext_and_answer_hops` I want to use my own evaluator, which is a gpt model graded answer. I have `eval` function which returns true for accepted answers.

The following is the metric function I use
```python
def validate_model_graded_score(example, pred):
    question = example.question
    ideal = example.answer
    return eval(question=question, expected=ideal, predicted=pred)
```

I get the following error when doing the compilation. 
`AttributeError: 'Example' object has no attribute 'dspy_uuid` when using this custom evaluator. 
Any idea what could be the issue and recommended steps for having a custom evaluator? Thanks.

**Comment by hasalams** [comment]
Ok, I had to add `trace=None` to the function

```python
def validate_model_graded_score(example, pred, trace=None):
    question = example.question
    ideal = example.answer
    return eval(question=question, expected=ideal, predicted=pred)
```
add define teleprompter as follows. 

```python
teleprompter = BootstrapFewShot(metric=validate_model_graded_score)
```

**Comment by salam020** [comment]
I still get the same error even after adding `trace=None`

**Comment by okhat** [comment]
We had some updates on `main` that were not pushed to pip yet.

Now they are pushed. Please do `pip install -U dspy-ai` to get the latest DSPy package.

**Comment by salam020** [comment]
I installed the latest one but still getting the same error

**Comment by salam020** [comment]
Oh yes, you are right, I wasn't using the right attribute in the metric! Thanks, it's solved now :)
