### ISSUE TITLE
MultiChainComparison M parameter

### ISSUE THREAD

**Issue by tom-doerr** [stanfordnlp/dspy#1103]
Do we really need the M parameter for MultiChainComparison? Took me a few minutes of debugging to figure out it only worked if I input three predictions and that I need to change M to fix it.
I would suggest moving the code that assembles the signature to the forward pass so it's no longer necessary to set M.
MultiChainComparison code:
https://github.com/stanfordnlp/dspy/blob/main/dspy/predict/multi_chain_comparison.py

**Comment by okhat** [comment]
Hmm, the number affects the signature which needs to be known ahead of time. Right?

Maybe we should have an assertion or something?

**Comment by tom-doerr** [comment]
There is an assertion, it just doesn't give you an explanation of what's going on
