### ISSUE TITLE
Adding information to tqdm

### ISSUE THREAD

**Issue by tom-doerr** [stanfordnlp/dspy#1106]
Could it make sense to add more information to the tqdm progress bars, e.g. "FINISHED EARLY" when enough examples are collected? That text can be added to the progress bar itself using tqdm.
Also I wish we had nested tqdm progress bars for optimizers/teleprompters that generate multiple programs.
That way you could see the progress of the current program and also the progress for the whole search.
Examples of nested tqdm can be seen here: 
https://medium.com/@harshit4084/track-your-loop-using-tqdm-7-ways-progress-bars-in-python-make-things-easier-fcbbb9233f24

**Comment by okhat** [comment]
FINISHED EARLY makes sense.
