### ISSUE TITLE
Streaming response from compiled DSPy module

### ISSUE THREAD

**Issue by Momilijaz96** [stanfordnlp/dspy#1112]
Hi guys,
I have compiled a DSPy module that I want streaming response from.
I tried using the only_completed flag and stream=True flag in the kwargs of the dspy.OpenAI model, but no luck, I get error:
```
AttributeError: 'Stream' object has no attribute 'model_dump'
```
How can we integrate streaming with DSPy module or how to use the existing capabilities of LangChain/OpenAI stream endpoint.
Please urgent help needed!

**Comment by tom-doerr** [comment]
I think we had a similar issue fixed by https://github.com/stanfordnlp/dspy/pull/1043.
The solution might just be to filter the arguments that get passed to `Stream`, which most likely in your case requires modifying DSPy itself

**Comment by Momilijaz96** [comment]
Yeah I tried removing model_dump from line 249 in DSPy from file ```lib/python3.10/site-packages/dsp/modules/gpt3.py
``` 
but it didn't help and I get

```
Stream object is not subscriptable
```

**Comment by tom-doerr** [comment]
Could you post the relevant code part you are running?

**Comment by Momilijaz96** [comment]
I try setting up a model with stream True like this and called it with a simple signature.
```
gpt4T = dspy.OpenAI(model="gpt-4-1106-preview", max_tokens=1000, model_type="chat",stream=True)
chain = dspy.Predict(" question -> answer ")
dspy.configure(lm=gpt4T)

chain(question='what is cancer?')
```
`
and it gave `AttributeError: 'Stream' object has no attribute 'model_dump'` error without any changes in DSPy, when I run the chain.

To get rid of the error I removed the model_dump from this function in dsp/modules/gpt3.py file.

```
def chat_request(**kwargs):
    if OPENAI_LEGACY:
        return _cached_gpt3_turbo_request_v2_wrapped(**kwargs)

    # return v1_cached_gpt3_turbo_request_v2_wrapped(**kwargs).model_dump() ###  original code
    return v1_cached_gpt3_turbo_request_v2_wrapped(**kwargs)
```
But it results in another error (
Yeah I tried removing model_dump from line 249 in DSPy from file
`lib/python3.10/site-packages/dsp/modules/gpt3.py
`
but it didn't help and I get another error (Stream object is not subscriptable ) from __call__ function of GPT-3 class on this line
`[choices = response["choices"]`

**Comment by Momilijaz96** [comment]
My goal is to stream response from my compiled module

**Comment by tom-doerr** [comment]
There's a refactored backend available on the `rc` branch, maybe it's easier to get streaming to work with that. Documentation for the new backend on `rc`: https://github.com/stanfordnlp/dspy/blob/5b6047895f522ff2a63a4a8253b38476126a6266/examples/backends/Intro%20To%20Backends.ipynb

**Comment by tom-doerr** [comment]
Having said that it doesn't look like it's supported here out of the box either.
How about you look at the trace of how DSPy is prompting gpt-4 and just send that yourself using the `openai` client?
Then you could just enable streaming there.

**Comment by CyrusOfEden** [comment]
Streaming is one of those things that feels simple at first, but is actually really complicated. 

When you have a single module, question => answer, of course you wonder “how can I stream the generated text?”

But when that module has sub modules, or there’s something more complex, then what is being streamed? All the text from all the modules? 

Let me understand your bigger problem here — I suspect you want to stream intermediate steps to a UI so a user can get feedback on progress. 

Is that the case?

**Comment by Momilijaz96** [comment]
> Streaming is one of those things that feels simple at first, but is actually really complicated.
> 
> When you have a single module, question => answer, of course you wonder “how can I stream the generated text?”
> 
> But when that module has sub modules, or there’s something more complex, then what is being streamed? All the text from all the modules?
> 
> Let me understand your bigger problem here — I suspect you want to stream intermediate steps to a UI so a user can get feedback on progress.
> 
> Is that the case?

I just want to stream the final response from my module to UI, so that the user can see the response for input request as it is streamed from LLM.
My module does not have sub-modules but some if-else statements to create chained LLM calls, and last call to LLM is what I want to stream the result of.

**Comment by Momilijaz96** [comment]
I am trying to install the backend support form rc branch, with lite-llm add-on.
what is the proper way to do that, since I get error:
`WARNING: dspy-ai 2.5.0rc3 does not provide the extra 'lite-llm'
`
When I installing it like this:
```
!pip install git+https://github.com/stanfordnlp/dspy.git@rc
!pip install dspy-ai[litellm]
```

**Comment by Momilijaz96** [comment]
I ended up simply extracting the compiled prompts and using them in production for now!

**Comment by pedroallenrevez** [comment]
> There's a refactored backend available on the `rc` branch, maybe it's easier to get streaming to work with that. Documentation for the new backend on `rc`: https://github.com/stanfordnlp/dspy/blob/5b6047895f522ff2a63a4a8253b38476126a6266/examples/backends/Intro%20To%20Backends.ipynb

Sounds pretty cool. Any timeline, release date? Is there any more documentation I can check out meanwhile?
