### ISSUE TITLE
Missing arguments in documentation

### ISSUE THREAD

**Issue by tom-doerr** [stanfordnlp/dspy#1118]
I noticed there sometimes are arguments missing in the documentation, as for BootstrapFewShotWithRandomSearch
https://dspy-docs.vercel.app/api/optimizers/BootstrapFewShotWithRandomSearch
In this case it's:
```
        max_errors=10,
        stop_at_score=None,
        metric_threshold=None,
```

Is this on purpose or is it okay for me to open a PR?

**Comment by arnavsinghvi11** [comment]
Just updated! Thanks for raising.
