### ISSUE TITLE
Where does this model call the OpenAI API? 

### ISSUE THREAD

**Issue by ShenLongDX** [stanfordnlp/dspy#1119]
"Where does this model call the OpenAI API? I want to call my own API interface, but I can't find the configuration file. Where should I configure it?

**Comment by tom-doerr** [comment]
This is the code that connects to OpenAI: https://github.com/stanfordnlp/dspy/blob/main/dsp/modules/gpt3.py
Setting `api_base` might be enough when initializing the LM.
```
    def __init__(
        self,
        model: str = "gpt-3.5-turbo-instruct",
        api_key: Optional[str] = None,
        api_provider: Literal["openai"] = "openai",
        api_base: Optional[str] = None,
        model_type: Literal["chat", "text"] = None,
        system_prompt: Optional[str] = None,
        **kwargs,
    ):
```

Related issue: https://github.com/stanfordnlp/dspy/issues/1075
