### ISSUE TITLE
Need tutorial on dspy compiler

### ISSUE THREAD

**Issue by hiradha** [stanfordnlp/dspy#112]
@okhat  Is there a good explanation for what teleprompter.compile(..) does
It is not clear what/where compilation is happening in the code base.

**Comment by hasalams** [comment]
Agree, looking for more tutorials on teleprompters and different modules in it apart from `BootStrapFewShot`

**Comment by okhat** [comment]
Are you guys looking for a tutorial of how to use teleprompters and which ones to use? Or how they work internally?

**Comment by hasalams** [comment]
I am more interested in the former. I need a way to figure out which type of teleprompter is good for my usecase.

**Comment by hasalams** [comment]
Also, looking forward to seeing the module reference docs. Currently, it is hard to understand the input args to different modules, and what they do.

**Comment by hasalams** [comment]
Hi @arnavsinghvi11 ,
Thanks for the reference docs. Really helpful.

**Comment by okhat** [comment]
Let us know if anything is unclear there!

**Comment by okhat** [comment]
In general, there's a lot of parameters. I suggest keeping everything as default initially in your exploration.

**Comment by darinkishore** [comment]
@okhat Hi! Was reading through all the docs, and something I'm still not certain about is the actual differences in functionality between the Modules. The docs in the PR just describe inputs and outputs, but we don't know how Predict differs from ChainOfThought, or the like, in terms of when to use what and what philosophies guide each one/what use cases to use them in. 

I'm working on a dataset that maps "crisis" containing conversation utterances to the crises they contain, so I'm unsure what to use in my specific use case. The pipeline is complex. We have to define crises, detect major ones referenced, infer changes from context throughout the conversation, make sure the model sticks to our definition of crisis, and output them.

**Comment by arnavsinghvi11** [comment]
Hi @darinkishore, thanks for taking a look at the documentation! Happy to clarify your questions on the Modules.

Regarding the differences between `dspy.Predict` and `dspy.ChainOfThought`,
`dspy.Predict` is best for basic prediction tasks where you pass in your inputs as specified InputFields to your model for predicting outputs as `OutputFields` per your defined signature. For instance, as per the [example in the `dspy.Predict` section](https://github.com/stanfordnlp/dspy/blob/main/docs/modules.md#examples), given a QA signature with a question `InputField` and answer `OutputField`, you can use `dspy.Predict` to pass in your input question to produce an output answer that follows the `OutputField` signature description of an answer between 1 to 5 words (which can be tuned to your needs).
`dspy.ChainOfThought` is best used for understanding the model's reasoning process and the module extends the Predict class but tailors it for chain-of-thought processing in not only providing the expected output but also offering a rationale behind the prediction in a step-by-step manner. Observing a model's decision-making by calling `lm.inspect_history()` is a great way to observe how the chain-of-thought philosophy works. For example, here is how the model would operate on the [example provided in the `dspy.ChainOfThought` section:](https://github.com/stanfordnlp/dspy/blob/main/docs/modules.md#examples)

```
Answer questions with short factoid answers.

---

Follow the following format.

Question: ${question}
Reasoning: Let's think step by step in order to ${produce the answer}. We ...
Answer: often between 1 and 5 words

---

Question: What is the color of the sky?
Reasoning: Let's think step by step in order to produce the answer. We know that the sky appears blue during the day because of the scattering of sunlight by the Earth's atmosphere.
Answer: Blue
```

For your specific use case on "crisis" containing conversation utterances, `dspy.Predict` would be great for detecting major crisis references in using it to classify input utterances as binary outputs determining whether the text defines a crisis.
To dive deeper into the conversational flow of the model, `dspy.ChainOfThought` would be great for gathering insights into the model's reasoning process behind the context of the conversation and the steps the model takes to define the crisis.

Feel free to provide more details on your intended use case and any other specific docs you wanted clarity on. The [introductory tutorial notebook](https://colab.research.google.com/github/stanfordnlp/dspy/blob/main/intro.ipynb) is also a great resource to dip your toes into the other amazing modules!

**Comment by darinkishore** [comment]
Hi @arnavsinghvi11 , thank you for your response and clarification! I've read through the notebook a couple of times, but I struggle to cross-apply the information since almost nothing I'm doing really needs the retrieval of external data step. I've revisted the repo 8 or 9 times this month, and I'm trying to slowly soak it in, but it's a lot and there's not too many examples of non RAG stuff so it's hard to imagine how I'd implement them. 

Basically, I want to use GPT to take a dialog, operate turn by turn, and extract some information at both the utterance level and the contextual, dialog-so-far level. I'll show an example (**trigger warning, abuse!!)**

```
****Speaker** 1:** "Hey, I wanted to talk to you about something. My friend has been going through a tough time with her husband and I'm really worried about her."
[emotion: worry]
[crisis: n/a]


**Speaker 2:** "Of course, what's been going on?"

**Speaker 1:** "Well, she's been married to her abuser for years and his abuse is mostly emotional. She thinks it's not that bad since he doesn't hit her, but he's cheating on her and gaslighting her. He's also taking away her car keys and isolating her from friends and family."
[emotion: worry]
[crisis: emotional abuse, forced isolation, infidelity, gaslighting]

**Speaker 2:** "That sounds really tough. Has she thought about leaving him?"

**Speaker 1:** "Yeah, she's been talking to me about it more and more. But she's worried about the kids and doesn't know her rights if she were to divorce him."
[emotion: worry]
[crisis: Divorce, Legal rights]
 
**Speaker 2:** "That's understandable. Have you tried talking to her about getting legal help or finding a support group?"

**Speaker 1:** "I have, but I don't want to push her too hard. I just try to be there for her as much as possible. Like listening to her vent and offering for her and the kids to move in with me and my husband if she needs to."
[emotion: n/a]
[crisis: Divorce Logistics]

**Speaker 2:** "That's really kind of you. Have you also been sending her resources?"

**Speaker 1:** "Yeah, I send her coded text messages so that he doesn't see any evidence of her searching for help."

**Speaker 2:** "It sounds like you're doing everything you can to support her. Just keep being there for her and offering all the help you can. It's important for her to know that she has people who care about her."
```

Still unsure of what labels we're extracting, because that's uncertain (the literature is REALLY complicated on this topic). But I think DSPy is the best way to get a controllable generation of these label outputs. For the train set, I'd like to feed it one dialog pair at a time, with all the other ones included for context so GPT can see how the situation changes. 

`train = ('Hey, I ... Of course, ...' , {'emotion': 'worry', 'crisis:'emotional...'}), (('Hey, I ... Of course, ...\n\n' + 'Well, ... That sounds really...'), {'emotion: 'worry', 'crisis': 'divorce, legal rights'})`. 

Does that kinda make sense? Also slightly worried about cost when calling GPT for evaluation function. Is that something you guys plan to implement in any pipelines?

Thanks for your help again. It really is very appreciated.

sidenote: It'd be interesting to see how DSPy teleprompts to make a good eval function/prompt for GPT.
