### ISSUE TITLE
Deprecated invalid escape sequences in regexes found in file  dspy/dsp/templates  /template_v2.py

### ISSUE THREAD

**Issue by dixon1e** [stanfordnlp/dspy#1123]
The template_v2.py uses escape sequences that require a simple fix to update from deprecated behavior.

On lines 35 and 42, add an 'r' in front of the match string

35: match = re.search("(.*)(\s){(.*)}\s(.*\${.*})", template)
35: match = re.search(r"(.*)(\s){(.*)}\s(.*\${.*})", template)

and

42: match = re.search("(.*)(\s){(.*)}", template)
42: match = re.search(r"(.*)(\s){(.*)}", template)

This was exposed using the test suite from HybridAGI.

**Comment by arnavsinghvi11** [comment]
Feel free to open a PR for this @dixon1e !

**Comment by okhat** [comment]
Thank you. We will do away with that entire file soon.

**Comment by dixon1e** [comment]
@arnavsinghvi11 I'll be faster next time and do a PR :)
Thanks for taking care of this so fast!
