### ISSUE TITLE
OpenMC-mgxs-plot

### ISSUE THREAD

**Issue by MaryHoss** [stanfordnlp/dspy#1135]
hi everyone,

I have created a mgxs in OpenMC13-3 and want to Plot the fission Cross section for U235, and get this error:

    fig = openmc.plot_xs('U235', ['fission'])
  File "/dss/dsshome1/0C/ge25kij2/.local/lib/python3.8/site-packages/openmc/plotter.py", line 169, in plot_xs
    for this, types in reactions.items():
AttributeError: 'str' object has no attribute 'items'

can anyone help me sollte this error?

thank you
Mary

**Comment by tom-doerr** [comment]
From the documentation
```
reactions ([dict](https://docs.python.org/3/library/stdtypes.html#dict)) – keys can be either a nuclide or element in string form or an openmc.Material object. Values are the type of cross sections to include in the plot.
```
You are passing a string, `'U235`, which is the wrong type.

Also I don't think this is the right GitHub repo you opened the issue in.

**Comment by ajayrawat** [comment]
```
import matplotlib.pyplot as plt

fig = openmc.plotter.plot_xs(
    reactions = {
        'U235': ['fission'],
        'Pu239': ['fission'],
    }
)
plt.show()
```
