### ISSUE TITLE
max_backtracking_attempts value

### ISSUE THREAD

**Issue by Momilijaz96** [stanfordnlp/dspy#1138]
I am using dspy.Suggest and want to set a custom value for `max_backtracking_attempts`

**Comment by tom-doerr** [comment]
You should be able to do that by creating your own backtrack_handler setting the `max_backtracks` value:
https://github.com/stanfordnlp/dspy/blob/300f0eddefef0fa8397eb524fac132904b12f615/dspy/primitives/assertions.py#L179

You then need to set your custom backtrack handler as the `assertion_handler` when calling `assert_transform_module`:
https://github.com/stanfordnlp/dspy/blob/300f0eddefef0fa8397eb524fac132904b12f615/dspy/primitives/assertions.py#L304
