### ISSUE TITLE
Description usage

### ISSUE THREAD

**Issue by salam020** [stanfordnlp/dspy#114]
I have noticed that changing the description of the signature (desc) does not change the results at all.
Although in the intro tutorial, it was mentioned that "we can tweak the descriptions in the Signatures we use in your program to make them more precisely suited for their sub-tasks."
I tried to trace where it is being used but haven't figured it out.
So my question is: is the desc field being used? if yes then where?

**Comment by okhat** [comment]
Are you saying the outputs are not changing? Or the prompts sent to the LM are not changing?

Can you report a minimal example of a signature and the inspect_history(n=1) output? The first line of the prompt will match the docstring of the class signature.

**Comment by salam020** [comment]
Yes, outputs are not changing. I understand that inspect_history shows what is sent to the LM but since the output was not changing I tried to trace it and did not find where "desc" is used.

signature code (using GPT-3.5):
```
class BasicSig(dspy.Signature):
  essay = dspy.InputField()
  score = dspy.OutputField(desc='The score should fall within the range of 5 to 10')
```

inspect_history(n=1)
```
Follow the following format.

Essay: ${essay}
Score: The score should fall within the range of 5 to 10

---

Essay: Givin the Following prompt, and essay. What is the score of the "prompt adherence" trait? The prompt: <Write a response that explains how the features of the setting affect the cyclist. In your response, include examples from the essay that support your conclusion.The essay:The features of the setting affect the cyclist in many ways. The features of the setting that affect the cyclist is the lact of information on were to go and the lack of water. This was a problem because he needed water for his trip and directions on were to go.
Score: The score for the "prompt adherence" trait is 3.
```

Note: Actually, I noticed this issue when I was using the T5 model, for example, this is the score in inpect_history for the same input using T5:
`Score:The lact of information on were to go and the lack of water were both problems.`
It is not even a number and no matter what I change I could not get a proper output.

I tried a couple of different things now, and I noticed that this problem only occurs when using T5 and GPT-3.5 but Llama works fine.

So the conclusion is that the "desc" is passed to the LM just like in inspect_history, however, the output and how desc is used is highly dependent on the used LM nature, correct?

**Comment by okhat** [comment]
By the way, to pass task instructions you need a doc string like this.

```python
class BasicSig(dspy.Signature):
  """Assign a score to the following essay."""

  essay = dspy.InputField()
  question = dspy.InputField()
  score = dspy.OutputField(desc='integer score between 5 to 10')

# then pass the following string as question=question to a dspy.Predict or dspy.ChainOfThought module.
question = "How well does this student essay adhere to <Write a response that explains how the features of the setting affect the cyclist. In your response, include examples from the essay that support your conclusion.>"

# inside your __init__
self.score_essay = dspy.ChainOfThought(BasicSig)

# inside your forward
score = self.score_essay(essay=essay, question=question).score
```

As for what you're seeing, T5 is not going to be great at instruction following from a short prompt. This is a limitation of T5 and not of DSPy. If you want to use T5, you have to use BootstrapFinetune to compile. This will finetune T5 to do your task.

That said, GPT-3.5 should really be able to do this, especially after my changes.

**Comment by okhat** [comment]
> the output and how desc is used is highly dependent on the used LM nature, correct?

yes

**Comment by okhat** [comment]
is this resolved?

**Comment by salam020** [comment]
Yes thanks!
