### ISSUE TITLE
Unable to save model from the DSPY Example

### ISSUE THREAD

**Issue by sartyagi91** [stanfordnlp/dspy#1140]
Hey I encountered an error when I was compiling one of the examples from the dspy library, I got an error like this "TypeError: {'Talk About a Stranger', 'Nancy Reagan'} is not JSON serializable"

link to the colab example: https://colab.research.google.com/github/stanfordnlp/dspy/blob/main/examples/longformqa/longformqa_assertions.ipynb#scrollTo=r0t33A00YzVV

**Comment by tom-doerr** [comment]
Did you run it with default settings?
It's weird that there's a quotation mark missing after "Stranger".

**Comment by sartyagi91** [comment]
Yes, I ran with  default settings, But when I was saving the model using

**cited_longformqa.save("FILE_NAME.json")**

I encountered the error I showed above.

**Comment by tom-doerr** [comment]
Related:
https://github.com/stanfordnlp/dspy/issues/1011
https://github.com/stanfordnlp/dspy/issues/758

**Comment by fivejjs** [comment]
> > Did you run it with default settings? It's weird that there's a quotation mark missing after "Stranger".
> 
> The quotation mark was there, I did not paste it correctly. ![abc](https://private-user-images.githubusercontent.com/170337082/339593225-c20e216e-5a2c-4363-8094-8fabd0a607e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMzk1MDQsIm5iZiI6MTcxODMzOTIwNCwicGF0aCI6Ii8xNzAzMzcwODIvMzM5NTkzMjI1LWMyMGUyMTZlLTVhMmMtNDM2My04MDk0LThmYWJkMGE2MDdlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQwNDI2NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zN2QxMWU5YjgxN2Q4MDU3M2UwNTkwN2FkOWNlNGYxOTUyZGNlOWQwMjdhNTkzOTI3MjViYTQ2Y2QwMTA0MjcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.23lKKjDiYKlh43Aj7MvZU85PM6DFMd6Zw0ZF0cEBnpY)

It looks like the proper json object: `{"some key": "values"}`. But yours looks like Python set.

**Comment by okhat** [comment]
The examples contain sets. They should tuples or lists. That will fix it.

We can make this change in the HotPotQA class.
