### ISSUE TITLE
Does DSP can be used for entity extraction?

### ISSUE THREAD

**Issue by SaiSatwik** [stanfordnlp/dspy#115]
In the realm of Natural Language Processing (NLP), one of the most prominent problem statements is centered around Natural Language Search.

Suppose I possess a database with a predefined schema. When a user intends to formulate a query in natural language, my objective is to extract entity-value pairs from the query, thereby enabling the conversion of the natural language query into a structured query (such as SQL or Elasticsearch) that can be executed on the underlying database.

For instance, if my database contains a table with fields like "employee_name" and "job_description," and a user submits a query like "Joe with job description Software Developer," the desired outcome should be the extraction of entity-value pairs, such as employee_name: Joe and job_description: Software Developer, facilitating subsequent structured querying of the database. 

Can this task be effectively accomplished within dsp framework. 

Note: I have tried to use example in the repo, but unlike prompt technique where I can specify the output format, here in this case output are almost coming in passages with unrelated content. Tried to passed enough number of training examples as well.

**Comment by okhat** [comment]
DSPy should be able to do very well at entity extraction.

Do you have an example code that's failing? I can suggest what needs to change.
