### ISSUE TITLE
Update Google and Google VertexAI for Gemini 1.5 Pro / Flash

### ISSUE THREAD

**Issue by davenportjw** [stanfordnlp/dspy#1163]
Default available model rev to Gemini 1.5 Pro (Google) and Gemini 1.5 Flash (Vertex AI)

Providers: 
- https://github.com/stanfordnlp/dspy/blob/main/dsp/modules/googlevertexai.py
- https://github.com/stanfordnlp/dspy/blob/main/dsp/modules/google.py

**Comment by arnavsinghvi11** [comment]
Thanks @davenportjw - feel free to open a PR to make this update!

**Comment by davenportjw** [comment]
Cool! I will plan to do that.
