### ISSUE TITLE
GROQ client not available in packages

### ISSUE THREAD

**Issue by psilonpneuma** [stanfordnlp/dspy#1166]
It seems that GROQ is available as `lm = dspy.GROQ(model='mixtral-8x7b-32768', api_key ="gsk_***" )`

Nonetheless I am getting an `Attribute Error` when instantiating the LLM as specified in the docs. There does not seem to be a `groq_client ` module in my package installation.

<img width="746" alt="Screenshot 2024-06-18 at 11 46 18" src="https://github.com/stanfordnlp/dspy/assets/15186930/5a2e74e6-ca0e-49a7-8d51-0e150c59bc0e">

Using:
python v3.11.9
dspy==0.1.5

**Comment by mlederbauer** [comment]
Hi! Can you or have you tried updating dspy? It seems that you use an older version, it worked fine for me for dspy==2.4.x

**Comment by psilonpneuma** [comment]
Thank you! Issue resolved :)
