### ISSUE TITLE
Predict forward() does not use lm in kwargs

### ISSUE THREAD

**Issue by Ruce** [stanfordnlp/dspy#1167]
In the Predict class, the forward function sets the local variable `lm` from kwargs (line 71), but this lm is not used in generating output. The assignment should be to `self.lm` instead so that it works with the block in lines 102-108.

**Comment by arnavsinghvi11** [comment]
Thanks for raising this @Ruce ! This is related to #774 if you'd like to follow for updates.

**Comment by okhat** [comment]
closing in favor of the other issue, we're exploring this
