### ISSUE TITLE
ETA on new release?

### ISSUE THREAD

**Issue by lebsral** [stanfordnlp/dspy#1174]
AFAIK the last release was on April 11th for version 2.4.9

Since then many new things have been merged in.  (I was trying to use CloudflareAI and kept getting errors that it doesn't exist.  it turns out it doesn't in 2.4.9)  Some of those things have even made it into the documentation.

Am I doing this wrong, is there a more recent version than this one somewhere?
https://pypi.org/project/dspy-ai/

Of course, we could do something like
poetry add git+https://github.com/stanfordnlp/dspy.git

but that seems less than ideal for new users just trying it out and following the documentation.

**Comment by okhat** [comment]
Updated.

**Comment by lebsral** [comment]
Thank you.  This community is amzaing.
