### ISSUE TITLE
dspy and langfuse integration

### ISSUE THREAD

**Issue by xucailiang** [stanfordnlp/dspy#1179]
Langfuse is a good prompt  management project.
I would like to know if dspy has plans to support langfuse. 
and I have written some code for this and am currently verifying them
Thank you all🙏

**Comment by xucailiang** [comment]
Yes, After the dspy optimization prompt, I hope to easily observe what changes have been made. So that we can do some comparison and cost statistics.

Of course, we can use methods similar  to `inspect_history` , but it would be a good idea to have a more intuitive management page to observe.

thank you for your reply.

**Comment by xucailiang** [comment]
> 是的，经过dspy优化提示后，我希望能够方便的观察到做了哪些改动。这样我们可以做一些比较和成本统计。
> 
> 当然，我们也可以使用类似的方法`inspect_history`，但是如果有一个更加直观的管理页面可以观察会更好。
> 
> 感谢你的回复。



> 您是否建议将 DSPy 创建的已编译优化 json 程序保存到 langfuse？（在您的提示管理下）。还是其他什么？您能提供一些您所看到的情况的更多细节吗？

是的，经过dspy优化提示后，我希望能够方便的观察到做了哪些改动。这样我们可以做一些比较和成本统计。

当然，我们也可以使用类似的方法inspect_history，但是如果有一个更加直观的管理页面可以观察会更好。

感谢你的回复。

**Comment by xucailiang** [comment]
> Are you suggesting something like saving the compiled optimized json programs that DSPy creates to langfuse? (at your prompt management). Or something else? Can you give some more details of what you see happening?

> Yes, after the dspy optimization prompt, I hope to be able to easily observe what changes have been made. In this way, we can do some comparisons and cost statistics.
>
> Of course, we can also use a similar method `inspect_history`, but it would be better if there is a more intuitive management page to observe.
>
> Thank you for your reply.

**Comment by denisergashbaev** [comment]
That´s a good suggestion. On my side, I would want DSPy integration with Langfuse. That is, I want to see the calls that DSPy makes to LLM, grouped into traces and spans.

**Comment by xucailiang** [comment]
> That´s a good suggestion. On my side, I would want DSPy integration with Langfuse. That is, I want to see the calls that DSPy makes to LLM, grouped into traces and spans.
> 
> I see there was a PR for this: #200

I also noticed this PR, unfortunately，it was submitted on Oct 31, 2023, and has not been merged yet, dspy and langfuse have been updated for many versions. 

So far, I have completed part of the code for `chat_request` and `completions_request`， If necessary, I will submit these changes and try to connect langfuse elsewhere.

**Comment by arnavsinghvi11** [comment]
Feel free to build on #200 @xucailiang (will need to be updated with latest DSPy and/or Langfuse changes) or open a new PR for this integration!

**Comment by xucailiang** [comment]
> Feel free to build on #200 @xucailiang (will need to be updated with latest DSPy and/or Langfuse changes) or open a new PR for this integration!

As you said, I have submitted the relevant code [PR](https://github.com/stanfordnlp/dspy/pull/1186) thank you everyone🙏

**Comment by Aaryaveerkrishna23** [comment]
> Langfuse is a good prompt management project. I would like to know if dspy has plans to support langfuse. and I have written some code for this and am currently verifying them Thank you all🙏

Hi , @xucailiang I was still not able to see any traces of my azure model's cost on locally hosted langfuse dashboard

**Comment by xucailiang** [comment]
> > Langfuse is a good prompt management project. I would like to know if dspy has plans to support langfuse. and I have written some code for this and am currently verifying them Thank you all🙏
> 
> Hi , @xucailiang I was still not able to see any traces of my azure model's cost on locally hosted langfuse dashboard

hi，The PR for integrating langfuse is under review by @arnavsinghvi11 and we are all looking forward to this feature!

**Comment by mahitha-29** [comment]
> > Langfuse is a good prompt management project. I would like to know if dspy has plans to support langfuse. and I have written some code for this and am currently verifying them Thank you all🙏
> 
> Hi , @xucailiang I was still not able to see any traces of my azure model's cost on locally hosted langfuse dashboard

Hi @Aaryaveerkrishna23 Were you able to see now as the PR got integrated into the main? Let me know if you have found out a way to see the traces using dspy and languse!

**Comment by JankoLancer** [comment]
@xucailiang after your work here, is there any way to manipulate the current trace, and group together all dspy call in one trace? e.g. how to call https://python.reference.langfuse.com/langfuse/decorators#LangfuseDecorator.update_current_trace properly.

Thanks a lot!

**Comment by xucailiang** [comment]
> @xucailiang after your work here, is there any way to manipulate the current trace, and group together all dspy call in one trace? e.g. how to call https://python.reference.langfuse.com/langfuse/decorators#LangfuseDecorator.update_current_trace properly.
> 
> Thanks a lot!

Do you mean you want to manage the trace yourself? if you need to manage langfuse yourself, you can get the langfuse object after you instantiate LangfuseTracker, 
like this `langfuse = LangfuseTracker().langfuse` and then you can operate on it.
I don't know if this helps you, if you have any questions feel free to contact me
