### ISSUE TITLE
Adding textgrad as an optimizer?

### ISSUE THREAD

**Issue by Anindyadeep** [stanfordnlp/dspy#1197]
Hi, I recently saw this project from Stanford named [TextGrad](https://github.com/zou-group/textgrad). Although I had a high level read to this project, but on the first thought, DSPy optimizers came into my mind. I wonder whether we can integrate this?

**Comment by Josephrp** [comment]
you will need to have text in a separate container to solve the incompatible python versions

**Comment by okhat** [comment]
yes this is coming soon

**Comment by okhat** [comment]
we'll have help from Mert

**Comment by tekumara** [comment]
hiya given this has been closed as completed, are there any docs on how to use textgrad as an optimizer? I wasn't able to find anything.

**Comment by xiaoyunwu** [comment]
What is the status of this?

**Comment by tekumara** [comment]
Oh I see. Is there some way to be notified when features are completed? Subscribing to an issue for a feature and being notified when the status changes is very useful for this.

**Comment by Haoping-Xiao** [comment]
hi, what is the current progress?

**Comment by J-Fo-S** [comment]
shouldn't be closed

**Comment by halcasteel** [comment]
What is the status on this?
