### ISSUE TITLE
Inconsistent Weaviate dependency

### ISSUE THREAD

**Issue by hsm207** [stanfordnlp/dspy#1198]
On the [pyproject.toml ](https://github.com/stanfordnlp/dspy/blob/d1a0d9323e02393f5d2cec78dcc8dcf36b33c9d2/pyproject.toml#L50)file, we have:

```
weaviate = ["weaviate-client~=4.5.4"]
```

but in [setup.py](https://github.com/stanfordnlp/dspy/blob/d1a0d9323e02393f5d2cec78dcc8dcf36b33c9d2/setup.py#L31) we have:

```
"weaviate": ["weaviate-client~=3.26.1"],
```
Why do we have 2 package managers for this project?

CC @CShorten

**Comment by arnavsinghvi11** [comment]
Resolved via #1204 .
