### ISSUE TITLE
How do I load a previously compiled agent?

### ISSUE THREAD

**Issue by ArslanS1997** [stanfordnlp/dspy#1201]
Hi in a previous project I have saved an agent file, how do I load it back in my new project?

**Comment by vikrantrathore** [comment]
Based on information in the document you can save and load the optimized programs, they are saved as JSON. Check the information in the document at https://dspy-docs.vercel.app/docs/building-blocks/optimizers


```
optimized_program.save(YOUR_SAVE_PATH)
loaded_program = YOUR_PROGRAM_CLASS()
loaded_program.load(path=YOUR_SAVE_PATH)
```

Hope this helps.

Also one suggestion for future, if you seek help from community please provide bit more details.

**Comment by okhat** [comment]
thank you @vikrantrathore

**Comment by okhat** [comment]
feel free to reopen if problem persists @ArslanS1997
