### ISSUE TITLE
how to set training epoch when using miprov2

### ISSUE THREAD

**Issue by hjc3613** [stanfordnlp/dspy#1207]
how to set training epoch when using miprov2

**Comment by arnavsinghvi11** [comment]
Hi @hjc3613 , do you mean [`num_batches`](https://github.com/stanfordnlp/dspy/blob/39cda4903ef2b27330971036cd6655d1e7da18b0/dspy/teleprompt/mipro_optimizer_v2.py#L44)?

**Comment by okhat** [comment]
Training epochs is not a concept in MIPRO. We're working on new optimizer docs, but in the meantime see the new MIPRO paper and the visual thread on MIPRO from Michael Ryan on twitter.

**Comment by hjc3613** [comment]
> Hi @hjc3613 , do you mean [`num_batches`](https://github.com/stanfordnlp/dspy/blob/39cda4903ef2b27330971036cd6655d1e7da18b0/dspy/teleprompt/mipro_optimizer_v2.py#L44)?

the training time of miprov2 is a little long than my expection, so i want to know how to complete it early

**Comment by hjc3613** [comment]
> Michael Ryan on twitter.

can you give me the link about the new MIPRO blog? thanks!!
