### ISSUE TITLE
How do I specify metadata query parameters in Retrievers?

### ISSUE THREAD

**Issue by rodrigomeireles** [stanfordnlp/dspy#1212]
I was wondering how do I specify metadata to the retrievers' queries. For instance, a user might ask about something specifically for 2022 and semantically, all year numbers are very similar. Therefore I might want to query all documents with a "year" label attached to them being equal to 2022.

This is trivially done if I have control of the query and almost all vector DBs support metadata filters. How should I go about implementing this in my Retriever? Is there any way to use the built-in retrievers?

Any suggestion is appreciated.

**Comment by rodrigomeireles** [comment]
I figured maybe no one answered because my question is too generic. I am looking at the PGVector retriever.

**Comment by rodrigomeireles** [comment]
@arnavsinghvi11 you seem to have comitted recently to the PgVector retriever. Do you have any idea on how to add filtering?

**Comment by rodrigomeireles** [comment]
I ended up subclassing the PgVectorRM and overwrote the `forward` method to include more parameters. After that I wrote some `if/else` expression to conditionally inject a `where` clause in my query.

**Comment by leegang** [comment]
How did overwrite the forward function?
