### ISSUE TITLE
TypedChainOfThought and ChainOfThought have divergent reasoning output fields.

### ISSUE THREAD

**Issue by ko0stik** [stanfordnlp/dspy#1235]
On `ChainOfThought` in the [source code](https://github.com/stanfordnlp/dspy/blob/55510eec1b83fa77f368e191a363c150df8c5b02/dspy/predict/chain_of_thought.py#L45), we can see that output field for explaining the CoT is named `rationale`.

On TypedChainOfThought, in [this file](https://github.com/stanfordnlp/dspy/blob/55510eec1b83fa77f368e191a363c150df8c5b02/dspy/functional/functional.py#L69), CoT explanation is named `reasoning`.

Is there a reason why those 2 are different or is it simply a matter of separate evolutions of the code?
If it is the latter, would it be more advisable to avoid using the typed predictors?

🙏

**Comment by okhat** [comment]
Good point, we should streamline this. That said, it seems like a minor thing. Does it break any major things for you?

**Comment by ko0stik** [comment]
Absolutely not, I noticed this while working more closely with the reasoning output fields when I was switching between typed and regular. It is slightly confusing at most.

I tend to prefer typed predictors. Considering the massive overhaul that has been under discussion lately, my main concern was to make sure that what I implement is as future-proof as possible to avoid migrations later on.

Thanks @okhat , I appreciate your reactivity on my question!

**Comment by okhat** [comment]
Thank you!
