### ISSUE TITLE
How to set the concurrency when using a custom api to access the model?

### ISSUE THREAD

**Issue by hitmgr** [stanfordnlp/dspy#1236]
My api access concurrency is 5, I want to know how dspy handles concurrency when sending requests? Where can I set this parameter?

**Comment by okhat** [comment]
Set num_threads in classes that accept that parameter like when compiling or evaluating

**Comment by hitmgr** [comment]
> Set num_threads in classes that accept that parameter like when compiling or evaluating

thanks,but are there any parameters for parallelism if it's just a generation job using pipeline
