### ISSUE TITLE
Can we add query_filter filed for QdrantRM

### ISSUE THREAD

**Issue by hawktang** [stanfordnlp/dspy#1238]
![image](https://github.com/stanfordnlp/dspy/assets/2004071/130d0981-a20e-4676-a9e5-396d4fefcdfc)
to

![image](https://github.com/stanfordnlp/dspy/assets/2004071/b0e891a5-6491-40de-82d1-84dd4a3f685d)

**Comment by arnavsinghvi11** [comment]
Fixed by #1239
