### ISSUE TITLE
HFClientVLLM is missing http_request_kwargs

### ISSUE THREAD

**Issue by MohammedAlhajji** [stanfordnlp/dspy#1249]
I have model deployed via VLLM; however, I have to use a proxy at my work PC and I run into certificate issues often due to the proxy.

I've noticed that HFClientTGI has a useful extra argument http_request_kwargs. I'd love to add it to HFClientVLLM if there's no limitation to that

**Comment by MohammedAlhajji** [comment]
I've made this branch to fix this issue https://github.com/stanfordnlp/dspy/pull/1250

**Comment by okhat** [comment]
Thanks a lot for opening the PR!
