### ISSUE TITLE
Does DSPY require cohere? Never saw this in the main documentation.....

### ISSUE THREAD

**Issue by Tonic3** [stanfordnlp/dspy#1251]
AttributeError: module 'cohere' has no attribute 'CohereAPIError'

I know what the error is, but I'm wondering why its forcing cohere?

**Comment by CShorten** [comment]
Are you using the latest version of DSPy? I think this should be solved from 2.4.10 onwards.

Reference - https://github.com/stanfordnlp/dspy/blob/main/dsp/modules/cohere.py.

**Comment by clearsitedesigns** [comment]
I just loaded it from pip install so perhaps not if that isn't updated

**Comment by okhat** [comment]
@clearsitedesigns let us know if the problem persists if you do

pip install -U dspy-ai
