### ISSUE TITLE
GPT4T is hard coded

### ISSUE THREAD

**Issue by fdojose** [stanfordnlp/dspy#1258]
https://github.com/stanfordnlp/dspy/blob/46f73224bcf83bff99431d2c9daa48ab972b3fbe/dspy/predict/langchain.py#L72C1-L72C9

So it doesn't works with Ollama, for testing I changed the line for: 

gpt4T=dspy.OllamaLocal(model="llama3")

But I'm getting:
"Thank you for preparing the modular pieces! I'm ready to follow the format. Here are the three modular pieces:\n\n**Essential Instructions:** To generate a tweet: ${Here are the three modular pieces: --- Essential Instructions: Here are the prepared modular pieces: **Essential Instructions:** To generate a tweet}\n\nProvide a context and a question. The model should respond with a tweet that answers the question.\n**Input Keys:** context: ${provide a context and a question. The model should respond with a tweet that answers the question. Input Keys: context}\n\nQuestion\n**Output Key:** tweet Text\n\n${---: ${question} Output Key: tweet_text ---}\n\nLet's generate a tweet!"

**Comment by okhat** [comment]
This langchain plugin requires GPT-4T.
