### ISSUE TITLE
question about the documentation of KNNFewShot

### ISSUE THREAD

**Issue by enchyisle** [stanfordnlp/dspy#1262]
Hello,

I was reading the doc here:https://dspy-docs.vercel.app/docs/building-blocks/optimizers#what-dspy-optimizers-are-currently-available

<img width="848" alt="image" src="https://github.com/stanfordnlp/dspy/assets/2070224/a2ee2121-3089-4e10-bf48-082c683b8f27">

And I was confused by this part.
How is KNN used to pick a diverse set of examples from different clusters?
I suppose KNN should just select the k most similar candidates, while clustering would be the job of K-means.

Or is there some post-processing after KNN that does the clustering stuff that I was missing?

Thanks.

**Comment by okhat** [comment]
That paragraph has many problems — I’d merge a PR that makes it simpler and more faithful to the code. I don’t remember any clustering in that teleprompter. Also pretty sure we don’t have a notebook for this teleprompter. Lots of mistakes in that paragraph.

**Comment by okhat** [comment]
I checked the git history — this was volunteered by a kind user, but imo it shouldn’t have been merged like this. Pretty inaccurate.

**Comment by enchyisle** [comment]
Thanks for the clarifacation @okhat .

**Comment by okhat** [comment]
Reopening until this is corrected / fixed

**Comment by arnavsinghvi11** [comment]
fixed in [latest commit](https://github.com/stanfordnlp/dspy/commit/525f33be6c0e610c9fdfffa2f8b61cf763fcf37c). Thanks again @enchyisle !
