### ISSUE TITLE
dspy answer signature for a system that could be both factual and long

### ISSUE THREAD

**Issue by karrtikiyer** [stanfordnlp/dspy#127]
Wanted some advise, say we are building a Q/A system using which the users can ask both factoid(factual) as well as long (summaries or how to questions).
In such cases what would be your advise in terms of generated_answer part in the overall pipeline? 
Is there a way wherein based on the nature of questions the compiler takes the decision to call the appropriate answer signature?

**Comment by okhat** [comment]
You can easily have a `self.router` module that chooses whether the question should be factoid or long. Just add one more module with that kind of signature. For this, use the long dspy.Signature class format.
