### ISSUE TITLE
Question: BootstrapFewShot - Intermediate Label  Bootstrapping

### ISSUE THREAD

**Issue by simonr98** [stanfordnlp/dspy#1274]
Hey! When using bootstrapFewShot to optimize a multi-module DSPy program with TypedPredictors, DSPy does not actually bootstrap the intermediate labels correctly - is what I want currently supported? 

This is the way it should be:

{
  "validity_assessment.validity_assessment.predictor": {
    "lm": null,
    "traces": [],
    "train": [],
    "demos": [
      {
        "input": [
          "{\"id\":0,\"company_name\":\"ELASTIC\",\"product_description\":\"Embedded Architect 200 (200 Consulting Days)\"}",
          "{\"id\":1,\"company_name\":\"ELASTIC\",\"product_description\":\"Software Engineer\"}"
        ],
        "output": [
          {
            "id": 0,
            "valid": true
          },
          {
            "id": 1,
            "valid": false
          }
        ]
      }
    ],
    "signature_instructions": "..."
  },
 ...

# ---------------------------------------------------------------------------------------------------------
This is what I get:

{
  "validity_assessment.validity_assessment.predictor": {
    "lm": null,
    "traces": [],
    "train": [],
    "demos": [
      {
        "input": [
          "{\"id\":0,\"company_name\":\"ELASTIC\",\"product_description\":\"Embedded Architect 200 (200 Consulting Days)\"}",
          "{\"id\":1,\"company_name\":\"CLOUDERA\",\"product_description\":\"Cloudera Edge Management: Annual Subscription - Up to 50000 Agents - Business Support. US Citizen US Soil Support Engineers, 50% Premier Plus Support Engineer -up to 20 Days On-site, Designated Support Engineer - up to 50 Days On-site\"}"
        ],
        "output": [
          {
            "id": 0,
            "high_level_product_name": "ELASTIC Embedded Architect",
            "low_level_product_name": "ELASTIC Embedded Architect 200",
            "validity": "VALID"
          },
          {
            "id": 1,
            "high_level_product_name": "Cloudera Edge Management",
            "low_level_product_name": "Cloudera Edge Management: Annual Subscription",
            "validity": "VALID"
          }
        ]
      }
    ],

**Comment by okhat** [comment]
I don't understand the problem. Is this only with TypedPredictors? What is incorrect about the outcome?
