### ISSUE TITLE
Early stop when scores reach 1.0

### ISSUE THREAD

**Issue by talperetz** [stanfordnlp/dspy#128]
`BootstrapFewShotWithRandomSearch` keeps searching even when gets to:

`Average Metric: 3.0 / 3  (100.0%)
Score: 100.0 for set: [3]
Scores so far: [0.0, 0.0, 33.33, 100.0, 100.0]
New best score: 100.0 for seed 1
Best score: 100.0
Average of max per entry across top 1 scores: 1.0
Average of max per entry across top 2 scores: 1.0
Average of max per entry across top 3 scores: 1.0
Average of max per entry across top 5 scores: 1.0
Average of max per entry across top 8 scores: 1.0
Average of max per entry across top 9999 scores: 1.0`

**Comment by okhat** [comment]
haha what a good problem to have — thank you for the note, will fix

**Comment by okhat** [comment]
oh actually it's a bit trickier... we can't assume the scores are out of 1.0, what if your metric returns 2 or 6 or 126.1?

**Comment by okhat** [comment]
But we can add a stop_at_score keyword argument. Btw for now you can easily modify max_candidate_programs from 16 to like 3

**Comment by talperetz** [comment]
`stop_at_score` would work well

**Comment by okhat** [comment]
Fix merged. You can now use it if you install from git, eg with `pip install -e .`

Will be part of the next pip release too if you don’t wanna use it this way.
