### ISSUE TITLE
BuilderConfig doesn't have "trust_remote_code" key when loading HotPotQA

### ISSUE THREAD

**Issue by zhaohan-dong** [stanfordnlp/dspy#1288]
Loading HotPotQA following [this](https://dspy-docs.vercel.app/docs/deep-dive/data-handling/built-in-datasets)

Error on datasets/hotpotqa.py:14-15

> ValueError: BuilderConfig BuilderConfig(name='fullwiki', version=1.0.0, data_dir=None, data_files=None, description='\nIn the fullwiki setting, a question-answering system must find the answer to a question in the scope of the\nentire Wikipedia. We fully test the model’s ability to locate relevant facts as well as reasoning about them\nby requiring it to answer the question given the first paragraphs of all Wikipedia articles without the gold\nparagraphs specified. This full wiki setting truly tests the performance of the systems’ ability at multi-hop\nreasoning in the wild.\n') doesn't have a 'trust_remote_code' key.

**Comment by arnavsinghvi11** [comment]
Hi @zhaohan-dong , this should be resolved on the latest release `dspy-ai 2.4.12` or with upgrading your `datasets` library version.

**Comment by linuaries** [comment]
Have the same issue with dspy-ai 2.4.13.

coud be solved by unistall dspy-ai and install dspy
```shell
pip install -U dspy
```
which will instal dspy 0.1.5 with dspy-ai 2.4.5.

**Comment by raviakasapu** [comment]
is this resolved? I am still getting error on version 2.5.9
uninstalled old DsPY and installed latest version available.

Thanks
Ravi

**Comment by sheli-kohan** [comment]
hi, same issue here in Version 2.5.31
