### ISSUE TITLE
Integrate dspy with qwen 72B model

### ISSUE THREAD

**Issue by prashanthkolaneru** [stanfordnlp/dspy#1322]
My qwen 72B model is present in azure dbfs location. I want to integrate qwen model with dspy. Can some one help me how to integrate dspy with locally saved models

**Comment by arnavsinghvi11** [comment]
Hi @prashanthkolaneru , feel free to check out the [various Local LM client integrations](https://dspy-docs.vercel.app/api/category/local-language-model-clients)!
