### ISSUE TITLE
KeyError: 'max_tokens'.

### ISSUE THREAD

**Issue by james4tsystem** [stanfordnlp/dspy#1324]
I got the following error message
""" 
# Recurse with greedy decoding and a shorter length.
---> 95             max_tokens = kwargs.get("max_tokens", dsp.settings.lm.kwargs["max_tokens"])
     96             max_tokens = min(max(75, max_tokens // 2), max_tokens)
     97             new_kwargs = {**kwargs, "max_tokens": max_tokens, "n": 1, "temperature": 0.0,}

KeyError: 'max_tokens'
"""
when using Gemini in Google Colab.

Any idea how to resolve this error?

**Comment by grant-d** [comment]
I had to use `max_output_tokens` when using Gemini. Not sure if still the case, but might help you
