### ISSUE TITLE
QdrantRM do not support passages

### ISSUE THREAD

**Issue by hawktang** [stanfordnlp/dspy#1329]
from dspy.retrieve.qdrant_rm import QdrantRM
<img width="545" alt="image" src="https://github.com/user-attachments/assets/8fbe877d-5860-4c4d-91f6-e57ab01aa732">

The implementation is not same as other retriever

<img width="795" alt="image" src="https://github.com/user-attachments/assets/53dd1f9e-89fd-4eca-aec0-45279011f068">

**Comment by Anush008** [comment]
I thinnk you can wrap the result in

```py
dspy.Prediction(passages=qdrant_retriever("Why?")).passages
```

**Comment by hawktang** [comment]
Thank you @Anush008 

I found if wrapping with  dspy.Retrieve, it will also be working.

<img width="460" alt="image" src="https://github.com/user-attachments/assets/e9218c73-c57b-4910-a4d7-6b789153a2cc">

**Comment by Anush008** [comment]
Awesome 🙌

**Comment by hawktang** [comment]
Thank you so much for help @Anush008
