### ISSUE TITLE
Could you share how you built up Wikipedia corpus.

### ISSUE THREAD

**Issue by yhao-wang** [stanfordnlp/dspy#133]
From the retrieval results, the corpus is neither in the format of 100w chunks like DPR, nor the passage-level Wikipedia corpus as you mentioned in ColBERT. Could you inform me how you built up Wikipedia corpus. Could you please share the scripts or use network disks divers to share the processed data? 
Thanks a lot.

**Comment by okhat** [comment]
The details are fully described in the notebook: HotPotQA wiki abstracts 2017.

**Comment by yhao-wang** [comment]
I am sorry, I still can not find it. Could you give me a link or specific file name or paper name? Thank a lot

**Comment by okhat** [comment]
Well — which notebook are you referring to so i can be sure?

**Comment by yhao-wang** [comment]
Oh, I understood your meaning. The basic setting is that the corpus only contains the abstract. But if the key points to the question lie in the rest part of the article, how can this setting run well? Does the paper Determine-search-predict has the same setting? If not, how is the wiki corpus built up?

**Comment by okhat** [comment]
We have multiple notebooks and multiple Wiki indexes: three in total. The paper and each notebook is explicit about the details of each Wiki index used.

For instance we also host a colbert index for the full DPR 2018 index. See it in the v1 branch. Different tasks call for different indexes by design.

**Comment by yhao-wang** [comment]
Thanks a lot!

**Comment by okhat** [comment]
No worries! Happy to provide further guidance if you have any followup questions!

**Comment by yhao-wang** [comment]
Hello, would you please release the checkpoint of Colbertv2 trained on NQ or TQ? 

Thanks a lot!

**Comment by okhat** [comment]
You can use the same checkpoint for all datasets/indexes
