### ISSUE TITLE
Support to use PEFT settings in BootStrapFineTune

### ISSUE THREAD

**Issue by ShwetaliShimangaud** [stanfordnlp/dspy#1342]
I am trying to fine tune Mistral 7B model and want to use PEFT setting. but getting following error :

File [~/.conda/envs/env/lib/python3.10/site-packages/dspy/teleprompt/finetune.py:166](http://localhost:8888/lab/tree/u/liferaft-nrc/notebooks/~/.conda/envs/unsloth_env/lib/python3.10/site-packages/dspy/teleprompt/finetune.py#line=165), in BootstrapFinetune.compile(self, student, teacher, trainset, valset, target, bsize, accumsteps, lr, epochs, bf16, int8, peft, path_prefix)
    164 compiler_config_ = dict(compiler_config)
    165 compiler_config_["save"] = compiler_config["save"] + "." + name
--> 166 best_ckpt_path = finetune_hf(training_data_path, target, compiler_config_)
    168 print(f"#> Best checkpoint path: {best_ckpt_path} for {name}")
    169 finetune_models[name] = dsp.HFModel(model=target, checkpoint=best_ckpt_path)  # best_ckpt_path

File [~/.conda/envs/env/lib/python3.10/site-packages/dsp/modules/finetuning/finetune_hf.py:342](http://localhost:8888/lab/tree/u/liferaft-nrc/notebooks/~/.conda/envs/unsloth_env/lib/python3.10/site-packages/dsp/modules/finetuning/finetune_hf.py#line=341), in finetune_hf(data_path, target, config)
    340 if config['peft']:
    341     model = AutoModelClass.from_pretrained(target, device_map='auto')
--> 342     task_type = TaskType.SEQ_2_SEQ_LM if encoder_decoder_model else TaskType.CAUSAL_LM
    343     peft_config = LoraConfig(task_type=task_type, inference_mode=False, r=8, lora_alpha=32, lora_dropout=0.1)
    344     model = get_peft_model(model, peft_config)

NameError: name 'TaskType' is not defined

Here is my code:
```
peft_settings = {
     'r' : 16, 
    'target_modules' : ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj",],
    'lora_alpha' : 16,
    'lora_dropout' : 0,
    'bias' : "none",    
    'use_gradient_checkpointing' : True,
    'random_state' : 3407,
    'use_rslora' : False, 
    'loftq_config' : None, 
}

teleprompter = BootstrapFinetune()
cot_compiled = teleprompter.compile(CoT(), 
                                    target='mistralai/Mistral-7B-Instruct-v0.3' ,
                                    trainset=sampled_example, 
                                    peft = True, bsize=1,accumsteps=4,lr=1e-4, epochs=5,bf16=True)

```

I tried using both options `peft=True` and `peft=peft_settings`

Any way to solve this?

**Comment by arnavsinghvi11** [comment]
Hi @ShwetaliShimangaud , ah it's because the[ import was left commented out ](https://github.com/stanfordnlp/dspy/blob/fd7924ce7d342deba846b6ea1c6c15a7f3a08475/dsp/modules/finetuning/finetune_hf.py#L28). LMK if uncommenting resolves the issue for you, and feel free to push a PR after testing!

**Comment by lavindu1133** [comment]
Hi @arnavsinghvi11 why is it commented?

**Comment by thoriqakbar0** [comment]
have the same issue and was asking why is it commented
