### ISSUE TITLE
Optimized prompt (COPRO) not used when calling the LLM

### ISSUE THREAD

**Issue by domsj-foodpairing** [stanfordnlp/dspy#1344]
I'm setting up an LLM (google vertex AI in my case) and phoenix tracing (to have visibility into what my dspy program is actually doing)
```python
lm = configure_dspy_vertex_ai()
phoenix_host = "localhost"
if phoenix_host:
    instrument_dspy_phoenix(phoenix_host)
```

next I define a simple dspy program

```python
import dspy
from pydantic import BaseModel

class Output(BaseModel):
    result: int

    def items(self):
        return [("result", self.result)]


class MySignature(dspy.Signature):
    function: str = dspy.InputField()
    input: int = dspy.InputField()
    output: Output = dspy.OutputField()

class MyModule(dspy.Module):
    def __init__(self):
        self.predictor = dspy.TypedChainOfThought(MySignature)
    
    def forward(self, input: int) -> int:
        return self.predictor(input=input, function="fibbonaci").output
```

I evaluate and optimize the prompt

```python
trainset = [
    dspy.Example(input=1, output=1).with_inputs("input"),
    dspy.Example(input=6, output=8).with_inputs("input"),
]

from random import random
def evaluation_metric(example: dspy.Example, prediction: Output, trace = None) -> bool:
    print(f"Example: {example.input} * 2 = {example.output}, Prediction: {prediction}")
    return example.output == prediction.result and random() > 0.3

from dspy.evaluate import Evaluate

evaluator = Evaluate(
    devset=trainset,
    metric=evaluation_metric,
    num_threads=4,
    display_progress=True,
    display_table=True,
)

evaluator(MyModule())

from dspy.teleprompt import COPRO

teleprompt = COPRO(prompt_model=lm, metric=evaluation_metric)
my_module = MyModule()
my_optimized_module = teleprompt.compile(my_module, trainset=trainset, eval_kwargs={})
```

The optimizer has created a new prompt
```python
my_optimized_module.dump_state()
```
> {'predictor.predictor': {'lm': None,
  'traces': [],
  'train': [],
  'demos': [],
  'signature_instructions': '## Optimized Function Application\n\n**Basic Instruction:** Given the fields `function`, `input`, produce the fields `output`.\n\n**Proposed Instruction:**  You are a powerful function-executing AI. Your goal is to flawlessly apply the provided `function` to the given `input` and return the accurate `output`. \n\n**Here is the function you must execute:** ```<insert function>```\n\n**Here is the input for this function**: ```<insert input>```\n\nNow, please calculate and clearly present:\n\n**Proposed Prefix For Output Field:** **Output:**',
  'signature_prefix': 'This is a great start! Your proposed instruction is much more specific and action-oriented, which can be helpful for large language models. \n\nHere\'s a slightly modified version that incorporates best practices and addresses potential issues:\n\n**Basic Instruction:** Given the fields `function`, `input`, produce the fields `output`.\n\n**Proposed Instruction:** \nYou are a powerful function-executing AI. Your goal is to apply the provided function to the given input and return the accurate output.  \n\n**Function:**\n```tool_code\n<insert function> \n```\n\n**Input:**\n```json\n<insert input>\n```\n\n**Output:** \n\n**Proposed Prefix For Output Field:**  (Leave this blank; let the model format the output naturally)\n\n**Explanation of Changes:**\n\n* **Clear Separation:** Using headings like "Function" and "Input" improves readability and helps the model distinguish between instructions and the actual data.\n* **Code Blocks:** Enclosing the function and input within code blocks (` ``` `) further emphasizes their distinct roles and can help with parsing, especially for programming-related tasks.\n* **JSON for Input:**  Representing the input as a JSON object can be beneficial if the input is structured data. This promotes consistency and makes it easier for the model to process.\n* **Flexibility in Output:**  Instead of forcing a specific prefix for the output, allow the model to present the result naturally. This avoids unnecessary formatting constraints and allows for more human-like responses.\n\n**Additional Tips:**\n\n* **Context is Key:** If the function or input requires specific domain knowledge, provide a brief explanation or example to guide the model.\n* **Test and Iterate:** Experiment with different instruction variations and evaluate the model\'s performance to find the most effective approach.'}}

Using the optimized module however results in
```python
lm.history.clear()
my_optimized_module.forward(3)
print(lm.history)
```

> [{'prompt': 'Given the fields `function`, `input`, produce the fields `output`.\n\n---\n\nFollow the following format.\n\nFunction: ${function}\n\nInput: ${input}\n\nReasoning: Let\'s think step by step in order to ${produce the output}. We ...\n\nOutput: ${output}. Respond with a single JSON object. JSON Schema: {"properties": {"result": {"title": "Result", "type": "integer"}}, "required": ["result"], "title": "Output", "type": "object"}\n\n---\n\nFunction: fibbonaci\n\nInput: 3\n\nReasoning: Let\'s think step by step in order to',
  'response': {'prompt': 'Given the fields `function`, `input`, produce the fields `output`.\n\n---\n\nFollow the following format.\n\nFunction: ${function}\n\nInput: ${input}\n\nReasoning: Let\'s think step by step in order to ${produce the output}. We ...\n\nOutput: ${output}. Respond with a single JSON object. JSON Schema: {"properties": {"result": {"title": "Result", "type": "integer"}}, "required": ["result"], "title": "Output", "type": "object"}\n\n---\n\nFunction: fibbonaci\n\nInput: 3\n\nReasoning: Let\'s think step by step in order to',
   'choices': [{'text': '```json\n{\n "result": 2\n}\n```\n',
     'safetyAttributes': {<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 1>: <HarmProbability.NEGLIGIBLE: 1>,
      <HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 2>: <HarmProbability.NEGLIGIBLE: 1>,
      <HarmCategory.HARM_CATEGORY_HARASSMENT: 3>: <HarmProbability.NEGLIGIBLE: 1>,
      <HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 4>: <HarmProbability.NEGLIGIBLE: 1>}}]},
  'kwargs': {'top_k': 1,
   'temperature': 0.7,
   'max_output_tokens': 8192,
   'stop_sequences': None,
   'top_p': 1.0},
  'raw_kwargs': {}},
 {'prompt': 'Given the fields `function`, `input`, produce the fields `output`.\n\n---\n\nFollow the following format.\n\nFunction: ${function}\n\nInput: ${input}\n\nReasoning: Let\'s think step by step in order to ${produce the output}. We ...\n\nOutput: ${output}. Respond with a single JSON object. JSON Schema: {"properties": {"result": {"title": "Result", "type": "integer"}}, "required": ["result"], "title": "Output", "type": "object"}\n\n---\n\nFunction: fibbonaci\n\nInput: 3\n\nReasoning: Let\'s think step by step in order to\n```json\n{\n "result": 2\n}\n```\n\nOutput:',
  'response': {'prompt': 'Given the fields `function`, `input`, produce the fields `output`.\n\n---\n\nFollow the following format.\n\nFunction: ${function}\n\nInput: ${input}\n\nReasoning: Let\'s think step by step in order to ${produce the output}. We ...\n\nOutput: ${output}. Respond with a single JSON object. JSON Schema: {"properties": {"result": {"title": "Result", "type": "integer"}}, "required": ["result"], "title": "Output", "type": "object"}\n\n---\n\nFunction: fibbonaci\n\nInput: 3\n\nReasoning: Let\'s think step by step in order to\n```json\n{\n "result": 2\n}\n```\n\nOutput:',
   'choices': [{'text': '```json\n{\n "result": 2\n}\n```',
     'safetyAttributes': {<HarmCategory.HARM_CATEGORY_HATE_SPEECH: 1>: <HarmProbability.NEGLIGIBLE: 1>,
      <HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: 2>: <HarmProbability.NEGLIGIBLE: 1>,
      <HarmCategory.HARM_CATEGORY_HARASSMENT: 3>: <HarmProbability.NEGLIGIBLE: 1>,
      <HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: 4>: <HarmProbability.NEGLIGIBLE: 1>}}]},
  'kwargs': {'candidate_count': 1,
   'top_k': 1,
   'temperature': 0.0,
   'max_output_tokens': 4096,
   'stop_sequences': None,
   'top_p': 1.0},
  'raw_kwargs': {'max_tokens': 4096, 'n': 1, 'temperature': 0.0}}]

This show the module doesn't use the optimized prompt.
(It also shows 2 calls to the LLM, where there should only be 1 afaict!)
Phoenix confirms the same.

Am I doing something wrong? Or is this a bug in dspy?
I'm using dspy-ai==2.4.12

**Comment by okhat** [comment]
COPRO is never recommended. It's more of a baseline. (I didn't check the details here but I suspect that COPRO just couldn't do better than your original prompt, so it did the right thing. It stuck to the original prompt.)

Our docs generally recommend that you use random search first, and get it to work, then upgrade to MIPROv2.

**Comment by okhat** [comment]
Looking more closely, you're using TypedChainOfThought, so you might need to use a Typed optimizer accordingly. I'm not sure that COPRO can handle Typed predictors yet.
