### ISSUE TITLE
Integrate LiteLLM

### ISSUE THREAD

**Issue by lawliet19189** [stanfordnlp/dspy#1357]
## High-level explanation of the problem

DSPy currently supports many LLM providers, including OpenAI, Anthropic, and (~) Huggingface, to name a few.  Each of the LLM providers has its own wrapper script, such as `module/anthropic` for the Anthropic provider. This helped us in handling the custom API interface that LLM providers had. What this means:

- Each LLM provider wrapper must be manually updated when an LLM API interface changes. This may change due to the introduction of new parameters, API refactoring, and significant feature upgrades.
- Supporting a New LLM provider requires creating a new wrapper script and writing many redundant code.
- Since API interfaces differ across API providers, standardization is lacking.

## Suggested Solution

Integrate [LiteLLM](https://github.com/BerriAI/litellm), which helps manage, standardize, and scale LLM providers. Here is a short summary of what LiteLLM can help us with:

- Supporting New LLM providers
- Maintaining Existing LLM Providers (new features from providers are easy to integrate!)
- Standardization Across LLM providers (To a certain satisfactory degree)

## Changes Necessary (only included significant ones)

- We will create a new centralized LLM provider wrapper that implements LiteLLM. The wrapper will be the entry point for all the LLM usage.
- We will start deprecating individual LLM provider wrappers such as `module/anthropic`. NOTE: This will not break existing code when users upgrade to the latest version, but they may miss out on new features.

**Comment by okhat** [comment]
Thank you @lawliet19189 ! This is the right path indeed. There's ongoing work on this, by @hmoazam and in the "rc" branch. Maybe coordinating with Hanna makes sense? She has a more detailed plan.
