### ISSUE TITLE
 ModuleNotFoundError: No module named 'dspy.predict.llamaindex'

### ISSUE THREAD

**Issue by simplexityware** [stanfordnlp/dspy#1359]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-12-cee46cbc595c>](https://localhost:8080/#) in <cell line: 2>()
      1 from llama_index.core.query_pipeline import QueryPipeline as QP, InputComponent, FnComponent
----> 2 from dspy.predict.llamaindex import DSPyComponent, LlamaIndexModule
      3 
      4 dspy_component = DSPyComponent(
      5     dspy.ChainOfThought(GenerateAnswer)

ModuleNotFoundError: No module named 'dspy.predict.llamaindex'

**Comment by arnavsinghvi11** [comment]
Hi @simplexityware , this import works for me, but there's a [related issue](https://github.com/stanfordnlp/dspy/issues/1300) with DSPyComponent
