### ISSUE TITLE
Need more info or documentation on dspy.settings.experimental

### ISSUE THREAD

**Issue by tanzeel291994** [stanfordnlp/dspy#1371]
In ChainOfThought.py and Predict.py few of the conditions depend on dspy.settings.experimental
` if dsp.settings.experimental:
            completions = new_generate(lm, signature, dsp.Example(demos=demos, **kwargs), **config)
        else:
            completions = old_generate(demos, signature, kwargs, config, self.lm, self.stage)
`

` if dspy.settings.experimental:
            desc = "${produce the output fields}. We ..."`
            
 1. dspy.settings.experimental not callleble from jupyter notebook 
 _AttributeError: 'super' object has no attribute '__getattr__'_
 2. If its legacy code /or soon going be deprecated?
 3.How to turn it on/off ?

**Comment by okhat** [comment]
Use dspy.configure(experimental=True)
