### ISSUE TITLE
Using GPT for evaluation function

### ISSUE THREAD

**Issue by darinkishore** [stanfordnlp/dspy#139]
Is this possible/financially feasible? Is the evaluation only used when the pipeline is teleprompted, or is it run for every prediction?

**Comment by okhat** [comment]
Share more information below. Anyway with a model like gpt 3.5 it’s definitely feasible

**Comment by darinkishore** [comment]
@okhat I'm wondering if I can basically **define an arbitrary set of criteria** and **have GPT run** a **human**-like **evaluation**. 

Current project is crisis detection, so if I want to use DSPy to generate examples of crises, I would call 3.5 on let's say 4 different criteria, with a function output {"pass": "yes"/"no"}. 

Example utterance: "My mom just died. I've been struggling in college. I'm perpetually sad and don't know what to do."

would identify the crises as "mom dying", "academic failure", internal state as "perpetual sadness". 

We have a certain set of criteria (that we need to refine) for what a "crisis" is. If the model splits out "mom dying, academic failure" and misses the point on the internal state , saying "very happy" instead, I'd like to be able to catch something like that and have it fail the evaluation using 3.5. 


I have 17,000 and rapidly growing conversations about crises, each with 4-7 identified on average per conversation. With 3.5, is it going to call the evaluation function *every single time* the "Predict" is called? Or will it just use the evaluation function in the teleprompter stage when the prompts are being optimized? 

I hope that's clear!

**Comment by okhat** [comment]
Yes that's clear! Thank you.

Evaluation is only conducted when you're compiling or evaluating your program.

It's not involved when you're just running your program for inference.

**Comment by darinkishore** [comment]
@okhat Thank you for the response! 

Is there a function that describes total # of calls to evaluate function given `n_train` examples in training and `n_dev` examples in dev? If not, why is that challenging to know? 

I know I've been all over your issues page, but I think this is one of the best innovations and one of the hugest leaps forward that has come out since the 3.5-turbo api released. I want to understand it so I can use it well.
