### ISSUE TITLE
How to make this reply only with the answer?

### ISSUE THREAD

**Issue by haalcala** [stanfordnlp/dspy#1404]
How to make this reply only with the answer?

![image](https://github.com/user-attachments/assets/fe40e8c7-dba5-4184-b4ef-df75278c975a)

**Comment by haalcala** [comment]
Sorry.  Been trying a few things and it's already late at night and I didn't notice that I was asking for a joke which is typically a QnA type.

**Comment by haalcala** [comment]
Ooppss, sorry, there it is! Where do I change thing template?  And I thought I don't have to think of how the prompt will be?

![image](https://github.com/user-attachments/assets/4bcfa901-169d-43e0-9581-11d7a9ee030f)

**Comment by haalcala** [comment]
Even GPT4 is confused.

I have done a lot prompting in the past, so I thought I'll try DSPy to brute force prompting as I thought it would do ... but how it fails just for simple case like this?  Which part again that I don't need to think about the prompt itself?

![image](https://github.com/user-attachments/assets/4faf63cb-7a22-47b5-80f3-5cd53f9a8d14)

**Comment by okhat** [comment]
Chat models require special treatment, if you aren't compiling your program.

Set `dspy.configure(experimental=True)` for this and let us know.

**Comment by okhat** [comment]
Fixed in DSPy 2.5 if you follow the migration guide!
