### ISSUE TITLE
Roadmap: Integrate with pyvene and pyreft

### ISSUE THREAD

**Issue by AriMKatz** [stanfordnlp/dspy#1412]
Both in Stanford nlp GitHub org. I haven't done experiments comparing them to pure prompt engineering, but my sense is that there will be places each one excels, particularly with very granular changes, deep or robust steering (like gokden gate claude) and perhaps an ensemble will give sota in many situations. Also don't have to worry about Prompt leakage.

Pyreft might need special user space API but pyvene can just accept xy pairs

**Comment by okhat** [comment]
Hey @AriMKatz ! Thanks for the suggestion! This would probably fit as an implementation of BootstrapFinetune. I perceive PyREFT as a form of finetuning, and I imagine it's probably less expressive from a quality standpoint in our setting than just doing full finetuning? Of course, it has other advantages like parameter efficiency.
