### ISSUE TITLE
Evaluate: numerical metric can result in logging e.g. "Average Metric: 49 / 10"

### ISSUE THREAD

**Issue by raphaelmerx** [stanfordnlp/dspy#1426]
## Description

When using a metric that can be higher than 1, evaluate can produce logs like "Average Metric: 49 / 10"

This is due to the score being added to the count of correct answers, without normalising: 
https://github.com/stanfordnlp/dspy/blob/4323844ccae2289d7505a8f2922183140ed289fa/dspy/evaluate/evaluate.py#L120

Maybe for now the docs should mention that scores should be normalised between 0 and 1?

**Comment by okhat** [comment]
Thanks @raphaelmerx ! I don't see a problem here. The score can exceed 1.0 and it's OK.
