### ISSUE TITLE
Support of Wenxin's LLM

### ISSUE THREAD

**Issue by walkbird** [stanfordnlp/dspy#1433]
Hello everyone!

This framework is very useful, and I plan to use it in my project. My project intends to use Wenxin's large language model, and I hope to optimize the prompts based on it. Does anyone know if there's already an implementation for calling Wenxin's LLM? If not, I plan to work on this. 

Thank you!

**Comment by okhat** [comment]
You should be able to use this by hosting on VLLM or SGLang and connecting via a dspy LM client
