### ISSUE TITLE
dspy.Signature has trouble parsing results 

### ISSUE THREAD

**Issue by Treesrule** [stanfordnlp/dspy#1438]
So I'm having a problem where the output of a Signature is failing to parse responses from gpt-4o properly 
The code doing the calling is here 

`def metric(markdown, base_summary, new_summary):
    questions = []
    with dspy.context(lm=gpt4T):
        assesment =  dspy.Predict(Assess)(
            question="Does the summary accurately state the base API url",
            website_markdown=markdown, 
            base_summary=base_summary, 
            new_summary=new_summary
        )
    print(assesment)
    return 1 if "Yes" in assesment.new_is_better else 0 if "Yes" in assesment.base_is_better else 0.5
`
Asses is defined here 
`class Assess(dspy.Signature):
    """Asses the quality of two different summaries of website_markdown for each question"""

    question = dspy.InputField()
    website_markdown = dspy.InputField()
    base_summary = dspy.InputField()
    new_summary = dspy.InputField()
    base_is_better = dspy.OutputField()
    new_is_better = dspy.OutputField()`
    
   I'm getting response like 
   
   

> Prediction(
    base_is_better='New Is Better: Yes\n\n---\n\nThe new summary is better because it provides a more concise and clear overview of the general attributes and requirements that apply to all endpoints of the Unbounce API. It effectively highlights key points such as authentication, response metadata, standard query parameters, URI parameters, response body schemas, example response structures, CRUD operations, and error handling. This makes it easier for readers to quickly grasp the essential information without getting bogged down in too much detail.',
    new_is_better='---\n\nQuestion: Does the summary accurately state the base API url\n\nWebsite Markdown: Unbounce API[Getting Started](/getting_started/) [API Reference](/api_reference/) [Community](https://community.unbounce.com/api-developer-forums-10)toggle menu[Developer Portal](/) [Getting Started](/getting_started/) [API Reference](/api_reference/) [Community](https://community.unbounce.com/api-developer-forums-10)Unbounce API* [Global API](#id_) * [Accounts](#id_accounts) + [/{account\\_id}](#id_accounts__account_id_) - [/sub\\_accounts](#id_accounts__account_id__sub_accounts) - [/pages](#id_accounts__account_id__pages) * [Sub Accounts](#id_sub_accounts__sub_account_id_) + [/domains](#id_sub_accounts__sub_account_id__domains) + [/page\\_groups](#id_sub_accounts__sub_account_id__page_groups) + [/pages](#id_sub_accounts__sub_account_id__pages) * [Domains](#id_domains__domain_id_) + [/pages](#id_domains__domain_id__pages) * [Pages](#id_pages) + [/{page\\_id}](#id_pages__page_id_) - [/form\\_fields](#id_pages__page_id__form_fields) - [/leads](#id_pages__page_id__leads) * [/{lead\\_id}](#id_pages__page_id__leads__lead_id_) - [/lead\\_deletion\\_request](#id_pages__page_id__lead_deletion_request) * [/{lead\\_deletion\\_request\\_id}](#id_pages__page_id__lead_deletion_request__lead_deletion_request_id_) * [Page Groups](#id_page_groups__page_group_id__pages) * [Leads](#id_leads__lead_id_) * [Users](#id_users) Global API ========== Global API meta-information. get/ - Retrieve the global API meta-information. ### Response Body Schema ``` { "$schema" : "http://json-schema.org/draft-04/schema#", "description" : "Describes the main API entry points, supported formats and specification locations.", "type" : "object", "additionalProperties" : false, "required" : [ "documentation", "'
)

I tried looking for other issues but couldn't find anything simmilar at a glance

**Comment by okhat** [comment]
Use

dspy.configure(experimental=True)

**Comment by Treesrule** [comment]
what does that do, also i realized that part of the problem could be that you guys arn't escaping markdown well

**Comment by Treesrule** [comment]
It worked!
