### ISSUE TITLE
Evaluate - display_table option doesn't work

### ISSUE THREAD

**Issue by dorperetz-fiverr** [stanfordnlp/dspy#1449]
Hey, when using display_table=True

i'm getting this weird object pointer print instead of the actual table:
`<pandas.io.formats.style.Styler at 0x147457ac0>`
![image](https://github.com/user-attachments/assets/8f6a4e9b-d31f-48da-9fd0-9545636b1e47)

additional details:
i see that this import works successfully:
![image](https://github.com/user-attachments/assets/ac544e17-fa72-4f2f-80e8-7b50d95bc9e1)

(not reaching the `ipython_display = print` part)

**Comment by okhat** [comment]
It only works in notebooks. Maybe a good PR is to make it work in scripts?

**Comment by dbczumar** [comment]
Filed https://github.com/stanfordnlp/dspy/pull/1472 to address this

**Comment by okhat** [comment]
Than you @dbczumar !!
