### ISSUE TITLE
Generate changelog from commit history (git log)

### ISSUE THREAD

**Issue by nongrata081** [stanfordnlp/dspy#1455]
Would be nice to have detailed changelogs in the [DSPy Releases page](https://github.com/stanfordnlp/dspy/releases), generated with one shell command with [commitizen](https://commitizen-tools.github.io/commitizen/). Releases could look like [this](https://github.com/nongrata081/ng-assessment/releases). Includes:

- CLI-utility for creating [Conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- Automatic version bump using [semantic versioning](https://semver.org/) based on the latest type of commits.
- Possibility to **generate a changelog** using [Keep a changelog](https://keepachangelog.com/)

Please let me know if this is a desired functionality. I can look into creating a Pull Request for this.

**Comment by okhat** [comment]
Sounds like a good idea. Open for a PR?

**Comment by nongrata081** [comment]
Yes! Will do

**Comment by nongrata081** [comment]
[Generated changelog](https://github.com/nongrata081/dspy/blob/feature/changelog/CHANGELOG.md) example.

[Commit](https://github.com/nongrata081/dspy/commit/7bb4a8f5a78e757be30ac1c16ddc321b2fbb8f75).
[Breaking changes rendering example](https://github.com/nongrata081/dspy/commit/ef09c1232b89d44d69904a63620d4425fb8bd208).

[How to commit](https://github.com/nongrata081/dspy/blob/feature/changelog/CONTRIBUTING.md#how-to-commit)
[How to generate changelog (manually)](https://github.com/nongrata081/dspy/blob/feature/changelog/CONTRIBUTING.md#how-to-generate-changelog-manually)
[How commits are rendered in the changelog](https://github.com/nongrata081/dspy/blob/feature/changelog/CONTRIBUTING.md#how-commits-are-rendered-in-the-changelog)

<img width="806" alt="commitizen-cli-prompt-for-commits" src="https://github.com/user-attachments/assets/c028b475-0158-4004-9f0c-6abf04955e21">

**Comment by okhat** [comment]
Thanks so much @nongrata081 ! Seems like github does it natively now?? See the last 2 releases and lmk if they look fine

**Comment by nongrata081** [comment]
> Thanks so much @nongrata081 ! Seems like github does it natively now?? See the last 2 releases and lmk if they look fine

Looks great! 👍
