### ISSUE TITLE
Does dspy.GROQ actually works?

### ISSUE THREAD

**Issue by simplexityware** [stanfordnlp/dspy#1459]
according to https://dspy-docs.vercel.app/api/language_model_clients/Groq

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-2-d7f5c6b1fffa>](https://localhost:8080/#) in <cell line: 12>()
     10 # )
     11 
---> 12 llm = dspy.GROQ(model="llama-3.1-70b-versatile", api_key = GROQ_API_KEY )
     13 dspy.settings.configure(lm=llm)

AttributeError: module 'dspy' has no attribute 'GROQ'
```

I am really keen to complete this tutorial using the free GROQ/LLama3 service in the cloud - https://github.com/stanfordnlp/dspy/blob/main/examples/llamaindex/dspy_llamaindex_rag.ipynb - to use as a reference for other projects involving the use of DSPy and LlamaIndex.

Thank you for your kind attention.

**Comment by hacker-4-good** [comment]
@simplexityware use 
`dspy.GroqLM(model="llama-3.1-70b-versatile", api_key = GROQ_API_KEY)`

**Requirements** :- `pip install groq`

**codebase link for GroqLM :- [GroqLM](https://github.com/stanfordnlp/dspy/blob/main/dsp/modules/groq_client.py)**

**below is the screenshot of GroqLM class for reference**
![image](https://github.com/user-attachments/assets/0bda3bd6-f4a0-4642-b49c-422cb97bd540)

**Comment by okhat** [comment]
fixed by recent PR, thanks @hacker-4-good

**Comment by simplexityware** [comment]
> @simplexityware use `dspy.GroqLM(model="llama-3.1-70b-versatile", api_key = GROQ_API_KEY)`
> 
> **Requirements** :- `pip install groq`
> 
> **codebase link for GroqLM :- [GroqLM](https://github.com/stanfordnlp/dspy/blob/main/dsp/modules/groq_client.py)**
> 
> **below is the screenshot of GroqLM class for reference** ![image](https://private-user-images.githubusercontent.com/91790864/365459757-0bda3bd6-f4a0-4642-b49c-422cb97bd540.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjc0NTEsIm5iZiI6MTcyNjEyNzE1MSwicGF0aCI6Ii85MTc5MDg2NC8zNjU0NTk3NTctMGJkYTNiZDYtZjRhMC00NjQyLWI0OWMtNDIyY2I5N2JkNTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA3NDU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5NzViODQzNDhlYTUxOGI2OGNiM2U4OGRjNGU2Y2EyMjhiMDQ5NTgwZjkzZTZlZDVmZmNkNDY0YjNhMzk1MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p_M-EKY7h7XHNBMwA5A0wlHu7_7tuaR41jPtoMklUz8)

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-2-03daf97e6575>](https://localhost:8080/#) in <cell line: 12>()
     10 # )
     11 
---> 12 llm = dspy.GroqLM(model="llama-3.1-70b-versatile", api_key = GROQ_API_KEY )
     13 dspy.settings.configure(lm=llm)

AttributeError: module 'dspy' has no attribute 'GroqLM'
```

**Comment by hacker-4-good** [comment]
@simplexityware have you update dspy-ai
