### ISSUE TITLE
LLM acting as a Tutor to explain the content of document 

### ISSUE THREAD

**Issue by stepahane** [stanfordnlp/dspy#149]
Hi
I work as datascientist in the french ministery of justice. 
I have 2 questions : 
1° Is it possible to use dspy to work on a french corpus (for instance court decisions) ?
2° Is it possible to use it with objective function in order to use llm a tutor that will explain a court decision. 
The public to be tutored can have different 'profile' in term of 
a) knowledge of the law, 
b) cognitive ability 
c) knowledge of the french language.
So the application has to asses the user (knowledge, cognitive abitlity, knowledge of the french) and adapt.

It's not an issue but thanks for your answer !

**Comment by arnavsinghvi11** [comment]
Hi,

While not fully tested yet, DSPy likely can support queries in other languages with certain settings depending on your use case. For instance, this will largely depend on the language compatibilities of the language models you use for queries or the interpretability within the retrieval models you use for understanding French within your data. 
As a brief test, writing queries in French with lm set to gpt-3.5-turbo and retriever ColBERTv2 (as in the intro notebook) seems to work fine (apologies for any French mistranslations!): 

```
generate_answer = dspy.Predict(BasicQA)
pred = generate_answer(question="Quelle est la capitale de la France et qui est son président actuel?")
print(f"Predicted Answer: {pred.answer}")

Predicted Answer: Paris, Emmanuel Macron

```
I presume similar behavior would take place when inputting French documents.

Regarding your second question, this use case definitely is supported within DSPy. I recommend checking out the README and intro notebook on Colab to further understand how Signatures and Modules can help build out this question. 

Please let me know if you have any additional questions!

**Comment by stepahane** [comment]
As a retreiver I'm planing to use vectordb and llama_index as a framework. Is it possible ?

I'm interresterd to use dspy for provinding the best answer (in term of cognitve ability, level in french, and knowledge of the low) adapted to the reader. The cahbot has first to assess what kind of user is connected (the content of the decision of justice, the question asked to the chabot, the age and nationality of the user... can give clues) and respond to the question of the user in the best way. It will adapt as the conversation continues in order to best fit to the user profile (as it is understood by the chabot). Do you think this kind of dynamic optimisation can be done with dspy ? how ?

**Comment by stepahane** [comment]
I'm interested to use dspy for the LLM to act as a tutor. My usecase is to use an LLM for explaining a court decision (by default to the people concerned by this decision). In order to do that, before each response, the LLM should assess the level of his user and then provide answer adapted to his user (in term of cognitve ability, level in french, and knowledge of the low). To assess the profile of the connected user we can use (the content of the decision of justice, the question asked to the chabot, the age and nationality of the user... can give clues). The adapation of the user profile is a continuous process, as it is better discover at each question (how many times the same point has to be explained, what is the level in french, what is the level in law understanding). So the llm sould adapt as the conversation continues. Do you think this kind of dynamic optimisation can be done with dspy ? I have seen teacher and student in the telepromter and I guess that I can use this pattern for my problem
