### ISSUE TITLE
o1-preview problem

### ISSUE THREAD

**Issue by MindsightsAI** [stanfordnlp/dspy#1504]
Version: 2.4.16
```2024-09-17 14:02:24 - root - ERROR - Error occurred: Error code: 400 - {'error': {'message': "Unsupported parameter: 'stop' is not supported with this model.", 'type': 'invalid_request_error', 'param': 'stop', 'code': 'unsupported_parameter'}}``

**Comment by arnavsinghvi11** [comment]
Hi @MindsightsAI , can you share how you are querying o1-preview in DSPy?

is this potentially resolved by using the new dspy.LM wrapper around LiteLLM?
`lm = [dspy.LM](https://github.com/stanfordnlp/dspy/blob/main/dspy/clients/lm.py)(...)`

**Comment by okhat** [comment]
Tagging @isaacbmiller too

**Comment by isaacbmiller** [comment]
I think we can close with 2.5 out now and litellm support here.

Feel free to reopen if you are using litellm and it still doesn't work

**Comment by younes-io** [comment]
https://github.com/stanfordnlp/dspy/issues/1516#issuecomment-2377407534
