### ISSUE TITLE
Issue: Unable to Use Multiple LMs with Different Backend Servers

### ISSUE THREAD

**Issue by LetianLee** [stanfordnlp/dspy#1507]

**Comment by okhat** [comment]
Try the new dspy.LM which is a wrapper around LiteLLM for all LMs. We'll be migrating to it across the board.

```python
lm = dspy.LM("openai/meta-llama/Meta-Llama-3-8B-Instruct", model_type="text OR chat", api_base="here", api_key="could be empty")
```

use `openai/` as a prefix for any openai-compatible server like VLLM
