### ISSUE TITLE
Missing headers as http_request setting simple quick fix needed

### ISSUE THREAD

**Issue by dgonier** [stanfordnlp/dspy#1513]
You need to modify your hf_client.py because there are cases where uses need to pass in special headers in their request. You can easily do this by making the following changes

        self.http_request_kwargs = http_request_kwargs or {}
        self.model_type = model_type
        self.headers = self.http_request_kwargs.get('headers', {"Content-Type": "application/json"})
        self.http_request_kwargs.pop('headers')

**Comment by arnavsinghvi11** [comment]
Thanks @dgonier ! updated on the latest [commit](https://github.com/stanfordnlp/dspy/commit/bdf52ca21175f0aa0ca9e9ebc54fe1d7d059a06f)
