### ISSUE TITLE
The structured output of o1 is not very good and very messy.

### ISSUE THREAD

**Issue by zouhuigang** [stanfordnlp/dspy#1516]
```

class Assess(dspy.Signature):
    """Assess the quality of a answer along the specified dimension."""
    assessed_text = dspy.InputField()
    assessment_question = dspy.InputField()
    assessment_answer = dspy.OutputField(desc="Yes or No")

def metric_gpt4(example: QAModel, pred: QAModel) -> bool:
    gpt4T = dspy.OpenAI(model='o1-preview', max_tokens=1000, model_type='chat')
    question, answer, pred_answer = example.question, example.answer, pred.answer

    correct = f"The text should answer `{question}` with `{answer}`. Does the assessed text contain this answer?"

    with dspy.context(lm=gpt4T):
        correct_result = dspy.Predict(Assess)(assessed_text=pred_answer, assessment_question=correct)
    return correct_result.assessment_answer.lower() == 'yes'

```
o1-preview  correct_result.assessment_answer output:

```
'Assessment Answer: Yes'
```

o1-min output:

```
  Prediction(
      assessment_answer='Assessed Text: 排版软件两台电脑都可以安装的, 但是不支持两台电脑同时使用  \nAssessment Question: The text should answer `排版软件，同时可以装2个电脑吗` with `排版软件两台电脑都可以安装的, 但是不支持两台电脑同时使用`. Does the assessed text contain this answer?  \nAssessment Answer: Yes'
  )
  ```

**Comment by okhat** [comment]
For chat LMs, try:

dspy.configure(experimental=True)

**Comment by okhat** [comment]
@isaacbmiller Could be worth looking into this, especially with the new dspy.LM

**Comment by younes-io** [comment]
When I do this:

```python
import dspy
import json
import openai

gpt_lm = dspy.OpenAI(
    model='gpt-3.5-turbo',
)

dspy.configure(experimental=True)
dspy.settings.configure(lm=gpt_lm)

gpt_lm.max_tokens = None
gpt_lm.max_completion_tokens = None

response = gpt_lm("Hello")
print(response)
```
['Hello! How can I assist you today?']

However, when I use `o1-mini` or `o1-preview`, it doesn't work:

```python
import dspy
import json
import openai

gpt_lm = dspy.OpenAI(
    model='o1-preview'             // <------------ same for 'o1-mini'
)

dspy.configure(experimental=True)
dspy.settings.configure(lm=gpt_lm)

gpt_lm.max_tokens = None
gpt_lm.max_completion_tokens = None

response = gpt_lm("Hello")
print(response)
```

TypeError: Completions.create() got an unexpected keyword argument 'max_completion_tokens'

**Comment by isaacbmiller** [comment]
Try:
```python
import dspy
import json
import openai

gpt_lm = dspy.LM(
    model='o1-preview'             // <------------ same for 'o1-mini'
)

dspy.settings.configure(lm=gpt_lm)

response = gpt_lm("Hello")
print(response)
```

**Comment by younes-io** [comment]
@isaacbmiller 

```bash
BadRequestError: litellm.BadRequestError: OpenAIException - Error code: 400 - {'error': {'message': "Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.", 'type': 'invalid_request_error', 'param': 'max_tokens', 'code': 'unsupported_parameter'}}
```

**Comment by okhat** [comment]
Someone needs to look into LiteLLM's strategy for o1, we can follow the same.

**Comment by arnavsinghvi11** [comment]
> ```shell
> BadRequestError: litellm.BadRequestError: OpenAIException - Error code: 400 - {'error': {'message': "Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.", 'type': 'invalid_request_error', 'param': 'max_tokens', 'code': 'unsupported_parameter'}}
> ```

[OpenAI changed their API for o1](https://community.openai.com/t/why-was-max-tokens-changed-to-max-completion-tokens/938077/4) to support `max_completion_tokens` over `max_tokens` going forward. 

This was a relevant [PR](https://github.com/BerriAI/litellm/pull/5691/files#diff-848966526203f3e13b8e4d6d610f6cfe40fd4a5d6178f01f04b3f15d97f68c09) for supporting o1 in LiteLLM. Seems like you just need to set `max_completion_tokens` instead of `max_tokens` @younes-io

**Comment by okhat** [comment]
@arnavsinghvi11 It's a bit weird, because we want DSPy to be consistent. Right now we do by default always have max_tokens! Maybe we should convert max_tokens to max_completion_tokens if the model is o1, if litellm isn't gonna do that for us?

**Comment by okhat** [comment]
Actually @younes-io I think you may just need to upgrade litellm. It works well for me!

```python
dspy.LM('o1-mini', temperature=1.0)('hello')
```

**Comment by younes-io** [comment]
@okhat : Thank you for the feedback. I still believe this is an issue from an end-user perspective. By installing the latest DSPy version, everything should be ready to run (instead of having the end-user explicitly upgrade internal or other packages). In my use case, I didn't have to upgrade litellm, I used `litellm.drop_params=True` and I could have it work.

However, my real use case is `TypedPredictor(CustomType)`, and it does fail in this case.

**Comment by denisergashbaev** [comment]
I am encountering something similar and posted it here: https://github.com/stanfordnlp/dspy/issues/1847
