### ISSUE TITLE
Unify the retrievers into dspy.Retrieve

### ISSUE THREAD

**Issue by okhat** [stanfordnlp/dspy#152]
Right now, there's dspy.Retrieve (which supports colbertv2) and there's dspy.Pinecone and dspy.Pyserini.

These should all work using dspy.Retrieve by simply updating `dspy.settings.configure(rm=colbert or pyserini or pinecone)`

**Comment by okhat** [comment]
Is this something that would be of interest to you, @jasper-xian or @msnidal ?

**Comment by jasper-xian** [comment]
sure, this is something I can look into!

**Comment by okhat** [comment]
Super cool! Lmk if it’s not clear where to start. Btw if this needs making changes to the colbert class that’s ok

**Comment by darinkishore** [comment]
Side note, but is it possible to compile retrieval models using the teleprompter as well? All examples seem to focus on the generation evaluation for pipeline. I'd like to tune dense searching pyserini to retrieve based on maximizing a metric, in this case (GPT-eval func +  averaged entropy).

**Comment by okhat** [comment]
@darinkishore Optimizing retrieval models during compilation is a key future direction. (It would be a nice paper to write.) The main challenge is how do you determine the supervision signal for the retrievers. If you have an idea to try there, it's entirely doable to add a Teleprompter that does that.

**Comment by darinkishore** [comment]
@okhat Thank you for the next step guidance! I'm currently working on a diff paper right now, but I think compiled targetable-output retreival models can create a LOT of value as a fine-tuned system component, especially for really nuanced use cases. 

I'd like to begin ideation on this. Can you point me to what ideas/goals to consider in the teleprompter architecture to achieve this, and an example of the problem you specified?

**Comment by jasper-xian** [comment]
hey @okhat, did a first glance and noticed that the current structure for pyserini/pinecone is this:

```python
retriever_model = dspy.Pinecone(...) # or dspy.Pyserini(...)
dspy.settings.configure(rm=retriever_model)
```

From the pyserini example notebook, we can then use pyserini with dspy.Retrieve:

```python
retrieve = dspy.Retrieve(k=3)
topK_passages = retrieve(example_question).passages
```

Could you elaborate a bit more on what you mean by having pyserini/pinecone work under `dspy.Retrieve`? Specifically, how does `dspy.Retrieve` support colbert in a way that it doesn't for pyserini/pinecone? 

Let me know and I'll be happy to dig further!

**Comment by okhat** [comment]
Well! Maybe it already works and we just need to confirm that, and update your notebook and (the pinecone docs later) accordingly.

This format dspy.Retrieve is generic and much nicer than having to hardcode the exact class

**Comment by jasper-xian** [comment]
Those lines are copied from the pyserini notebook, so indeed I'd imagine using pyserini should be more or less the same as colbert. Not sure about pinecone though, I can play around with that if needed

**Comment by okhat** [comment]
Oh nice, my bad, great design on your end making this interoperable cleanly.

I don’t want you to test pinecone if that feels like a tangent for you but could you check it has the same format, so that _in theory_ it should also work

**Comment by jasper-xian** [comment]
From the comments within the pinecone class it gives an example usage:

```python
llm = dspy.OpenAI(model="gpt-3.5-turbo")
retriever_model = PineconeRM(openai.api_key)
dspy.settings.configure(lm=llm, rm=retriever_model)
```

The Pinecone class inherits from dspy.Retrieve and overrides its forward function, but in theory this should work I think

**Comment by jasper-xian** [comment]
Also, happy to help out with the future objective of optimizing retrieval models @okhat! Tuning dense pyserini retrieval sounds like an interesting idea to me

**Comment by okhat** [comment]
Fantastic, that’s more of a research project. I have the initial design (we’d wanted to do this as part of the DSPy paper but it had too much stuff already).

Do you guys both want to take this conversation to zoom/email and we can see how to test it out? We are mainly limited on people who can run experiments right now since we have a few other directions. Lmk if interested.

**Comment by darinkishore** [comment]
@okhat @jasper-xian Definitely interested in working on this as well!

Jjust learned about zoom chat, sent an invite to Omar. Jasper, if you add me or Omar on zoom chat, that should work as well. My email is `dakisho@emory.edu` , which should let you add me on zoom.

Also sent an actual email to @okhat and a wrongly inferred email address for @jasper-xian. Please ignore, my bad.

**Comment by okhat** [comment]
Closing. This is great !
