### ISSUE TITLE
How to change language in case of Synthesizer

### ISSUE THREAD

**Issue by VitalyKrenel** [stanfordnlp/dspy#1525]
Hey folks! 

**Question**
How to get Synthesizer to generate non English output?

**Context**
I was playing around with DSPy Synthesizer experimental module. I recently have been building a product in Armenia where a Russian [cyrilic] is used quite a lot. So I'm trying to figure out, how to adjust the Synthesizer to return me non english.

**Problem description:**
- I can't figure out a way to get non english output in the final `syn_data`

I get results written in Russian during feedback loop and I provide feedback on them in Russian — I still get English synthetic data output most of the time. Among 5-6 run, I only managed to get non english output like 0.5 times [half of the output was still in english]

**What I tried so far:**
I provided a ground_source datasetp with many materials nomenclatures written in Russian:
```python
# original dataset looks like this:
materials = pd.read_csv(io.StringIO('''
"Труба стальная ВГП 15х2,5 ст3 электросварная ГОСТ 8732-78"
"Обогреватель конвекторный электрический Ballu Solo BES/SM-1500 1,5кВт"
Конвектор электрический Ballu Transformer BEC/EVU-1500 1500Вт
"Обогреватель конвекторный электрический Ballu Solo BES/SM-1500 1,5кВт"
"Сетка штукатурная сварная оцинкованная 25х25мм d=0,8мм, рулон 1х25м"
...
'''))

# building examples dataset:
dataset = []

dataframe = materials;

# TODO: Add material_description later
for material_nomenclature in dataframe.values.flatten():
    dataset.append(dspy.Example(material_description=None, material_nomenclature=material_nomenclature).with_inputs('material_description'))
```

Then I use Synth like this:
```python
config = SynthesizerArguments(
    feedback_mode="human",
    num_example_for_feedback=3,
    num_example_for_optim=10
)
synthesizer = Synthesizer(config=config)

syn_data = synthesizer.generate(
    ground_source=dataset[:50],
    num_data=10
)
```

Here's my full colab:
https://colab.research.google.com/drive/1xbvpRKLMcnI91heO2S1EkZ-v0BR1byt5

I couldn't find any API reference on Synthesizer class in the Docs

**Comment by VitalyKrenel** [comment]
Amazing if someone could guide me with an example of Synthetic data generation using DSPy — which is not just a simple "QA" examples. I found quite a lot of those guides — but not many other use-cases.

**Comment by VitalyKrenel** [comment]
@okhat could you help please and guide who I could mention to get some help here? Help would be really appreciated 🙏

I'm just making first experiments with DSPy and really could use some community support here

**Comment by okhat** [comment]
Hey @VitalyKrenel , sorry the Synthesizer is experimental. It's written in DSPy. You could edit the code or adjust if needed. Will close this for now. Feel free to reopen if we can help.
