### ISSUE TITLE
Structured Output Best Practices

### ISSUE THREAD

**Issue by darinkishore** [stanfordnlp/dspy#153]
Hi! One of the DSPy core tenets is to avoid prompt engineering. 

But if you want structured input/output, where is it best to indicate that in a program, aside from the training examples? 

Would it be in 
- Signature classes that specify format?
    - `utterance_mapping = dspy.OutputField(desc="A dictionary mapping speaker to utterance")`
- validation metric for subtask?

We don't always have the luxury of intermediate labels, so if an intermediate task has to have a particular format, it would be nice to have an official best practices recommendation for this case.

**Comment by arnavsinghvi11** [comment]
Hi @darinkishore,

Yes, for enhanced control over structured input and outputs, utilizing the full-form signature notation is recommended, allowing you to include a `prefix` to denote your input/output and a `desc` as a refined description for the corresponding field (as you have illustrated in your example). Usually, brief descriptions suffice, as the aim is to avoid even "signature engineering" where possible and let DSPy do the work with these concise InputFields and OutputFields.

Let me know if that answers your question!

**Comment by okhat** [comment]
Yes, signature desc and metrics, and compiling, are the ways to control this now.

Soon we will have built-in types that will make this smoother.

**Comment by darinkishore** [comment]
@arnavsinghvi11 Definitely answers! Thank you.

I was wondering if you could shed a little more light on the prefix field, though. How does that work?
