### ISSUE TITLE
Migrate from `requests` to `httpx`

### ISSUE THREAD

**Issue by stevapple** [stanfordnlp/dspy#1536]
DSPy has been using both `requests` and `httpx`, which are libraries that serves almost the same purposes. `httpx` is basically a modernized version of `requests` , so it would be better to drop `requests` to shrink the installation size and resource cost.

**Comment by okhat** [comment]
Thanks a lot @stevapple. In the grand scheme of things in DSPy, this seems like a very minor problem :D
