### ISSUE TITLE
Consider migrating from setup.py to pyproject.toml

### ISSUE THREAD

**Issue by amicus-veritatis** [stanfordnlp/dspy#154]
Since the introduction of [PEP 621](https://peps.python.org/pep-0621), using `pyproject.toml` is [the standard way](https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#declaring-project-metadata) for declaring project metadata. There seems to be little, if any, reason to keep using `setup.py` method.

More pragmatically, adopting popular package manager like [poetry](https://python-poetry.org/) would help third-party integration in my opinion.

**Comment by okhat** [comment]
Thanks a lot. I get this multiple times, but I don't quite understand the value proposition here. Is there something I should read on this other then the PEP document

**Comment by amicus-veritatis** [comment]
@okhat 
>I get this multiple times, but I don't quite understand the value proposition here.

Considering `setup.py` is classified as legacy in [official pip document](https://pip.pypa.io/en/stable/reference/build-system/setup-py/), so adopting a recommended standard would be beneficial for a relatively new project.

This also would help interacting with third party libraries as well. You incorporate configurations for various development tools into `pyproject.toml` (black, isort, ruff, mypy, etc.)

For example:
```pyproject.toml
[tool.ruff]
select = [
    "E",  # pycodestyle
    "F",  # pyflakes
    "I",  # isort
    "B",  # black
]

[too.ruff.isort]
known-third-party = ["orjson"]
```

Additionally, it's [useful](https://python-poetry.org/docs/dependency-specification/) for specifying versions for dependencies, especially when combined with package manager like `poetry`. For example:
```pyproject.toml
[tool.poetry.dependencies]
gunicorn = { version = "^20.1", extras = ["gevent"] }
```

>Is there something I should read on this other then the PEP document
- [Official PIP document](https://pip.pypa.io/en/stable/reference/build-system/)
- [Official setuptools document](https://setuptools.pypa.io/en/latest/userguide/quickstart.html#setup-py)

**Comment by okhat** [comment]
Thank you! I'm convinced now. @lawliet19189 this could be something to add with the black refactoring things

**Comment by darinkishore** [comment]
@amicus-veritatis 

Hi! Please let me know if there's anything you'd like to change in the implementation

**Comment by amicus-veritatis** [comment]
@darinkishore lgtm! I'll close this issue as completed.

**Comment by amicus-veritatis** [comment]
I'll close this issue as soon as the PR in #234 is merged.
