### ISSUE TITLE
How to get LangFuse trace_id

### ISSUE THREAD

**Issue by raghavbali** [stanfordnlp/dspy#1540]
Hey dspy team,
I am trying to use langfuse tracer to trace my usage and most importantly capture cost. The place where I am struggling at the moment is getting hold of ``trace_id`` for each request that is generated with LLMs (eg: openai). I am able to get to the whole list of traces using ``TracerObject.langfuse.fetch_traces()`` and then using the ``data`` attribute to get to ``total_cost`` but this requires a whole lot of processing to filter the actual traces I am looking for. 

Is there a cleaner way I can make use of ``fetch_trace_id()`` method without creating a custom tracer? From what I understand the default implementation is not passing any id and expecting LangFuse to generate random trace ids.

PS: _Kudos on the Amazing work in getting this integration in place_

**Comment by okhat** [comment]
Thanks @raghavbali ! Can you tag the langfuse team? You can find who committed the relevant parts.

**Comment by isaacbmiller** [comment]
@karthikscale3

**Comment by karthikscale3** [comment]
I know the names are confusing, but I maintain Langtrace and not Langfuse 😄. But in case, you want to monitor cost, run experiments, visualize eval scores or capture checkpoints, Langtrace has native support for DSPy. You can find more information [here](https://docs.langtrace.ai/supported-integrations/llm-frameworks/dspy#dspy)

**Comment by isaacbmiller** [comment]
Oops sorry about that @karthikscale3 !

**Comment by isaacbmiller** [comment]
@xucailiang

**Comment by xucailiang** [comment]
> @xucailiang

May I know how you use langfuse in dspy? Here are some simple usage instructions. I hope this helps you. [langfuse.md](https://github.com/stanfordnlp/dspy/blob/main/docs/api/language_model_clients/langfuse.md)

**Comment by raghavbali** [comment]
Thanks for the quick response everyone.
@xucailiang : I am following the instructions on the linked README and using the following snippet to get to the most recent traces
```python
# capturing cost and latency
# start and end times are simple time-stamps captured before and after the dspy predict
total_time = end_time-start_time
tracers = langfuse.langfuse.fetch_traces()
total_cost = sum([t.total_cost for t in tracers.data if t.timestamp>=start_time and t.timestamp<end_time])
```

Not a very clean way and hence I wanted to get hold of the trace_id without going through the additional step of creating a customer tracer

**Comment by xucailiang** [comment]
> Thanks for the quick response everyone. @xucailiang : I am following the instructions on the linked README and using the following snippet to get to the most recent traces
> 
> ```python
> # capturing cost and latency
> # start and end times are simple time-stamps captured before and after the dspy predict
> total_time = end_time-start_time
> tracers = langfuse.langfuse.fetch_traces()
> total_cost = sum([t.total_cost for t in tracers.data if t.timestamp>=start_time and t.timestamp<end_time])
> ```
> 
> Not a very clean way and hence I wanted to get hold of the trace_id without going through the additional step of creating a customer tracer

Sorry, I am replying to you just now. So you mean to get the `trace_id `of each reported data in order to track its `total_cost`?

**Comment by raghavbali** [comment]
yes, that's correct

**Comment by xucailiang** [comment]
> yes, that's correct

ok,this is a good suggestion, and for custom trackers this would be a good solution, but for the openai sdk with langfuse this might take some time to get done. I'll look into how to do this soon.
