### ISSUE TITLE
Does DSPy support soft prompt optimization?

### ISSUE THREAD

**Issue by jdkanu** [stanfordnlp/dspy#1560]
Does DSPy support soft prompt optimization?

as in

https://arxiv.org/pdf/2104.08691
https://arxiv.org/pdf/2306.03082

**Comment by okhat** [comment]
If you mean Parameter-Efficient Finetuning Tuning (PEFT) like LoRA or Prefix-Tuning, then that is just a form of finetuning and is supported at least in principle as an implementation of BootstrapFinetune, though control over this is not exposed cleanly in the abstractions of BootstrapFT just yet.

If you mean a different form of soft prompt optimization then the answer is no.
