### ISSUE TITLE
Bootstrapped 0 full traces

### ISSUE THREAD

**Issue by SrikarNamburu** [stanfordnlp/dspy#1566]
I tried to compile a program from the intro.ipynb with custom data with GPT3.5 and custom retriever module. Tried both Single-hop and Multi-hop, but 0 traces were formed. Although when I tried with hotpot q/a dataset with the above mentioned lm and rm modules, few traces were formed. How can I resolve this issue?

```
lm = dspy.AzureOpenAI(api_base='',api_key="" , api_version='', model='gpt35')
rm = custom_rm(index_name='', k=10)
dspy.settings.configure(lm=lm, rm=rm)

class GenerateAnswer(dspy.Signature):
    context = dspy.InputField(desc="may contain relevant facts")
    question = dspy.InputField()
    answer = dspy.OutputField(desc="be descriptive, provide most accurate answer based on context")

class GenerateSearchQuery(dspy.Signature):
    """Write a simple search query that will help answer a complex question."""
    context = dspy.InputField(desc="may contain relevant facts")
    question = dspy.InputField()
    query = dspy.OutputField()


class SingleHopRAG(dspy.Module):
    def __init__(self, num_passages=10):
        super().__init__()

        self.retrieve = dspy.Retrieve(k=num_passages)
        self.generate_answer = dspy.ChainOfThought(GenerateAnswer)
    
    def forward(self, question):
        context = self.retrieve(question).passages
        prediction = self.generate_answer(context=context, question=question)
        return dspy.Prediction(context=context, answer=prediction.answer)

class MultiHopRAG(dspy.Module):
    def __init__(self, passages_per_hop=5, max_hops=3):
        super().__init__()

        self.generate_query = [dspy.ChainOfThought(GenerateSearchQuery) for _ in range(max_hops)]
        self.retrieve = dspy.Retrieve(k=passages_per_hop)
        self.generate_answer = dspy.ChainOfThought(GenerateAnswer)
        self.max_hops = max_hops
    
    def forward(self, question):
        context = []

        for hop in range(self.max_hops):
            query = self.generate_query[hop](context=context, question=question).query
            passages = self.retrieve(query).passages
            context = deduplicate(context + passages)

        pred = self.generate_answer(context=context, question=question)
        return dspy.Prediction(context=context, answer=pred.answer)


#Single Hop RAG(Basic RAG) with Fewshot
from dspy.teleprompt import BootstrapFewShot

# Validation logic: check that the predicted answer is correct.
# Also check that the retrieved context does actually contain that answer.
def validate_context_and_answer(example, pred, trace=None):
    answer_EM = dspy.evaluate.answer_exact_match(example, pred)
    answer_PM = dspy.evaluate.answer_passage_match(example, pred)
    return answer_EM and answer_PM

# Set up a basic teleprompter, which will compile our RAG program.
teleprompter = BootstrapFewShot(metric=validate_context_and_answer)

# Compile!
compiled_rag = teleprompter.compile(SingleHopRAG(), trainset=trainset)


def validate_context_and_answer_and_hops(example, pred, trace=None):
    if not dspy.evaluate.answer_exact_match(example, pred): return False
    if not dspy.evaluate.answer_passage_match(example, pred): return False

    hops = [example.question] + [outputs.query for *_, outputs in trace if 'query' in outputs]

    if max([len(h) for h in hops]) > 100: return False
    if any(dspy.evaluate.answer_exact_match_str(hops[idx], hops[:idx], frac=0.8) for idx in range(2, len(hops))): return False

    return True

#Multi hop RAG with Few shot

teleprompter = BootstrapFewShot(metric=validate_context_and_answer_and_hops)
compiled_baleen = teleprompter.compile(MultiHopRAG(), teacher=MultiHopRAG(passages_per_hop=2), trainset=trainset)

```

I get this for both SingleHopRAG and MultiHopRAG - `Bootstrapped 0 full traces after 25 examples in round 0.` 

Is it because of the smaller trainset? It formed few traces when I tried with a similar size using hotpot q/a dataset.
Moreover, when I try the prediction using MultiHopRAG on devset, the responses are slightly better than usual eventhough 0 traces were formed. 

What could be the issue? And how can I resolve it?

Any help would be greatly appreciated!

**Comment by okhat** [comment]
I'm going to guess that your metric is too strict for your data. Is answer_exact_match appropriate for your usecase? Or do you need an LM judge?

**Comment by SrikarNamburu** [comment]
Thank you for the quick response, I did try out a custom metric based of cosine similarity, it didn't work out, I will try the LM Judge and see.

**Comment by SrikarNamburu** [comment]
Replace the metric with factuality_metric as shown below, no traces were formed. Can it be due to small dataset?

```
class FactJudge(dspy.Signature):
    """Judge if the answer is factually correct based on the context."""

    context = dspy.InputField(desc="Context for the prediciton")
    question = dspy.InputField(desc="Question to be answered")
    answer = dspy.InputField(desc="Answer for the question")
    factually_correct = dspy.OutputField(desc="Is the answer factually correct based on the context?", prefix="Factual[Yes/No]:")

judge = dspy.ChainOfThought(FactJudge)

def factuality_metric(example, pred, trace=None):
    factual = judge(context=example.answer, question=example.answer, answer=pred.answer)
    return bool(factual=="Yes")
```

I also did two experiments, instead of `question` and `answer`(actual answer) as dataset, I first replaced the `answer` column with responses from my retriever module. Secondly, I replaced the `answer` column with response from compiled RAG, in both the cases no traces were formed. I assumed traces will be formed in these experiments.

What am I missing?

**Comment by SrikarNamburu** [comment]
Hi @okhat,

Following up on the issue above Any feedback or insights would be really helpful.

Thanks!

**Comment by okhat** [comment]
Hey @SrikarNamburu ! Can you migrate to 2.5 by switching to dspy.LM? This will allow you to request a bool directly in your metric, which will fix the problem you have most likely.

Migration doc: https://github.com/stanfordnlp/dspy/blob/main/examples/migration.ipynb

new metric:

```python
judge = dspy.ChainOfThought("context, question, system_response -> faithfulness: bool")
```

**Comment by SrikarNamburu** [comment]
Hi @okhat,

Thanks for the suggestion. Let me try this, will get back.

**Comment by okhat** [comment]
Looking forward!

**Comment by SrikarNamburu** [comment]
Hey @okhat,

I haven't upgraded the version yet, but noticed that the problem was in the `factuality_metric`, after changing `factual=="Yes"` to `factual.factually_correct=="Yes"` ,traces are being formed now. 

I think this documentation here needs to be updated as well - https://dspy-docs.vercel.app/docs/cheatsheet#llm-as-judge.

I have couple more questions:
- When using the saved MultiHopRAG program(.json), the inference time went from 3sec to 60+sec(used gpt4om, context window maxed out for gpt35t), I expected a slight bump, but 60sec seems significant. Anything to help with improve the inference time?
- How to decide the value for `max_bootstrapped_demos` parameter when using `BootstrapFewShot`? 

Thank you for all the feedback and great work on DSPy!
