### ISSUE TITLE
Empty context causes 4o models to return "N/A" 

### ISSUE THREAD

**Issue by excubo-jg** [stanfordnlp/dspy#1603]
if dspy.Prediction is called with context = [] this causes in chat_adapter.py
```
def format_fields(fields):
    output = []
    for k, v in fields.items():
        v = _format_field_value(v)
        output.append(f"[[ ## {k} ## ]]\n{v}")
```
and 
`def format_list(items):
    if len(items) == 0: return "N/A"`

that content in format_turn()
`
content.append(format_fields({k: values.get(k, "Not supplied for this particular example.") for k in field_names}))
`
is set to
['[[ ## context ## ]]\nN/A\n\n[[ ## question ##]]\nMy prompt']

This context makes OpenAI 4o (but not 4 or older versions) reply "N/A" to all prompts. I think the line returning "N/A" should be changed to return "" - could do a pr if this is confirmed.

**Comment by okhat** [comment]
Can you share an example of this happening?

**Comment by okhat** [comment]
For example, I just tried this with GPT-4o:

```python
dspy.Predict('context, question -> answer')(context=[], question='What is the capital of France?')
```

The answer I get is "The capital of France is Paris."

**Comment by excubo-jg** [comment]
This is getting a bit weird... Using your question I get "Paris" as answer.
Some other examples:
"What are the first steps to connect to SAP?" -> "Install SAP GUI"
"What are the first steps to connect to SAP ARIBA?" -> "N/A"
I was using non-sensical prompts like "sdvsvders?" during testing of my other code which return "N/A" with 4o. With 4 I get "Could you please clarify your question?"

**Comment by okhat** [comment]
I'm not seeing any issues in behavior.

## Example 1:

```python
dspy.Predict('context, question -> answer')(context=[], question='sdvsvders?')
dspy.inspect_history()
```

Produces:
```
Prediction(
    answer="I'm sorry, but it seems like your question is incomplete or unclear. Could you please provide more context or clarify your question?"
)
```


## Example 2:

**Comment by excubo-jg** [comment]
Not sure what is going on - there must be side effects in my processing. Many thanks for your kind support.
