### ISSUE TITLE
Teacher and student in telepromters

### ISSUE THREAD

**Issue by stepahane** [stanfordnlp/dspy#163]
Is it possible to have more precisions about teacher and student in telepromters ? It's not so clear to me how it works.
Also is it possible to have more clarifications about the different telepromters : BootstrapFewShotWithRandomSearch, BootstrapFewShot, Ensemble, BootstrapFinetune
Thx by advance.

**Comment by arnavsinghvi11** [comment]
Hi @stepahane , 

Does the teleprompters [documentation](https://github.com/stanfordnlp/dspy/blob/main/docs/teleprompters.md) help provide more clarity? 
Please let me know if you have any additional questions!
