### ISSUE TITLE
Context length exceeded when using VLMs

### ISSUE THREAD

**Issue by dprokhorov17** [stanfordnlp/dspy#1659]
How does this lib is supposed to work with images correctly?

My current script is:

```python
import dspy
from constants import DESCRIPTION_PROMPT
import base64
from PIL import Image

lm = dspy.LM('openai/gpt-4o')
dspy.configure(lm=lm)

class RecognizeImage(dspy.Signature):
    f"""{DESCRIPTION_PROMPT}"""

    img_base64 = dspy.InputField(
        desc="Base64 data of the image",
        is_image=True,
    )
    description = dspy.OutputField(desc="description")
    
image_path = "labeled_data/2024-09-09_10_21_24_924.png"

# load with image and resize to 1280x720 pixels by keeping the aspect ratio
img = Image.open(image_path).convert("RGB")
img.thumbnail((1280, 720))

# convert to base64
img_base64 = base64.b64encode(img.tobytes()).decode()

predict = dspy.Predict(RecognizeImage)
predict(img_base64=img_base64)
```

I get the following error:

`ContextWindowExceededError: litellm.BadRequestError: litellm.ContextWindowExceededError: ContextWindowExceededError: OpenAIException - Error code: 400 - {'error': {'message': "Invalid 'messages[1].content': string too long. Expected a string with maximum length 1048576, but got a string with length 3686558 instead.", 'type': 'invalid_request_error', 'param': 'messages[1].content', 'code': 'string_above_max_length'}}`

However, I do not get the same error when I use the normal openai package.

**Comment by okhat** [comment]
Hey @dprokhorov17 , images are not yet supported in main, but they're WIP here: #1656

cc @isaacbmiller

**Comment by dprokhorov17** [comment]
@okhat @isaacbmiller Any specific thoughts on prompt optimization for VLMs in general? For instance, does few-shot prompting a VLM (e.g., Pixtral12B) make sense? Or would it only impact the text-based part of the VLM?

**Comment by okhat** [comment]
@dprokhorov17 The short answer is that we don't know definitively yet! I'd certainly like it to be true that VLMs benefit from the same prompt optimization strategies as LLMs.

**Comment by pavan4** [comment]
Looks like the linked WIP PR is incorrect and the right one is this? - https://github.com/stanfordnlp/dspy/pull/1495

**Comment by pavan4** [comment]
I tried it out and works great! Is this supporting only OAI or can I use Google gemini as `lm` etc., ?

**Comment by isaacbmiller** [comment]
Gemini should work for inline files or passing in https URLs.

Things like using the google files api or passing in gs:// addresses aren't supported yet. (If this is blocking for a use case ping me!)
