### ISSUE TITLE
Error: CODE 404 - {"error":"model not found, try pulling it first"} After model is running

### ISSUE THREAD

**Issue by cbrousseauAumni** [stanfordnlp/dspy#1661]
I have already started the ollama server and the mistral model, as evidenced by the logs. If I just run a command directed at mistral or attempt to curl, everything works great, but DSPy can't find mistral for some reason, even though it's connecting to the right port. Then on top of that, there's a .join problem with the actual content despite everything being strings. Something very strange is happening.

`$ps aux | grep ollama | grep -v grep
`gives 
` 7 root      0:07 {ollama} /run/rosetta/rosetta /usr/bin/ollama ollama serve`
`8 root      0:00 {ollama} /run/rosetta/rosetta /usr/bin/ollama ollama run mistral`
But when I try to invoke the DSPy program, with just a string input I get:
`Error: CODE 404 - {"error":"model \"mistral\" not found, try pulling it first"}`
and
`TypeError: can only join an iterable`

**Comment by okhat** [comment]
Hey @cbrousseauAumni ! I'd love to help here but there's not enough information.

**Comment by cbrousseauAumni** [comment]
I appreciate it. Here's all of the relevant info I'm aware of, if there's something specific we're looking for, let me know and I can get it.
### Signature and module:
```
class Basic(dspy.Signature):
    "string prompt"

    context = dspy.InputField(desc="description")
    text = dspy.InputField(desc="description")
    answer = dspy.OutputField(
        desc="description"
)
class Text2Val(dspy.Module):
    def __init__(self):
        super().__init__()

        self.generate_answer = dspy.ChainOfThought(Basic)

    def forward(self, context, text):
        prediction = self.generate_answer(context=context, text=text)
        return dspy.Prediction(answer=prediction.answer)
```
        

### Loading the DSPy Module:
```
base_url = "http://localhost:11434"
llm = dspy.AumniOllamaLocal(model="mistral", base_url=base_url)
dspy.settings.configure(lm=llm)
ensemble = list()
for idx in range(6):
    program = Text2Val()
  
    program.load(f"bootstrap-finetune-{idx}.json")
    ensemble.append(program)
  
expert_program = ensemble[0]
```

### Invoking the model

```
context = "some context"
text= "some text"
result = expert_program(context=context, text=text)
```

**Comment by cbrousseauAumni** [comment]
Running curl I get 200 and valid responses from mistral, running DSPy I get the errors I mentioned in the first comment.

**Comment by arnavsinghvi11** [comment]
Could you try `llm = dspy.LM(model="ollama/mistral", base_url=base_url)` and see if this resolves the error? ([relevant LiteLLM docs](https://docs.litellm.ai/docs/providers/ollama))

This is through the DSPy 2.5 migrated client (I suspect your custom LM AumniOllamaLocal may be causing the error)

**Comment by cbrousseauAumni** [comment]
Lol, AumniOllamaLocal is just adding print statements to the basic_request method for more visibility into where things were happening.

**Comment by cbrousseauAumni** [comment]
`AttributeError: 'LM' object has no attribute 'base_url'`

**Comment by arnavsinghvi11** [comment]
ah my bad, that should be `api_base= base_url`

**Comment by cbrousseauAumni** [comment]
Are you sure this is correct?
`AttributeError: 'LM' object has no attribute 'api_base'`
`llm = dspy.LM(model="ollama/mistral", api_base=base_url)`

**Comment by cbrousseauAumni** [comment]
Also this: `ValueError: The saved state is from a version of DSPy prior to v2.5.3. Please use `use_legacy_loading=True` to load the state.`

**Comment by cbrousseauAumni** [comment]
Thank you so much, seems like it ran, is there anything I should be aware of as I'm digging into this to make sure everything's ok @arnavsinghvi11 ?

**Comment by cbrousseauAumni** [comment]
> hmm regarding api_base, this is supported in [dspy.LM](https://github.com/stanfordnlp/dspy/blob/313aa669c6ad9280be624aa5d25415391ee32539/dspy/clients/lm.py#L177). can you share what version of DSPy you're on? the config should look like this (as it works on my end)
> 
> ```
> llm = dspy.LM(model="ollama/mistral", api_base="http://localhost:{...}")
> dspy.configure(lm=llm)
> ```
> 
> Which line in your code does the ValueError come from? potentially different suggestions depending on that

It came from this line: `program.load(f"bootstrap-finetune-{idx}.json")`
I will likely need to retrain on the most recent version of dspy to get rid of that.

**Comment by cbrousseauAumni** [comment]
Thank you!

**Comment by cbrousseauAumni** [comment]
I closed it too soon, I forgot about the base error
`litellm.exceptions.APIConnectionError: litellm.APIConnectionError: OllamaException - {"error":"model \"mistral\" not found, try pulling it first"}`

**Comment by cbrousseauAumni** [comment]
I think we have solved the dspy part of this issue, and have moved on to the ollama side, I will submit an issue on their github. Thank you for your help!
