### ISSUE TITLE
How to use multiple different LLMs?

### ISSUE THREAD

**Issue by abuonomo** [stanfordnlp/dspy#168]
The tutorial notebook says following:

>In the last line above, we configure DSPy to use the turbo LM and the ColBERTv2 retriever (over Wikipedia 2017 abstracts) by default. **This will be easy to overwrite for local parts of our programs if needed.**

(bold added by me)

Could you clarify how and where this overwriting would occur? I would like to use different language models for different pieces of my process.

**Comment by abuonomo** [comment]
Here is a method using a context manager that seems to work:
```
@contextmanager
def override_dspy_lm(lm):
    # Store original lm
    original_lm = dspy.settings.lm

    # Override the lm setting
    dspy.settings.lm = lm

    yield  # This is where the overridden setting will be active

    # Restore the original lm setting
    dspy.settings.lm = original_lm
    
with override_dspy_lm(alternate_llm):
    pass # do something here
```

**Comment by okhat** [comment]
There’s a thread safe and more powerful builtin

with dspy.settings.context(lm=…):

**Comment by abuonomo** [comment]
Ah, I didn't realize that was a context manager. I suppose that should have been obvious. Thank you!

**Comment by pe64** [comment]
The method you mentioned, which uses a context manager to temporarily override dspy.settings.lm, may cause issues in a multithreading environment. This is because dspy.settings.lm is a global variable, and multiple threads modifying it simultaneously can lead to race conditions, resulting in unpredictable behavior.
