### ISSUE TITLE
ValueError: Expected dict_keys(['output']) but got dict_keys([])

### ISSUE THREAD

**Issue by Haknt** [stanfordnlp/dspy#1691]
I am using TypedPredictor as the predictor and vertex_ai/gemini-pro as the LLM, as shown below:

```python
dspy.LM('vertex_ai/gemini-pro',
                     vertex_credentials=vertex_credentials_json,
                     vertex_project=GoogleConfigs.PROJECT_ID,
                     vertex_location=GoogleConfigs.LOCATION)
predictor =  dspy.TypedPredictor(SomeSignature)
predictor(input=input)
``` 

The following error is returned in ChatAdapter:

`ValueError: Expected dict_keys(['output']) but got dict_keys([])` in VertexAI with LiteLLM

The problem is that the LLM does not return in the `[[## example ##]]` format. Instead, it returns in the `## output ##` format.

**Comment by sushmanthreddy** [comment]
@Haknt I think have checked the code of litellm ,I also have the same problem few days back

1.Lm Client code :
```python
# Returns responses like this:
outputs = [c.message.content if hasattr(c, "message") else c["text"] for c in response["choices"]]
```

2. Vertex AI/Gemini-pro model:
```python
# Returns in this format:
## output ## here's the answer
```

3. DSPy's TypedPredictor:
```python
# Expects responses in this format:
[[## output ##]] here's the answer
```

The Problem Chain:
- LM client gets response from Vertex AI
- Vertex AI gives: `## output ##`
- TypedPredictor looks for: `[[## output ##]]`
- Can't find it → creates empty dictionary
- Crashes with: `ValueError: Expected dict_keys(['output']) but got dict_keys([])`

It's like three people speaking slightly different languages:
- Vertex AI speaks: "Hello"
- LM passes it as: "Hello"
- But TypedPredictor only understands: "[[Hello]]"


I have followed the below solution  actually ,when I have encountered the same problem

Solution  - Modify the prompt to make Gemini use DSPy's format:
```python
dspy.LM('vertex_ai/gemini-pro',
        instructions="Always format your responses using [[## output ##]] markers",
        vertex_credentials=vertex_credentials_json,
        vertex_project=GoogleConfigs.PROJECT_ID,
        vertex_location=GoogleConfigs.LOCATION)
```

**Comment by okhat** [comment]
Hey @Haknt , can you (i) upgrade to latest 2.5.18 and (ii) just swap out dspy.TypedPredictor with dspy.Predict or dspy.ChainOfThought?

I bet it'll work :D Closing here.

**Comment by Haknt** [comment]
Hey @okhat,
I **upgraded** to the latest version (2.5.18), but unfortunately, it **didn't solve** the issue. Then, I tried **replacing** `TypedPredictor` with `dspy.Predict`—and voila, it **works**! (As you mentioned, using both steps was key!)
