### ISSUE TITLE
Question: When creating a DSPy model with multiple outputs, does DSPy call the LLM API once per output?

### ISSUE THREAD

**Issue by rhiever** [stanfordnlp/dspy#1692]
For example, if I set up a model with a CoT reasoning output and then a final text output, will it call the LLM API twice?

**Comment by okhat** [comment]
Only one call if possible, overall in total, for every dspy.Predict call. But retries may happen if strictly necessary.

**Comment by okhat** [comment]
Use dspy.inspect_history(n=5) to view the last 5 prompts sent by DSPy and the outputs too!

**Comment by rhiever** [comment]
Brilliant, thank you @okhat.
