### ISSUE TITLE
Model history's prompt is "None" after BootstrapFewShot optimization

### ISSUE THREAD

**Issue by belmarca** [stanfordnlp/dspy#1737]
Hi,

I am running a `BootstrapFewShot` optimizer on a simple `model` as follows:

```py
        dspy.settings.configure(lm=student_model)

# ...

        config = dict(
            max_bootstrapped_demos=len(examples),
            max_labeled_demos=len(examples),
            teacher_settings=dict(lm=teacher_model),
        )
        optimizer = BootstrapFewShot(metric=metric, **config)

# ...

        run = optimizer.compile(module(), trainset=examples)
```

I want to get the optimized prompt out of the `student_model` but its history is empty. When accessing the `teacher_model`'s history, its `"prompt"` key is `None`. I am using the new `LM` class.

This works fine with the old `OpenAI` class.

**Comment by okhat** [comment]
>  want to get the optimized prompt out of the student_model but its history is empty

BootstrapFewShot never uses the student_model if you have a teacher_model. I think you might be interested in a better optimizer like MIPROv2 or random search.

Call the optimized program and use dspy.inspect_history().
