### ISSUE TITLE
Type annotations with ChainOfThought are not included in prompt or enforced

### ISSUE THREAD

**Issue by neil-sola** [stanfordnlp/dspy#1743]
Previously with `TypedChainOfThought`, I used a signature with pydantic type annotations - even though `TypedChainOfThought` is now deprecated, it doesn't include the schema in the prompt if I use the recommended `ChainOfThought` in the same way. Is there updated reference on how to achieve this?

**Comment by okhat** [comment]
Hey @neil-sola , could you include an example of what you're saying? Make sure to check with `pip install -U dspy`.

Type annotations are, to my knowledge, included and enforced in ChainOfThought, if you're on a recent version of DSPy.

**Comment by neil-sola** [comment]
Sorry, after debugging looks like it's an issue on our end - all good here!
