### ISSUE TITLE
AttributeError: 'Prediction' object has no attribute 'rationale'

### ISSUE THREAD

**Issue by priamai** [stanfordnlp/dspy#1746]
Hi there,
I am following the tutorial:

https://dspy-docs.vercel.app/building-blocks/2-signatures

but I get this error:

AttributeError: 'Prediction' object has no attribute 'rationale'

from:
```

# Example from the XSum dataset.
document = """The 21-year-old made seven appearances for the Hammers and netted his only goal for them in a Europa League qualification round match against Andorran side FC Lustrains last season. Lee had two loan spells in League One last term, with Blackpool and then Colchester United. He scored twice for the U's but was unable to save them from relegation. The length of Lee's contract with the promoted Tykes has not been revealed. Find all the latest football transfers on our dedicated page."""

summarize = dspy.ChainOfThought('document -> summary')
response = summarize(document=document)

print(response.summary)
print("Rationale:", response.rationale)
```
Maybe something has changed from the docs.
Cheers.

**Comment by priamai** [comment]
I believe the documents are wrong and it should be:
`
print(response.reasoning)`

which works.

**Comment by arnavsinghvi11** [comment]
Hi @priamai , yes `response.reasoning` is the right way to access this going forward in dspy v2.5+ and `dspy.LM`. (`rationale` was an older field which is compatible with `dspy.OpenAI` which will be deprecated going forward)

will update the docs shortly to reflect this new default behavior!
