### ISSUE TITLE
How to make my own template in DSPy?

### ISSUE THREAD

**Issue by Chanwhistle** [stanfordnlp/dspy#178]
Hi, 

I'm using DSPy with korean LM(this is in hugging face) and Retrieval.
But I'm having some problems in using it.
How can I rewrite template in Korean?

As I know there was Type and Template method in DSP but I couldn't find it in DSPy.

**Comment by detaos** [comment]
On the surface, you can control most of the template by how you define your class:

For example, here's an "answer bot" that responds in Korean:

```
class AnswerInKorean(dspy.Signature):
    """Respond to the question in Korean"""
    
    question = dspy.InputField(
        prefix = "Question:",
        desc = "A question in English",
    )
    answer = dspy.OutputField(
        prefix="Answer:",
        desc="${the answer to the question, but only speak in Korean}"
    )

class AnswerBot(dspy.Module):
    def __init__(self, tools=None):
        super().__init__()

        self.generate_answer = dspy.ChainOfThought(AnswerInKorean)
        
    def forward(self, question):
        prediction = self.generate_answer(question=f"{question}")
        return dspy.Prediction(answer=prediction.answer)

uncompiled_answer_bot = AnswerBot()
pred = uncompiled_answer_bot(question="What's the weahter like over there?")
print(pred.answer)
```

> 저기 날씨가 어때요.

You can see the prompt by doing this:
```
lm.inspect_history(n=1)
```
```
Respond to the question in Korean

---

Strictly adhere to the following format:

Question: A question in English
Reasoning: Let's think step by step in order to ${produce the answer}. We ...
Answer: ${the answer to the question, but only speak in Korean}

---

Question: What's the weather like over there?
Reasoning: Let's think step by step in order to 저기 날씨가 어때요? We need to translate the question into Korean, so we can ask it to someone who speaks Korean. To do this, we need to know the Korean words for "what's the weather like" and "over there". In Korean, "what's the weather like" is "날씨가 어때요" and "over there" can be translated as "저기". So, we put these two phrases together to get "저기 날씨가 어때요".
Answer: 저기 날씨가 어때요.
```

You can see I also changed the usual "Follow the following format" to "Strictly adhere to the following format".  That was done by editing `dsp/templates/template_v2.py`.

To modify the Chain of Thought prefix, you can make your own type and pass it to the CoT constructor.  In `AnswerBot`'s `__init__`:

```
    cot_type = dsp.Type(
        prefix="Reasoning: Let's think step by step in order to",
        desc="${produce the answer}. We ..."
    )
    self.generate_answer = dspy.ChainOfThought(AnswerInKorean, rationale_type=cot_type)
```
(Be sure to `import dsp` if you want to make your own type.)

**Comment by Chanwhistle** [comment]
Thank you for your kind response.
But this still doesn't work with my LM.
[(https://github.com/42dot/42dot_LLM)] this is LLM that I use. When I see this model's inference code, I think I should change some code in DSPy. I'll try to handle it.

And also, you used only Type method, not Template method, If I want to use Template method, how should I change those code?
I'm really thankful for your help.

**Comment by okhat** [comment]
@Chanwhistle Let me know if you're able to find the parts you need to change.

In general, supporting non-English inputs/outputs (with general LLMs like GPT-3.5 or Llama2) is important to us. But supporting non-English LLMs (like 42dot_LLM) is outside the current scope.
