### ISSUE TITLE
Neo4jRM

### ISSUE THREAD

**Issue by a136214808** [stanfordnlp/dspy#1788]
Does Neo4jRM only support OPENAI_API_KEY? If not, how do I use my local Embedding model or any other ways to execute the code? Thanks.

**Comment by okhat** [comment]
Perhaps just use neo4j without the RM in DSPy. Just call the library and call DSPy. It'll work!

**Comment by a136214808** [comment]
> Perhaps just use neo4j without the RM in DSPy. Just call the library and call DSPy. It'll work!

Could you please give an example of it, I am a little bit confused about it. Thanks!

**Comment by okhat** [comment]
You can set up your retriever without importing it from DSPy. Then call the retriever when you have a search query.
