### ISSUE TITLE
Is dspy.OllamaLocal here to stay?

### ISSUE THREAD

**Issue by NumberChiffre** [stanfordnlp/dspy#1811]
Hey guys,

I've missed out the latest updates over the past 1-2 months. I remember update from v2.5 that we will remove `dspy.OllamaLocal` and all else to be replaced by `dspy.LM` which uses `litellm` under the hood.

For those of us using local models, it seems we still need `dspy.OllamaLocal` since the newest `llama` and `qwen` models are not supported from `litellm`: https://docs.litellm.ai/docs/providers/ollama#ollama-models

Even for the local models that are supported, the structured format fails frequently with `dspy.LM`, while `dspy.OllamaLocal` works for most cases.

Could you share any forward guidance for those of us relying on local models for your roadmap?

**Comment by okhat** [comment]
Hey @NumberChiffre ! LiteLLM supports any Ollama model. I use Llama 3.2 on Ollama. 

What are you seeing in terms of failure cases?

**Comment by okhat** [comment]
@NumberChiffre Maybe you passed `ollama/` instead of `ollama_chat/` to LM?

**Comment by NumberChiffre** [comment]
@okhat Thanks for the suggestion, actually it worked with `ollama` as provider for `llama3.2`, the problem is it fails with structured output which refers to [this issue](https://github.com/stanfordnlp/dspy/issues/1539)

**Comment by okhat** [comment]
@NumberChiffre Please try ollama_chat. I think litellm makes a big distinction between the two. I doubt it'll fail often with structured outputs, but let me know if it does and if you have an example!

**Comment by NumberChiffre** [comment]
@okhat Yeah it doesn't fail frequently, I haven't run enough tests yet. Could there be any permanent fix to this issue: https://github.com/stanfordnlp/dspy/issues/1539

**Comment by okhat** [comment]
If you have a self-contained failure, like inputs + signature -> fail, we'd love to take a look. Especially with ollama_chat/* since ollama/* is probably just not processing the inputs correctly based on a few anecdotes from other users.
