### ISSUE TITLE
Using Different LMs in Complilation

### ISSUE THREAD

**Issue by kxzxvbk** [stanfordnlp/dspy#1816]
Hi, I'm using dspy to better prompt llama3.1.
However, I find that llama3 itself does not perform well in proposing new instructions, as this task is quite challenging.
I'm wondering whether there is an elegant way to use different LLMs when compilation (e.g. use gpt to propose new prompts)
Thanks :)

**Comment by okhat** [comment]
Hey @kxzxvbk ! Yes definitely. Are you using MIPROv2?

```python
optimization_model_kwargs = dict(prompt_model=gpt4o, task_model=llama, teacher_settings=dict(lm=gpt4o))
tp = dspy.MIPROv2(metric=YOUR_METRIC, auto="medium", num_threads=8, **optimization_model_kwargs)
optimized_react = tp.compile(YOUR_PROGRAM, trainset=trainset)
```

**Comment by kxzxvbk** [comment]
@okhat That's great, thank you! Maybe this can be added to relevant docs.
