### ISSUE TITLE
How to change order of input and prompt/instruction for prompt caching

### ISSUE THREAD

**Issue by anhnami** [stanfordnlp/dspy#1835]
Hi,

I would like to use dspy for extensive Q/A and information extraction on very long input texts. Since dspy builds the prompt based on the Signature and appends input fields, the resulting prompt will change for every question. I want to ask whether we can instruct dspy to place the instruction after the input. This way, we can reuse the KV cache in a self-hosted LLM or save money with OpenAI's prompt caching.

Thanks.

**Comment by okhat** [comment]
Hey @anhnami ! Just create an input field _after_ the context and pass any information you need to it.

`dspy.Predict('context, task -> response')(context=LONG, task="Please do ....")`

**Comment by anhnami** [comment]
Thank you and sorry for the late reply. Your suggestion makes sense and will work for simple cases. However, in my information extraction use cases, which is pretty common, I want to enforced types for different responses, I also want DSPY to optimize the prompt/task for each response. As far as I can see from the OpenAI LM's history, DSPy will build the LM's call with 2 messages:

0. 'system' message that includes input and output fields, types, formatting, and instruction
1. 'user' message that include user's input

My hypothesis is that since for different response, 'system' message will vary of course and thus the common prefix amongst DSP modules on the same input will be minimal (a few words). If we can swap the order between 'user' and 'system' message then the common prefix will be much longer and for local LLM we can reuse the KV cache.

**Comment by okhat** [comment]
I see. The easiest approach (it's 3-4 lines) is to build an adapter that inherits from ChatAdapter and just switches the order of messages:

```python
class SwappedChatAdapter(dspy.adapters.ChatAdapter):
  def format(...):
     ... # call super()'s format and replace the role

dspy.configure(adapter=SwappedChatAdapter)
```

**Comment by anhnami** [comment]
Thank you very much. That's exactly what I'm looking for.
