### ISSUE TITLE
lm.api_base

### ISSUE THREAD

**Issue by mike2463** [stanfordnlp/dspy#1841]
Here is the code snippet where I am setting up the LM:
lm = dspy.LM(
    model="ollama_chat/llama3.2",
    api_base='http://localhost:11434',  # Your local server
    api_key="",  # Placeholder API key for local use
)
dspy.configure(lm=lm)

I keep getting and AtrributeError saying LM object has no attribute api_base. I have the latest version of dspy 2.5.33.

**Comment by mike2463** [comment]
Traceback (most recent call last):
  File "/Users/michaelschell/Desktop/cobol-app/dspy_rag/main.py", line 5, in <module>
    from retriever import QueryApp  # QueryApp now handles query processing
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelschell/Desktop/cobol-app/dspy_rag/retriever.py", line 27, in <module>
    logger.debug(f"Configured model: {lm.model}, API base: {lm.api_base}")
                                                            ^^^^^^^^^^^
AttributeError: 'LM' object has no attribute 'api_base'

**Comment by okhat** [comment]
Ah I see. The issue is that you're trying to access lm.api_base in your code, in the file `dspy_rag/retriever.py`.

There's no such thing as `lm.api_base`. It's not saved in the object.

**Comment by mike2463** [comment]
Oh, now I feel dumb! Thank You for the help!!

**Comment by okhat** [comment]
No worries :D Do let me know if you face any issues down the line!
