### ISSUE TITLE
Are Assertions and Suggests still a thing?

### ISSUE THREAD

**Issue by dzimmerman-nci** [stanfordnlp/dspy#1842]
I see they aren't linked to in the  "Learn DSPy" documentation any longer. Is there functionality replaced by something else?

**Comment by okhat** [comment]
They exist, but we see that too many users apply them for things that are best addressed with signatures & types. We're adding them back with a more "advanced" label and a clearer explanation of when they're appropriate. 

What have you considered assertions for?

**Comment by dzimmerman-nci** [comment]
I was originally using them to both force a list type for the output field and to ensure that each item in the list is in a list of valid options for multi-label classification. Here is something similar to my valid options assert function:
```
def assert_func(answer_list):
    for answer in answer_list:
        if answer not in ['option1', 'option2', 'option3', 'option4']:
            return False
    return True
```
 I see now that I can set the list type in the Signature using: `answer: list = dspy.OutputField`
 I also see that I can set a Literal type in the Signature using: `answer: Literal['option1', 'option2', 'option3', 'option4']`

Is there a way to combine the two to set the output field as a list comprising of the valid options for multi-label classification?
What is the preferred approach here? Is there a way to do it without Assertions and if so, does adding an Assertion against this in my Module add any benefit in addition to explicitly stating the type in the Signature?

**Comment by okhat** [comment]
Yes you can do `answers: list[Literal[...]]` in a dspy.Signature subclass!

**Comment by dzimmerman-nci** [comment]
Thanks! Is this the preferred method a multi-label classification output? Or will an Assertion add any value in my Module after using this signature?

**Comment by okhat** [comment]
Assertions wouldn't add value in this case. Which is why we're reworking their docs. (Advanced type support came to DSPy after assertions, not before.)

**Comment by dzimmerman-nci** [comment]
Great, thank you for your support @okhat ! This way seems much cleaner
