### ISSUE TITLE
Disabling cache not working

### ISSUE THREAD

**Issue by lestan** [stanfordnlp/dspy#1857]
Tried to set the cache flag to False as per documentation to force requests to not use cache.  Not getting the results I expect - i.e. getting the same results each time.

Documentation on the [Migration guide](https://github.com/stanfordnlp/dspy/blob/main/examples/migration.ipynb):

`gpt_4o_mini = dspy.LM('openai/gpt-4o-mini', temperature=0.9, max_tokens=3000, stop=None, cache=False)`

My code uses Ollama:
`lm = dspy.LM("ollama_chat/granite3-moe:1b", provider="ollama", api_base="http://localhost:11434/", cache=False, launch_kwargs={'seed', 42})
dspy.configure(lm=llm)`

When I call it to generate a random name, I get the same results from run to run with the following code:

`llm("generate a random human person name. no descriptions. no famous people. not fantasy or science fiction based.")`

Am I missing something in the configuration?  

Appreciate any help!

Les

**Comment by okhat** [comment]
Try changing the temperature? The default temperature is 0.0, your `gpt_4o_mini` snippet changes the temperature to 0.9, but your ollama example doesn't.

**Comment by okhat** [comment]
Closing as I confirmed this works OK with gpt-4o-mini, but please do let us know if adjusting the temperature doesn't fix your issue!

**Comment by lestan** [comment]
Thanks for the suggestion. Setting the temperature didn't work. With cache flag set to False and a temperature set to some numeric value, it continues to generate the same output for a given prompt over multiple inference requests. 

Any other thoughts?
