### ISSUE TITLE
How to constrain the number of few shot examples ?

### ISSUE THREAD

**Issue by thangld201** [stanfordnlp/dspy#1859]
Hi @stanfordnlp, thank you very much for your works!

I am using the MIPROv2 teleprompter to jointly optimize both instruction and few shot sets. In my use case, I need to compare MIPROv2 with other prompting methods. For fair comparison, we set an equal budget for each method (max 3 exemplars). As far as I understand, setting the parameter `max_labeled_demos` would equal to the size of the exemplar set. However, when I tried running, the final demos usually contain more examples (I was setting `max_bootstrapped_demos=10, max_labeled_demos=3`, but usually get `4` to `8` examples). I think I misunderstood somehow, could you help me in this ?

cc @okhat @arnavsinghvi11 @krypticmouse @isaacbmiller @thomasahle @CShorten (sorry if I tagged the wrong person)

**Comment by okhat** [comment]
You can set max_labeled_demos=3 and max_bootstrapped_demos=3.

**Comment by thangld201** [comment]
> You can set max_labeled_demos=3 and max_bootstrapped_demos=3.

Thank you for your answer. This worked! May I ask what the `max_bootstrapped_demos` parameter actually means ? (i.e. what bootstrapping actually does here ?). I looked at the paper and thought it was just initial sample selection ?

**Comment by CShorten** [comment]
Hey @thangld201, the `max_bootstrapped_demos` argument refers to how many synthetic examples of your task DSPy will include in the prompt for in-context learning. Contrastively, `max_labeled_demos` refers to examples of your task that you provide. So DSPy can mix and match the synthetic examples it's creating by running through your program with examples that you might already have.

The extensions of `BootstrapFewShotWithOptuna` and `BootstrapFewShotRandomSearch` will try to find the optimal examples for your resulting metric. For example, say you have A,B,C labeled examples and D,E,F synthetic examples with `max_bootstrapped_demos=2` and `max_labeled_demos=2` -- perhaps A,C + E,F results in better performance than A,B + D,E and so on.

Maybe you'll also be interested in the `metric_threshold` argument to control the quality of these synthetic examples a bit further as well if you have a numeric-valued metric. :)

**Comment by thangld201** [comment]
Hi @CShorten Thank you for your answer. By synthetic examples, how does dspy create them ? Does it use self-generated outputs from llm and if metric(input,output) > threshold then that pair is treated as a synthetic example  (i.e. input is user provided and not model generated) ?
