### ISSUE TITLE
Error for minimal use case with (very) small lm

### ISSUE THREAD

**Issue by printfhere** [stanfordnlp/dspy#1876]
Hi,

I'm using the following minimal code from the docs:

```
import dspy

lm = dspy.LM("ollama_chat/smollm2:135m", api_base="http://localhost:11434", api_key="")
dspy.configure(lm=lm)

math = dspy.ChainOfThought("question -> answer")

res = math(
    question="Two dice are tossed. What is the probability that the sum equals two?"
)

print(res)
```

I get the following error:

`ValueError: Expected dict_keys(['reasoning', 'answer']) but got dict_keys(['answer'])`

or similar:

`ValueError: Expected dict_keys(['reasoning', 'answer']) but got dict_keys([])`

From other issues and tests, it would seem that the lm is not large enough to be able to produce the output reliably (it works with larger version of smol for example, but will error on more complex use cases).

Is there a way to use outlines as the backend for structured output generation not only for my modules but even within dspy itself?
Can someone point me in the right direction?

**Comment by eingrid** [comment]
Hi @okhat,

I have similar issue, I wanna Eval 8b quantized llama but some results do not follow schema, therefore can't be parsed. Is there any option to set metric to 0 for such cases?

Here's my current code:

`from dspy.evaluate import Evaluate
evaluate = Evaluate(
    devset=examples,
    metric=metric,
    num_threads=4,
    display_progress=True,
    display_table=0,
    max_errors=1
)
# zero-shot evaluation on examples
score = evaluate(LMCoT())`


looks like failure_score should be related to this (at least by it's name) but I am not quite sure about that

**Comment by eingrid** [comment]
From my vision it would be nice to have smth like 
```

        def process_item(example):
            #I added this try except
            try:
                prediction = program(**example.inputs())
                score = metric(example, prediction)
            except:
                prediction = None
                score = self.failure_score

            # Increment assert and suggest failures to program's attributes
            if hasattr(program, "_assert_failures"):
                program._assert_failures += dspy.settings.get("assert_failures")
            if hasattr(program, "_suggest_failures"):
                program._suggest_failures += dspy.settings.get("suggest_failures")

            return prediction, score

        results = executor.execute(process_item, devset)
        assert len(devset) == len(results)
   
        results = [((dspy.Prediction(), self.failure_score) if r is None else r) for r in results]
        results = [(example, prediction, score) for example, (prediction, score) in zip(devset, results)]
        ncorrect, ntotal = sum(score for *_, score in results), len(devset)
```

But that does not look very nice, probably would be much better to have smth like "return_none_on_error : bool" for if program can't parse the message, from the code it looks like program should be able to return it somehow

**Comment by eingrid** [comment]
Okay, I found solution for me I can just use "_parse_values":False and then do parsing on my own, and then in metric parse it from lm outputs

@

**Comment by rohitgarud** [comment]
From my experience with smaller models Llama 3.2 1B Q8 performs well. @printfhere I know it is around 10 times larger model size in memory, but it gives consistent JSON output

**Comment by printfhere** [comment]
Hi, thanks for the input. Indeed, it starts working better with 1b+ and I manage to make smol135 to work(ish) with sglang as it supports structured outputs. I just didn't realize that structuration of outputs we're outsourced to lm provider (sglang, ollama more recently). Anyway thanks for the help !

**Comment by rohitgarud** [comment]
@printfhere please note that even if you get structured output using sglang or ollama for small models, what the model puts in that structure can still be gibberish or hallucinated data. When I tried Llama 3.2 1B with data extraction from the raw text task, it added things to the structure that were not in the original text, so be careful 😄

**Comment by printfhere** [comment]
@rohitgarud yeah sure! That's why I had some examples to optimize the system but I couldn't even setup the system to begin with.
