### ISSUE TITLE
Using DSPy with Qdrant and ColQwen2

### ISSUE THREAD

**Issue by kubni** [stanfordnlp/dspy#1882]
Hello. 
I used `ColQwen2` model from Colpali team to generate embeddings and store them into my Qdrant database.
I wanted to try out DSPy, but I can't get it to retrieve the points from Qdrant:
```python
llm = dspy.OpenAI(model="gpt-4o-mini")
retriever_model = QdrantRM(
    qdrant_collection_name=collection_name, qdrant_client=qdrant_client
)
dspy.settings.configure(lm=llm, rm=retriever_model)

retrieve = dspy.Retrieve()
question = "List all institutional stakeholders"
topK_passages = retrieve(question).passages

for passage in topK_passages:
    print(f"Passage: {passage}\n")
```
I get the following error:
```
qdrant_client.http.exceptions.UnexpectedResponse: Unexpected Response: 400 (Bad Request)
Raw response content:
b'{"status":{"error":"Wrong input: Vector dimension error: expected dim: 128, got 384"},"time":0.000274272}'
```

I have tried changing the Vectorizer used but to no avail.
Colqwen2 produces `multi-vector embeddings`, I am not sure if that is supported by DSPy.
Any ideas?

**Comment by kubni** [comment]
For example, when I am querying the Qdrant database the standard way (without DSPy), I am using  the following code:
```python
 with torch.no_grad():
        batch_query = processor.process_queries([query_text]).to(model.device)
        query_embedding = model(**batch_query)

    # print("Query embedding: ", query_embedding)

    multivector_query = (
        query_embedding[0].cpu().float().tolist()
    )  # We only have one query, so 0 is okay

    # print("Multivector_query: ", multivector_query)

    start = time.time()
    search_result = qdrant_client.query_points(
        collection_name=collection_name,
        query=multivector_query,
        limit=top_k,
        timeout=100,
        search_params=models.SearchParams(
            quantization=models.QuantizationSearchParams(
                ignore=False,
                rescore=True,
                oversampling=2.0,
            ),
            hnsw_ef=128,
            exact=True,
        ),
    )
    end = time.time()
    print(f"Query finished. Took {end - start}s.")
```

This `multivector_query` is also a multivector, not a single list of embeddings.

**Comment by kubni** [comment]
When I am searching the database the usual way (without DSPy) I do something like this:
```python
 with torch.no_grad():
        batch_query = processor.process_queries([query_text]).to(model.device)
        query_embedding = model(**batch_query)

  multivector_query = (
      query_embedding[0].cpu().float().tolist()
  ) 
  
  
  search_result = qdrant_client.query_points(
      collection_name=collection_name,
      query=multivector_query,
      limit=top_k,
      timeout=100,
      search_params=models.SearchParams(
          quantization=models.QuantizationSearchParams(
              ignore=False,
              rescore=True,
              oversampling=2.0,
          ),
          hnsw_ef=128,
          exact=True,
      ),
  )

```

Here, `multivector_query` that is used for searching is a vector of 27 vectors of size 128.
Qdrant knows how to handle it since its configured to use MAX_SIM comparison.

I couldn't find a way to do something similar with DSPy so far.

**Comment by kubni** [comment]
Thanks for the reply. I will try some of the ideas you proposed.

**Comment by kubni** [comment]
Okay, thanks for the heads up, @okhat . I am still new to DSPy, so I am trying to see how various things work and fit together.
I will definitely try using the LM modules.

**Comment by kubni** [comment]
Hey @okhat. My RAG pipeline involves retrieving a Qdrant point which contains a base64 encoded image from the database, and afterwards I pass it to the VLM like 4o-mini.
Is this possible with DSPy LM modules?
I see some closed PRs but it doesn't say that they are merged?

**Comment by okhat** [comment]
@kubni Basically, you don't need DSPy features for the retrieval parts, since you want to use Qdrant or multi-vector serving or whatnot. Rely on DSPy only for the LM steps.

**Comment by okhat** [comment]
If you want to use an experimental feature that's not yet publicly documented, you can do this:

https://github.com/stanfordnlp/dspy/blob/main/examples/vlm/mmmu.ipynb
