### ISSUE TITLE
Support more ast types in Signature typed parsing

### ISSUE THREAD

**Issue by thomasahle** [stanfordnlp/dspy#1899]
On the website, you [see this example](https://dspy.ai/#__tabbed_3_3): 
```python
import dspy
dspy.configure(lm=dspy.LM('gpt-4o-mini-2024-07-18'))

# Define the DSPy module for classification. It will use the hint at training time, if available.
signature = dspy.Signature("text -> label").with_updated_fields('label', type_=Literal[tuple(CLASSES)])
classify = dspy.ChainOfThoughtWithHint(signature)

# Optimize via BootstrapFinetune.
optimizer = dspy.BootstrapFinetune(metric=(lambda x, y, trace=None: x.label == y.label), num_threads=24)
optimized = optimizer.compile(classify, trainset=trainset)

optimized_classifier(text="What does a pending cash withdrawal mean?")
```

This would have been a lot cleaner as
```
signature = dspy.Signature(f"text -> label:Literal{CLASSES}")
```

We already has support for most of this.
If you see https://github.com/stanfordnlp/dspy/blob/a8d11075daf7b39b890bf47d8d9d4aa8b1cc9b14/dspy/signatures/signature.py#L402 you just have to add a case for `ast.Constant`, like this:

```python
    if isinstance(node, ast.Constant):
        return node.value
```

Then you get
```
In[1]: dspy.Signature(f"text -> label:Literal[1,2]")
Out[1]:
StringSignature(text -> label
    instructions='Given the fields `text`, produce the fields `label`.'
    text = Field(annotation=str required=True json_schema_extra={'__dspy_field_type': 'input', 'prefix': 'Text:', 'desc': '${text}'})
    label = Field(annotation=Literal[1, 2] required=True json_schema_extra={'__dspy_field_type': 'output', 'prefix': 'Label:', 'desc': '${label}'})
)
```
and
```
In[1]: CLASSES = ["good", "bad"]
In[2]: dspy.Signature(f"text -> label:Literal{CLASSES}")
Out[2]:
StringSignature(text -> label
    instructions='Given the fields `text`, produce the fields `label`.'
    text = Field(annotation=str required=True json_schema_extra={'__dspy_field_type': 'input', 'prefix': 'Text:', 'desc': '${text}'})
    label = Field(annotation=Literal['good', 'bad'] required=True json_schema_extra={'__dspy_field_type': 'output', 'prefix': 'Label:', 'desc': '${label}'})
)
```

**Comment by okhat** [comment]
Hey @thomasahle ! Welcome back --- so happy to see an issue from you once again!

Yes this makes sense to me. I wonder also if we should consider the following syntactic sugar:

```python
dspy.Signature("a, b -> c", a=int, c=dspy.Out(float, desc="percentage score")) # b=str by default
```

**Comment by thomasahle** [comment]
Having something like that would be nice when using more complicated types. Though we also still have the decorator in https://github.com/stanfordnlp/dspy/blob/6178c28ce96b2ecb8a21c722ff06cac58b0bb83c/dspy/functional/functional.py#L22 which gives you
```python
@predictor
def classify(text:str) -> label:Literal[*CLASSES]:
    pass
```

However, for simple types and demos, the string notation is still neat though. Presumably we still want to allow
`dspy.Signature("context:list[str], query:str -> answer:str")` and all that, so we might as well give full access to things like `dspy.Signature("a -> Literal[1,2,3]")`.
After all, the code is already there, and very general using the `ast` module.

**Comment by thomasahle** [comment]
Just forgot, we also have this inline way of creating Signatures:
```python
sig = Signature({
    "input_str_list": (List[str], InputField()),
    "input_dict_int": (Dict[str, int], InputField()),
    "output_tup": (Tuple[int, float], OutputField()),
})
```
but that's probably not recommended in most code.
