### ISSUE TITLE
Compiled models are saved using ascii characters only

### ISSUE THREAD

**Issue by RawEnchilada** [stanfordnlp/dspy#1911]
The compiled prompts are converted into unicode special characters when saved.

The simple fix is to pass the optional ensure_ascii parameter to json.dumps

**Comment by okhat** [comment]
Just so I understand. Do you want to allow ensure_ascii=False? Should we just make it False by default?

**Comment by okhat** [comment]
I'm closing this to avoid discussing the same thing in two places. Will discuss in the PR.
