### ISSUE TITLE
function calling

### ISSUE THREAD

**Issue by DmitriyG228** [stanfordnlp/dspy#192]
Hey, I have been using function calling through llamaindex and langchain to delivere structured output. Can you give a hint on how to implement this in dspy?

**Comment by DmitriyG228** [comment]
I am tying to set function call with lm set in dspy.settings.
``
turbo = dspy.OpenAI(model='gpt-3.5-turbo-16k',
                    max_tokens=7000,
                    functions=[function],
                    function_call={"name": "client_meeting_insights"}, ) #gpt-3.5-turbo-16k
dspy.settings.configure(lm=turbo)`


the function:
`
function  = {
    "name": "client_meeting_insights",
    "description": "A function that takes in a list of arguments related to client meetings and processes the insights.",
    "parameters": {
        "type": "object",
        "properties": {
            "start_time": {
                "type": "string",
                "description": "The start time of the insight in the format HH:mm."
            },
            "tags": {
                "type": "array",
                "description": "Tags categorizing the type of insights.",
                "items": {
                    "type": "string"
                }
            },
            "description": {
                "type": "string",
                "description": "The description of the insight gathered from the client meeting."
            }
        }
    },
    "required": ["start_time", "tags", "description"]
}
`


here is the error:


`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[/app/nbs/call_annotated_2610/evaluate.ipynb](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f315f6e6f7363726962655f6465762d6170702d31227d-0040ssh-002dremote-002bbbb.vscode-resource.vscode-cdn.net/app/nbs/call_annotated_2610/evaluate.ipynb) Cell 16 line 4
      [2](vscode-notebook-cell://attached-container%2B7b22636f6e7461696e65724e616d65223a222f315f6e6f7363726962655f6465762d6170702d31227d@ssh-remote%2Bbbb/app/nbs/call_annotated_2610/evaluate.ipynb#X12sdnNjb2RlLXJlbW90ZQ%3D%3D?line=1) fail = []
      [3](vscode-notebook-cell://attached-container%2B7b22636f6e7461696e65724e616d65223a222f315f6e6f7363726962655f6465762d6170702d31227d@ssh-remote%2Bbbb/app/nbs/call_annotated_2610/evaluate.ipynb#X12sdnNjb2RlLXJlbW90ZQ%3D%3D?line=2) for chunk in chunks:
----> [4](vscode-notebook-cell://attached-container%2B7b22636f6e7461696e65724e616d65223a222f315f6e6f7363726962655f6465762d6170702d31227d@ssh-remote%2Bbbb/app/nbs/call_annotated_2610/evaluate.ipynb#X12sdnNjb2RlLXJlbW90ZQ%3D%3D?line=3)     r = compiled.predict(chunk=chunk)
      [5](vscode-notebook-cell://attached-container%2B7b22636f6e7461696e65724e616d65223a222f315f6e6f7363726962655f6465762d6170702d31227d@ssh-remote%2Bbbb/app/nbs/call_annotated_2610/evaluate.ipynb#X12sdnNjb2RlLXJlbW90ZQ%3D%3D?line=4)     try: 
      [6](vscode-notebook-cell://attached-container%2B7b22636f6e7461696e65724e616d65223a222f315f6e6f7363726962655f6465762d6170702d31227d@ssh-remote%2Bbbb/app/nbs/call_annotated_2610/evaluate.ipynb#X12sdnNjb2RlLXJlbW90ZQ%3D%3D?line=5)         success.append((chunk,eval(r.answer)))

File [/usr/local/lib/python3.9/site-packages/dspy/predict/predict.py:57](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f315f6e6f7363726962655f6465762d6170702d31227d-0040ssh-002dremote-002bbbb.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/dspy/predict/predict.py:57), in Predict.__call__(self, **kwargs)
     56 def __call__(self, **kwargs):
---> 57     return self.forward(**kwargs)

File [/usr/local/lib/python3.9/site-packages/dspy/predict/predict.py:81](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f315f6e6f7363726962655f6465762d6170702d31227d-0040ssh-002dremote-002bbbb.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/dspy/predict/predict.py:81), in Predict.forward(self, **kwargs)
     78 x = dsp.Example(demos=demos, **kwargs)
     80 if self.lm is None:
---> 81     x, C = dsp.generate(signature, **config)(x, stage=self.stage)
     82 else:
     83     with dsp.settings.context(lm=self.lm, query_only=True):
     84         # print(f"using lm = {self.lm} !")

File [/usr/local/lib/python3.9/site-packages/dsp/primitives/predict.py:79](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f315f6e6f7363726962655f6465762d6170702d31227d-0040ssh-002dremote-002bbbb.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/dsp/primitives/predict.py:79), in _generate.<locals>.do_generate(example, stage, max_depth, original_example)
     77 prompt = template(example)
     78 completions: list[dict[str, Any]] = generator(prompt, **kwargs)
---> 79 completions: list[Example] = [template.extract(example, p) for p in completions]
     81 # Find the completions that are most complete.
     82 field_names: list[str] = [field.input_variable for field in template.fields]

File [/usr/local/lib/python3.9/site-packages/dsp/primitives/predict.py:79](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f315f6e6f7363726962655f6465762d6170702d31227d-0040ssh-002dremote-002bbbb.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/dsp/primitives/predict.py:79), in <listcomp>(.0)
     77 prompt = template(example)
     78 completions: list[dict[str, Any]] = generator(prompt, **kwargs)
---> 79 completions: list[Example] = [template.extract(example, p) for p in completions]
     81 # Find the completions that are most complete.
     82 field_names: list[str] = [field.input_variable for field in template.fields]

File [/usr/local/lib/python3.9/site-packages/dsp/templates/template_v2.py:146](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f315f6e6f7363726962655f6465762d6170702d31227d-0040ssh-002dremote-002bbbb.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/dsp/templates/template_v2.py:146), in TemplateV2.extract(self, example, raw_pred)
    135 """Extracts the answer from the LM raw prediction using the template structure
    136 
    137 Args:
   (...)
    142     Example: The example with the output variables filled in
    143 """
    144 example = dsp.Example(example)
--> 146 raw_pred = raw_pred.strip()
    148 idx = 0
    149 while idx < len(self.fields):

AttributeError: 'NoneType' object has no attribute 'strip'`

**Comment by haddyadnan** [comment]
@DmitriyG228 Have you been able to achieve this?

**Comment by ctyler9** [comment]
having a similar issue. can't even call the simple RAG pipeline in a flask server. probably some threading issue

**Comment by jamesschinnerplxs** [comment]
Do you need to specify it as tools?

https://platform.openai.com/docs/api-reference/chat/create#chat-create-tools

**Comment by jamesschinnerplxs** [comment]
I managed to get this to work by modifying `_get_choice_text` like so:

```
def _get_choice_text(self, choice: dict[str, Any]) -> str:
        if self.model_type == "chat":
            message = choice["message"]
            if content := message['content']:
                return content
            elif tool_calls := message.get('tool_calls', None):
                return json.dumps([tool['function']['arguments'] for tool in tool_calls])
        return choice["text"]
```

NOTE: I'm using tools and tool_choice https://platform.openai.com/docs/api-reference/chat/create#chat-create-tools
