### ISSUE TITLE
Cannot save state of optimized modules with images in demos

### ISSUE THREAD

**Issue by itay-verkh-lightricks** [stanfordnlp/dspy#1920]
I have a `dspy.Module` that takes an Image input and I use `LabeledFewshot` optimizer to save some demos that include images. Those images are saved as `PIL` image objects which are not JSON serializable and thus can't be saved in the current implementation

**Comment by okhat** [comment]
Might be fixed by #1889 ?

**Comment by itay1542** [comment]
closing this, seems like it will be fixed in the next release
