### ISSUE TITLE
Cache flag on but no cache saved on designated directory

### ISSUE THREAD

**Issue by dovanquyet** [stanfordnlp/dspy#1924]
I am using DSPy 2.5.4x on Google Colab.

I ran the following snipper to setup DSPy (copied and modified from https://github.com/stanfordnlp/dspy/blob/main/examples/intro.ipynb)

```[python]
!pip install dspy-ai
import dspy

# Set up the cache for this notebook
# https://dspy.ai/faqs/#:~:text=you%20can%20turn%20off%20the%20cache%20by%20setting
# From v2.5, need to use DSPY_* instead of DSP_*
# os.environ["DSP_NOTEBOOK_CACHEDIR"] = os.path.join(os.getcwd(), 'cache')
# os.environ["DSP_CACHEDIR"] = os.path.join(os.getcwd(), 'cache')
os.environ["DSPY_NOTEBOOK_CACHEDIR"] = os.path.join(os.getcwd(), 'cache')
os.environ["DSPY_CACHEDIR"] = os.path.join(os.getcwd(), 'cache')

# Configure dspy
# Update the API call https://github.com/stanfordnlp/dspy/blob/main/examples/migration.ipynb
gpt4omini = dspy.LM(
    api_key=userdata.get('...'),
    model='openai/gpt-4o-mini',
    temperature=0.7,
    max_tokens=2048
)

dspy.settings.configure(lm=gpt4omini)
print(gpt4omini.cache, dspy.settings)
```

I believe that it saved cache somewhere, as when I reran DSPy code, I got result again instantly. However, it didn't save cache of my DSPy runs into the designated dir. 

Can you help solve this problem, so that I can save cache permanently on my Google Drive (for reproduction purpose). Many thanks!

**Comment by chenmoneygithub** [comment]
@dovanquyet Thanks for reporting the issue! Seems like the env var is not setting the litellm cache's directory properly. But you can find the litellm cache's location by:

```
litellm.cache.cache.disk_cache._directory
```

On my colab it is giving `/root/.dspy_cache`

**Comment by chenmoneygithub** [comment]
@dovanquyet  Thanks for reporting the issue! In order to have `os.environ["DSPY_CACHEDIR"]` function properly, you need to set the env var before `import dspy`

**Comment by dovanquyet** [comment]
It works! Thanks a lot!
