### ISSUE TITLE
Why isn't JSONAdapter the default adapter option?

### ISSUE THREAD

**Issue by DiyarD** [stanfordnlp/dspy#1932]
In `dspy/predict/predict.py` the default adapter is the `ChatAdapter`:

```python
def v2_5_generate(lm, lm_kwargs, signature, demos, inputs, _parse_values=True):
    import dspy

    adapter = dspy.settings.adapter or dspy.ChatAdapter()

    return adapter(
        lm, lm_kwargs=lm_kwargs, signature=signature, demos=demos, inputs=inputs, _parse_values=_parse_values
    )
```

But once that fails (`adapter/base.py`):
```python
        try:
            for output in outputs:
                value = self.parse(signature, output, _parse_values=_parse_values)
                assert set(value.keys()) == set(signature.output_fields.keys()), f"Expected {signature.output_fields.keys()} but got {value.keys()}"
                values.append(value)
            return values

        except Exception as e:
            from .json_adapter import JSONAdapter
            if _parse_values and not isinstance(self, JSONAdapter):
                return JSONAdapter()(lm, lm_kwargs, signature, demos, inputs, _parse_values=_parse_values)
            raise e
```

It switches to the `JSONAdapter`.

In my experience the ChatAdapter always fails wasting the LLM call (at least 2 calls are done for each prompt).

I know it can be set as default via `dspy.configure(lm=lm, adapter=dspy.JSONAdapter())`, but why isn't the `JSONAdapter` the default one?

**Comment by okhat** [comment]
Hey @DiyarD ! What model are you using? How complex is your signature?

For most signatures, chat adapter has a higher quality of outputs, but LMs sometimes fail to follow its structure. Hence the default strategy of using chat and fallback to json.

**Comment by okhat** [comment]
@DiyarD Yes, in our own testing, our chat adapter does have higher quality output than our JSON adapter.

There has been some discussion of the post you sent, e.g. https://x.com/dylanjcastillo/status/1867154938759155750

The tl;dr of all of these posts is clear IMO. There are three things here:

1. The prompt is the most important thing. Structured outputs cannot make up for a bad prompt.
2. The output template is the second most important thing. If the LM finds the template of its outputs confusing, the values it produces will not be good.
3. Given the best settings in (1) & (2) above, enforcing the structure at decoding time is preferrable whenever possible.

However, in practice, (3) tends to restrict (1) and (2) so much right now. I hope this changes in the future. But right now, if you want structured outputs, you tend to need (1) and (2) to overcommit to JSON specifically. Many types of outputs, like long-form RAG or code generation, are simply unusual for LLMs to see in JSON format. This does reflect itself in various anecdotes of lower quality, some of which we saw in our testing.

I hope this helps :D

**Comment by marfago** [comment]
It seems to me that the way the ChatAdpater is strucutring the output is confusing. For example in my case where I have a Signature with an output list of pydantic objects, it is adding this instruction

```
Respond with the corresponding output fields, starting with the field `[[ ## references ## ]]` (must be formatted as a valid Python list[Reference]), and then ending with the marker for `[[ ## completed ## ]]`.
```

The output is never a json string because the model follows the instruction and returns `[[ ## references ## ]]` and `[[ ## completed ## ]]`.
