### ISSUE TITLE
ProgramOfThought Requires New Signature Notation, Should Also Work with Original Notation

### ISSUE THREAD

**Issue by kevinbird15** [stanfordnlp/dspy#194]
I tried to use Program of thought in the intro notebook after the chain of thought cell, but I get the following error: 

```
# Define the predictor. Notice we're just changing the class. The signature BasicQA is unchanged.
generate_answer_with_program_of_thought = dspy.ProgramOfThought(BasicQA)

# Call the predictor on the same input.
pred = generate_answer_with_program_of_thought(question=dev_example.question)

# Print the input, the program of thought, and the prediction.
print(f"Question: {dev_example.question}")
print(f"Thought: {pred.rationale.split('.', 1)[1].strip()}")
print(f"Predicted Answer: {pred.answer}")
```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[54], line 2
      1 # Define the predictor. Notice we're just changing the class. The signature BasicQA is unchanged.
----> 2 generate_answer_with_program_of_thought = dspy.ProgramOfThought(BasicQA)
      4 # Call the predictor on the same input.
      5 pred = generate_answer_with_program_of_thought(question=dev_example.question)

File ~/Environment_personal/development/dspy/dspy/predict/program_of_thought.py:13, in ProgramOfThought.__init__(self, signature, max_iters)
     10 self.signature = signature = dspy.Predict(signature).signature
     11 self.max_iters = max_iters
---> 13 self.input_fields = signature.input_fields()
     14 self.output_fields = signature.output_fields()
     16 inputs_ = ', '.join([f"`{field_name}`" for field_name in self.input_fields.keys()])

TypeError: Signature.input_fields() missing 1 required positional argument: 'self'
```

When looking at the ProgramOfThought class, I see that it inherits from Module whereas ChainOfThought inherits from Predict and the signature is passed into the super init.  This doesn't happen in ProgramOfThought so the signature is the class BasicQA rather than an instance of that class.  I am new to this library so it's possible I am not using it correctly.

**Comment by okhat** [comment]
@arnavsinghvi11 has been extending and revising PoT, we'll make sure to fix this too with a new merge in the coming few days

**Comment by kevinbird15** [comment]
Sounds good! Is there anything I could do that would be helpful here?

**Comment by arnavsinghvi11** [comment]
Hi @kevinbird15 

Thank you for raising this point. This is particularly relevant to some of the ongoing changes within PoT I will be pushing out. However, temporarily, you can try PoT out with the simplified signature format 

`generate_answer_signature = dspy.Signature("question -> answer")
 generate_answer_signature.attach(question=("Question:", "")).attach(answer=("Answer:", "often between 1 and 5 words"))
`

Currently, we are transitioning from the older Signature class to support more modular methods, which might have led to some inconsistencies. These changes also require documentation which will be forthcoming! Feel free to check out the updated [Signature class](https://github.com/stanfordnlp/dspy/blob/f1084c7c3d85994307049b58c982668ccccf048f/dspy/signatures/signature.py#L53) for further details and let me know if you have any additional questions!
