### ISSUE TITLE
Different running time if already seen

### ISSUE THREAD

**Issue by MatFrancois** [stanfordnlp/dspy#1951]
Hi,

I aim to compare LLMs classification tasks on several models applied to thousands of data.
I am using ollama (with gpu) to run LLM as described in doc. 
And I'm using batch mod as follows to run several calls to ollama simultaneously and gain time.

```python
class ClassifyMultiLabel(dspy.Signature):
    sentence: str = dspy.InputField()
    subject: list[Literal["toto1", "toto2", "toto3"]] = dspy.OutputField()

class mod(dspy.Module):
    def __init__(self):
        super().__init__()
        self.cm = dspy.Predict(ClassifyMultiLabel)
    def forward(self, sent):
        try:
            return self.cm(sentence=sent)
        except (ValidationError, ValueError):
            return None
module = mod()
module.batch(examples=list_of_Examples, num_threads=128, max_errors=0)
```

When I run `module.batch` on a given sample, calls to api/chat and api/show are made on the ollama side (which takes quite a long time).

On the other hand, if I restart the kernel and run the same tasks again, it becomes almost immediate for the data previously seen by the model and there are no more api/chat calls. Is this behavior due to dspy? 

Is there a better way to increase the speed of inference? (or maybe dspy is not made to do this?)

**Comment by okhat** [comment]
That's just caching. Do you want to disable it? Set cache=False in dspy.LM if you want.
