### ISSUE TITLE
Signature OutputField(), does not work properly

### ISSUE THREAD

**Issue by nandhakumarsuriya** [stanfordnlp/dspy#1953]
SIGNATURE:
class Emotion(dspy.Signature):
    """Classify emotion."""
    sentence: str = dspy.InputField()
    sentiment: Literal['sadness', 'joy', 'love', 'anger', 'fear', 'surprise'] = dspy.OutputField()
    
  here the labels ['sadness', 'joy', 'love', 'anger', 'fear', 'surprise'] are not reflected in prompt.
  
  PROMPT :
  Classify emotion.

---

Follow the following format.

Sentence: ${sentence}
Sentiment: ${sentiment}

---

Sentence: i started feeling a little vulnerable when the giant spotlight started blinding me
Sentiment:

OUTPUT:
Negative (vulnerable)

DSPY VERSION: Version: 2.5.39

**Comment by okhat** [comment]
You're not using dspy.LM and are using a deprecated LLM client.

Please migrate: https://github.com/stanfordnlp/dspy/blob/main/examples/migration.ipynb

**Comment by nandhakumarsuriya** [comment]
> You're not using dspy.LM and are using a deprecated LLM client.
> 
> Please migrate: https://github.com/stanfordnlp/dspy/blob/main/examples/migration.ipynb

im using ollma for importing model, how to migrate this

**Comment by XiaoMaGe-hero** [comment]
It seems that DSPy was not designed for you.
