### ISSUE TITLE
"parameters are not available on gpt-35-turbo model" error

### ISSUE THREAD

**Issue by jhyearsley** [stanfordnlp/dspy#198]
I'm trying to experiment with DSPy using the specific model I have access to (in this case gpt-3.5-turbo) and when running this code:
```
turbo = dspy.OpenAI(
    api_provider="azure",
    api_base=api_base,
    api_key=api_key,
    api_version=api_version,
    deployment_id=<GPT-3.5-Turbo>
)

prompt = "Translate the following English text to Spanish: 'Hi, how are you?'"
completions = turbo(prompt, n=5, return_sorted=False)
for i, completion in enumerate(completions):
    print(f"Completion {i+1}: {completion}")
```

I'm getting the error:
```
File "/opt/homebrew/lib/python3.11/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: logprobs, best_of and echo parameters are not available on gpt-35-turbo model. Please remove the parameter and try again. For more details, see https://go.microsoft.com/fwlink/?linkid=2227346.
```

I tried removing the specific parameters from the kwargs but didn't seem to work. I'd love to get this library working I think it will be much better than the other options I'm considering but if I can't get it setup then unfortunately the "hacker move-on syndrome" tends to kick in... BUT I'm very interested in this library and can see the value add so please help!!

**Comment by okhat** [comment]
pass model_type as “chat”

**Comment by okhat** [comment]
Or use the latest version from the main branch, either approach will do

**Comment by jhyearsley** [comment]
Oh perfect, passing model_type as "chat" worked! thanks so much
