### ISSUE TITLE
My own retriever and LLM 

### ISSUE THREAD

**Issue by shahad2099** [stanfordnlp/dspy#209]
Hello everyone!

I'm new to this framework and I want to build an RAG model. I'd like to use my own retriever and language model. Are there any guidelines for doing this? Also, my model is in a non-English language. Do I need to make any changes to the framework's configuration, or is it language-agnostic?

Thanks for your help!"

**Comment by okhat** [comment]
As long as the instructions (or signatures) are in English, and one of your LMs supports in-context learning in English, this is going to work fine.

Adding a retriever is very simple, just check any of the existing ones in dspy/retrieve/*

Which LM are you trying to use?

**Comment by shahad2099** [comment]
My model is Llama,and is trained  with Arabic language data. Do you believe it will perform effectively?

Regarding the retriever,how can I utilize my custom retriever and vector database from a different framework? I've already implemented and stored text corpora using another framework and wish to integrate them seamlessly.

**Comment by shahad2099** [comment]
> As long as the instructions (or signatures) are in English, and one of your LMs supports in-context learning in English, this is going to work fine.
> 
> Adding a retriever is very simple, just check any of the existing ones in dspy/retrieve/*
> 
> Which LM are you trying to use?



> As long as the instructions (or signatures) are in English, and one of your LMs supports in-context learning in English, this is going to work fine.
> 
> Adding a retriever is very simple, just check any of the existing ones in dspy/retrieve/*
> 
> Which LM are you trying to use?

My model is Llama,and is trained with Arabic language data. Do you believe it will perform effectively?

Regarding the retriever,how can I utilize my custom retriever and vector database from a different framework? I've already implemented and stored text corpora using another framework and wish to integrate them seamlessly.

**Comment by okhat** [comment]
Llama typically works well with English too, so it should be fine.

See here on using local models: https://github.com/stanfordnlp/dspy/blob/main/docs/language_models_client.md#tgi

**Comment by tm16-medma** [comment]
@shahad2099 How is it going with running the non-english large language model? I also want to use DSPy with a german fine tuned mistral model from (https://huggingface.co/jphme/em_german_leo_mistral) and am not sure if that is possible.

**Comment by samiit** [comment]
@okhat 
Thanks for this great work. I just got exposed to it over the weekend, and hope am not too late. I wanted to understand how, say local models served via OLLAMA can be utilized with DSPy?

Thanks,
Sam

**Comment by okhat** [comment]
Someone did this recently:

https://gist.github.com/jrknox1977/78c17e492b5a75ee5bbaf9673aee4641

**Comment by okhat** [comment]
I think it addresses this basically, hence closing but feel free to reopen with further questions
