### ISSUE TITLE
Bootstrapped 0 full traces

### ISSUE THREAD

**Issue by rohitpatki** [stanfordnlp/dspy#210]
I am trying to compile a simple program from the Skycamp tutorial for question answering with just a language model (Mistral 7B). I removed the retriever module because I just want to see which demonstrations are picked by the compiler for in-context learning.

`mistral` = dspy.dsp.modules.HFModel(model="mistralai/Mistral-7B-v0.1")
`dspy.settings.configure(lm=mistral)`

```
class BasicQA(dspy.Signature):
    """Answer questions with adult or not"""

    question = dspy.InputField(desc="Does the given text have adult intent or not?")
    answer = dspy.OutputField(desc="between adult or not adult")

# Define the predictor.
generate_my_answer = dspy.Predict(BasicQA)

# Define module
class my_module(dspy.Module):  # let's define a new module
    def __init__(self):
        super().__init__()
        self.generate_answer = generate_my_answer
    
    def forward(self, question):
        return self.generate_answer(question=question)  # here we use the module

from dspy import evaluate, teleprompt

metric_EM = dspy.evaluate.answer_exact_match

teleprompter = teleprompt.BootstrapFewShot(metric=metric_EM, max_bootstrapped_demos=2)
adult_compiled = teleprompter.compile(adult_classifier_module(), trainset=train)
```

I keep getting this after compiling:
`Bootstrapped 0 full traces after 7 examples in round 0.`

What does this mean and how can I resolve it? I tried predicting on a new question and the format of the response is not as expected.

**Comment by okhat** [comment]
Hey @rohitpatki !

A few thoughts:

Using `HFModel` is not really encouraged. Can you use the `TGI` client for HF models?

`Bootstrapped 0 full traces` means the zero-shot prompts (for your Mistral LM) were not able to correctly answer any of the 7 questions you have in your training set, so the bootstrap process didn't kickstart. It couldn't produce few-shot examples.

This is almost certainly just an issue with Mistral not knowing when to stop generating things. If you use TGI, it'll stop (by default) at new lines, which will help with this.

**Comment by okhat** [comment]
In general, please look at some examples and you'll see the issue almost immediately.

After compiling, just do:

```mistral.inspect_history(n=7)```

**Comment by okhat** [comment]
Pinging here before closing.

**Comment by rohitpatki** [comment]
Thank you! I will give this a try. Feel free to close.
