### ISSUE TITLE
Error when using KNNFewShot Teleprompter

### ISSUE THREAD

**Issue by danielmachlab** [stanfordnlp/dspy#215]
I am trying to use the `KNNFewShot` teleprompter to use KNN for selecting examples to include in my prompt. [Here](https://gist.github.com/danielmachlab/b67b1a960f50a00367d1cdf6a805fa5c) is a Gist with how I am trying to use the teleprompter. Perhaps I am using the teleprompter incorrectly, but I think the issue lies in the `dspy/dsp/modules/sentence_vectorizer.py` file where  `_extract_text_from_examples`:

1. expects `inp_examples` to be a list of `Example` objects, but it is a list of strings.
2. expects `Example` objects to have a field called `'text_to_vectorize'`, but they do not contain this field

Am I using the teleprompter incorrectly or is there a bug in the code?

**Comment by okhat** [comment]
@danielmachlab Two teleprompters (KNNFewShot and Optuna) are provided as highly experimental things. There's a good chance they're not perfectly streamlined yet. (I haven't reviewed them in detail myself.) Do you want to open a PR with some improvements?

**Comment by danielmachlab** [comment]
@okhat #222 fixes the KNN functionality and #226 adds and example of how to use it. Can you check them out?

**Comment by okhat** [comment]
Really appreciate this @danielmachlab !
