### ISSUE TITLE
Failed to install with optional extra such as dspy-ai[pinecone]

### ISSUE THREAD

**Issue by kayue** [stanfordnlp/dspy#218]
I encountered an issue where the installation process returned an error and did not install the optional extra. This issue was consistent across two different environments, including Google Colab and Hex.tech and my local terminal.

The specific error message I received when I `!pip install dspy-ai[pinecone]` is as follows:

```
WARNING: dspy-ai 2.0.4 does not provide the extra 'pinecone'
```

I tried to install from source but still encounter other error related to `dsp.utils` import.

I would greatly appreciate any guidance or assistance you can provide to resolve this issue. Thank you in advance for your time.

**Comment by okhat** [comment]
Yeah we haven’t pushed the latest integrations to pypi (pip) yet

**Comment by okhat** [comment]
You can install with pip from github main though

**Comment by kayue** [comment]
@okhat Thank you, confirmed that `!pip install git+https://github.com/stanfordnlp/dspy.git` works.

I noticed ChromadbRM contain a type error `chromadb.Collection` type does not exist. I might submit a PR later after confirming everything is working. 

Cheers!
