### ISSUE TITLE
Is this an "Example Retriever" optimisation or it can also produce prompt from scratch like "LLM as Optimizers" ? 

### ISSUE THREAD

**Issue by gabgen** [stanfordnlp/dspy#219]
It is not clear if the teleprompter is just a way to retrieve a good example from your training dataset or it can also write a prompt from scratch , and in this case how .

**Comment by okhat** [comment]
It's an example _generation_ optimization, for a complete pipeline of steps. This is a lot richer than "LLM as Optimizers", which only optimizes a few words at the start of the prompt.

**Comment by okhat** [comment]
Learn more in the paper linked from the README (at the top).

**Comment by gabgen** [comment]
> It's an example _generation_ optimization, for a complete pipeline of steps. This is a lot richer than "LLM as Optimizers", which only optimizes a few words at the start of the prompt.

@okhat  thanks for the feedback. "LLM as Optimizers" can actually write a prompt from scratch ( the number of words is tunable). This is particularly useful when you have very few examples to provide, so the problem is not to retrieve a good example, but more to provide a good prompt. In this case, would DSPy provide a solution to generate a good prompt, without relying on examples to put in the prompt?  I saw you have a "finetune" teleprompter , is this something similar to what I am looking for ?
