### ISSUE TITLE
Update to the latest OpenAI library

### ISSUE THREAD

**Issue by Foxman13** [stanfordnlp/dspy#223]
The official Python client for OpenAI is on version 1.3 and contains support for their latest updates (like setting "response_format" to JSON" - https://pypi.org/project/openai/

dspy appears to still be dependent on version 0.28.1

**Comment by sutyum** [comment]
This one is quite important as its blocking usage of in many scenarios

**Comment by okhat** [comment]
Oh wow I didn’t know it was blocking anything. Okay we’ll prioritize this

**Comment by okhat** [comment]
@kevinykuo no update yet, we'd love to merge a PR if you want to open one

**Comment by okhat** [comment]
This is done, if you pip install openai >= 1.0 it will work.

The default is still 0.28 but it's not required for functionality.

Thanks a lot to @DanielUH2019

**Comment by okhat** [comment]
This is on `main` now but not yet on pypi. Won't push to pypi until I get 1-2 confirmations it works fine for people.
