### ISSUE TITLE
Are the save/load functions in BaseModule class meant to save/load the compiled model?

### ISSUE THREAD

**Issue by drawal1** [stanfordnlp/dspy#224]
When I use the save function, it creates a json file. But all it had was demo examples. Is that the full extent of the compiled state??

Alternative is to use pickle to serialize/deserialize the compiled model, but that seems a bit hacky

**Comment by okhat** [comment]
If you're compiling with a "few-shot" teleprompter, you just need the LM, the program, and the state (json). That's indeed all there is.

What else are you thinking of?

**Comment by okhat** [comment]
If you compile via finetuning, it's different.

**Comment by drawal1** [comment]
I expected that the optimized prompt would be saved with the compiled model. I assumed that compilation optimizes the prompt based on the few shot examples. 

From the documentation - "...the DSPy compiler will internally trace your program and then craft high-quality prompts..."

Is this not true?

**Comment by okhat** [comment]
The optimizations applied to each prompt are modular (instructions vs. demonstrations vs. prefixes). It’s not one big string blob.

BootstrapFewShot only optimize demonstrations. We haven’t released the instruction optimizers yet, but they optimize a different part. Etc.

The prompt is then built from these parts.

**Comment by drawal1** [comment]
So there is no performance benefit from saving the compiled model for LabeledFewShot and BootstrapFewShot, yes? We should compile the model every time we run the application?

**Comment by okhat** [comment]
What do you mean? You should save and load if you want to avoid compiling every time!

**Comment by drawal1** [comment]
Got it.

I should probably reread the paper and review the compile functions for each teleprompter carefully to understand better what state is being updated.

Thx for the guidance!
