### ISSUE TITLE
VLLM support not yet merged

### ISSUE THREAD

**Issue by meditans** [stanfordnlp/dspy#225]
Just mentioning this here to avoid anyone being confused by error messages like:
```
AttributeError: module 'dspy' has no attribute 'HFClientVLLM'. Did you mean: 'HFClientTGI'?
```
while following the documentation. See https://github.com/stanfordnlp/dspy/pull/93

**Comment by okhat** [comment]
Yeah it's probably ready to merge. We just need to test it out with a recent vllm version.

Have you given it a shot?

**Comment by meditans** [comment]
I have written a quick version for myself that works with current vLLM, adapting the idea of that commit. I can post a PR if that helps!
