### ISSUE TITLE
How to set prompt templates for local models?

### ISSUE THREAD

**Issue by meditans** [stanfordnlp/dspy#228]
Local models are often sensitive to be prompted with their own prompt template. For example, for Mistral models that would be:

```    
<s>[INST] {prompt} [/INST]
```
What's the mechanism a user of `dspy` should use to set the correct prompt templates for an llm?

**Comment by okhat** [comment]
There's a PR on something called adapters: https://github.com/stanfordnlp/dspy/pull/138

but it's untested and I'm not 100% sure it's fully complete yet.

**Comment by darinkishore** [comment]
@meditans Take a look at how it was implemented for Anyscale!! Unsure where to find rn bc on mobile, but I think looking for anyscale on main branch OR the closed and merged anyscale local branch would be useful. 

if you dig anything else up on this, let me know. i've been thinking about it for a while, but unsure.

if you wanna delve deeper, LiteLLMs update a couple weeks ago allows you to inspect prompt being sent to local model for easy debugging.

**Comment by macksin** [comment]
Often, I notice that this mechanism is implemented on the server side of Large Language Models (LLMs), as seen in [llama-python-cpp](https://github.com/abetlen/llama-cpp-python/blob/7467f129e5cfb61115184402af6645fd9cb4401b/llama_cpp/llama_chat_format.py#L908). Initially, I believe that the mask applied to the models should be part of a separate layer. Similarly, in [Langchain](https://python.langchain.com/docs/integrations/chat/llama2_chat), there is an emphasis on adaptation. However, I am uncertain about how this should integrate with finetuning in DSPy, as I have not yet reviewed the code.

**Comment by bilunsun** [comment]
Any updates on this? It would be great for local models with `dspy.OllamaLocal()`!

**Comment by meditans** [comment]
> Often, I notice that this mechanism is implemented on the server side of Large Language Models (LLMs),

Indeed, in the end that's the case for me too. I am using https://github.com/theroyallab/tabbyAPI as a openai-compatible backend to serve exl2 quantizations, and the business of adding the right markers is handled by the server (using the model's configuration). The frontend only sends the list of messages with the right role.

Hope it's useful @bilunsun

**Comment by maziyarpanahi** [comment]
The TGI by Hugging Face doesn't load any template for the Generate() endpoint. It is up to the user to construct the perfect prompt. There is an OpenAI endpoint however which loads the chat_template with tokenizer.

The HF TGI here uses `generate`, this means we are sending prompts without any bos or eos. I think it is useful to allow users add markers to system/user/and assistant roles if they choose to do so. Default can be whatever it is at the moment, but there is always going to be a case where this is not handled from the server side.

**Comment by okhat** [comment]
Adapters are now pretty useable in DSPy 2.5 see the new migration guide!
