### ISSUE TITLE
BootstrapFewShot teleprompter explanation

### ISSUE THREAD

**Issue by gabgen** [stanfordnlp/dspy#245]
I am trying to understand more about its internal work. In the paper and the videos it seems this teleprompter can actually generate responses from LLMs to be used as examples but not in the documentation, nor in the code I see this. Is it just an example retriever from the dataset provided? 

I don't understand where the "bootstrapping" phase comes into play . In the documentation it said the teacher should be compiled . Supposed we have a compiled teacher ( that should have the same predictors ) , now what ?

**Comment by okhat** [comment]
I recommend you look at the section titled `5] Program 2: Multi-Hop Search (“Baleen”)` in the intro notebook for example.

In particular, the outputs of the demonstrations in the few-shot prompts there are all generated, not retrieved.

**Comment by okhat** [comment]
Here's a link for your convenience: https://colab.research.google.com/github/stanfordnlp/dspy/blob/main/intro.ipynb 

Let me know if this clear it up!

**Comment by gabgen** [comment]
I see. Thanks for this. Still hard to understand the internal work. Could you briefly describe the process of compilation step-by-step? Also, I felt like the demonstrations were coming from the teacher, is that right?

**Comment by okhat** [comment]
Yes demonstrations come from the teacher!

I'll put out a twitter thread in the next 1-2 weeks on how compiling works!

**Comment by ratthachat** [comment]
I agree with the OP. By any chances, could you provide the twitter /x link explaining on how compiler internally work ?

In particular, i get some rough ideas that teacher try to generate demonstrations consistent with the given signatures. However, how the compiler "improves" demonstrations to be better at each step looks magical to me (assuming no gradient descent involves)

**Comment by EssamWisam** [comment]
@okhat this was closed but there isn't an explanation yet. I am also interested in understanding how it works internally.

**Comment by thiswillbeyourgithub** [comment]
> [@okhat](https://github.com/okhat) this was closed but there isn't an explanation yet. I am also interested in understanding how it works internally.

Me too! I'm looking for a way to spend bucks to optimize prompts without getting involved in managing a dataset. i'm sure it's possible for frontier models to comeup with examples, outputs and metrics. Dspy seems like the right tool for the job but man the documentation is not easy to wade through.
