### ISSUE TITLE
Support Assistant API

### ISSUE THREAD

**Issue by iAnanich** [stanfordnlp/dspy#266]
https://platform.openai.com/docs/assistants/overview
OpenAI put Assistant API into Beta

**Comment by okhat** [comment]
Thank you @iAnanich! This is kind of outside our scope!

**Comment by okhat** [comment]
But just to be sure, do you envision it in DSPy in a specific way?

**Comment by iAnanich** [comment]
As starting point: just as alternative to using GPT turbo. That will allow for using more advanced LM, with its own augmented knowledge base, access to internet and ability to execute code, which can be used instead of hops using RM.
That is the main point.

Additionally, it would be nice to support system prompt for both assistant and regular GPT - instead of tuning user prompt and sending it as such, examples and formatting could be specified in system prompt (was discussed in some other issue already).

**Comment by okhat** [comment]
Interesting. These are worth exploring but we don't have the capacity to test them. Let me know if you can, otherwise we can close this and reopen down the line? In 3-4 months it's quite possible OpenAI will completely change their API again anyway!

**Comment by iAnanich** [comment]
True...
Yet i think its a powerful feature to get GPT with  files you can upload.
Cannot promise i would implement it, but there 's a possibility
