### ISSUE TITLE
Open up retrieval from Qdrant to custom models

### ISSUE THREAD

**Issue by fronx** [stanfordnlp/dspy#267]
It seems that retrieval from Qdrant is limited to the following models:

```python
SUPPORTED_EMBEDDING_MODELS: Dict[str, Tuple[int, models.Distance]] = {
    "BAAI/bge-base-en": (768, models.Distance.COSINE),
    "sentence-transformers/all-MiniLM-L6-v2": (384, models.Distance.COSINE),
    "BAAI/bge-small-en": (384, models.Distance.COSINE),
    "BAAI/bge-small-en-v1.5": (384, models.Distance.COSINE),
    "BAAI/bge-base-en-v1.5": (768, models.Distance.COSINE),
    "intfloat/multilingual-e5-large": (1024, models.Distance.COSINE),
}
```

In principle, Qdrant is compatible with embeddings of all sorts of models. And DSPy seems to be at least partially compatible with OpenAI embeddings, among others, but apparently not for retrieval.

Is there a particular reason not to allow passing a custom model to the Qdrant Client so it can use it for embedding queries?
Or is that something anyone other than me would be interested in?

**Comment by fronx** [comment]
It looks like there might be a workaround:

- Don't use `Retrieve#retrieve`, because it calls `QdrantClient(QdrantFastembedMixin)#query_batch`, which imposes the limit on embedding models.
- Instead, call `QdrantClient#search` directly like so:

```python
encoded_query = retriever.encode(question).tolist()  # generate embeddings for the question

result = client.search(
    collection_name=collection_name,
    query_vector=encoded_query,
    limit=top_k,
)
```

Is that the recommended way?

**Comment by okhat** [comment]
Qdrant in DSPy is (currently) just a shallow tool, so there's no recommended way per se to use. Whatever works and is clean is fine! (We mainly care about how you use the LM.)

**Comment by Anush008** [comment]
Hey @fronx. Since Qdrant is agnostic to embeddings, it provides a client-side way to generate them easily, which is the integration with FastEmbed.
The Qdrant-Dspy integration uses the FastEmbed methods to enable easy query of the docs.
So you're right in using `QdrantClient#search` when using a different model. Do note the structure of the payload when parsing the result.

**Comment by satyaloka93** [comment]
@fronx Did you get the DSpy Qdrant integration working with search? If so, do you have an example? Building my vector db with Haystack and would love to integrate DSpy.

**Comment by Anush008** [comment]
@satyaloka93, to use the DSpy Qdrant integration for search, you'll have to add the docs to Qdrant using the `add()` method as shown here.

https://github.com/qdrant/qdrant-client?tab=readme-ov-file#fast-embeddings--simpler-api
