### ISSUE TITLE
[Request] - Adding functionality of other commercial LLMs ?

### ISSUE THREAD

**Issue by yash-srivastava19** [stanfordnlp/dspy#273]
Apart from the commercial LLMs that are available in the module, are you guys working on introducing other models such as Claude, Bard or similar. If that's something on the pipeline, I would like to contribute.

**Comment by okhat** [comment]
Hey Yash! We want to add support for LangChain LLMs out of the box, so you can import any of their LLMs and use them in DSPy. We are just starting to look into what’s needed for that

**Comment by yash-srivastava19** [comment]
Sure, if there's something where I can be of some utility, hit me up.

**Comment by ukituki** [comment]
Adding support for more llms, both commercial and open source, can be handled either on case by case basis or in a more scalable way with a good abstraction. I'm not sure about the downstream implications but perhaps the inspiration from llama_index may be helpful (https://docs.llamaindex.ai/en/stable/module_guides/models/llms/usage_custom.html). Btw, it also supports Langchain llms

It'd be fantastic if we could use their llm abstractions, like that:

`from langchain.llms import OpenAI
from llama_index.llms import LangChainLLM

model = "gpt-3.5-turbo"
llm_llamaindex = LangChainLLM(llm=OpenAI())
llm_llamindex = OpenAI(model=model)
# resp = llm_llamaindex.complete("what is colBERT?")
# print(resp)

# from llama_index.llms import TogetherLLM

# model = "meta-llama/Llama-2-70b-chat-hf"
# llm_llamaindex = TogetherLLM(
#     model=model, api_key= os.getenv("TOGETHERAI_API_KEY"),
# )
# resp = llm_llamaindex.complete("what is colBERT?")
# print(resp)

dspy.settings.configure(lm=llm_llamaindex)`

**Comment by yash-srivastava19** [comment]
> Adding support for more llms, both commercial and open source, can be handled either on case by case basis or in a more scalable way with a good abstraction. I'm not sure about the downstream implications but perhaps the inspiration from llama_index's ServiceContext may be helpful (https://docs.llamaindex.ai/en/stable/module_guides/models/llms/usage_custom.html). Btw, it also supports Langchain llms
> 
> It'd be fantastic if we could use their llm abstractions, like that:
> 
> Langchain llm:
> 
> ```
> from langchain.llms import OpenAI
> from llama_index.llms import LangChainLLM
> 
> model = "gpt-3.5-turbo"
> llm_llamaindex = LangChainLLM(llm=OpenAI())
> resp = llm_llamaindex.complete("what is colBERT?")
> print(resp)
> 
> dspy.settings.configure(lm=llm_llamaindex)
> ```
> 
> Llama2 via TogehterAI:
> 
> ```
> from llama_index.llms import TogetherLLM
> 
> model = "meta-llama/Llama-2-70b-chat-hf"
> llm_llamaindex = TogetherLLM(
>      model=model, api_key= os.getenv("TOGETHERAI_API_KEY"),
>  )
> resp = llm_llamaindex.complete("what is colBERT?")
> print(resp)
> dspy.settings.configure(lm=llm_llamaindex)
> ```

Good abstractions, as that of Langchain would be really good for scaling. I will read through the `ServiceContext`  and then we can we see how to take it from there. If you have any suggestions, or want to work together on this, we can do that !

**Comment by stillmatic** [comment]
Many commercial providers work out of the box with the OpenAI library though. For example:

```
mixtral = dspy.OpenAI(
    model="mistralai/Mixtral-8x7B-Instruct-v0.1",
    max_tokens=250,
    model_type="chat",
    api_key=os.environ["TOGETHER_API_KEY"],
    api_base="https://api.together.xyz/v1",
)

dspy.settings.configure(lm=mixtral)
```

**Comment by psykhi** [comment]
Sorry if I'm misunderstanding but does adding support for other LLMs mean supporting chat APIs? (referring to [this issue](https://github.com/stanfordnlp/dspy/issues/243#issuecomment-1902394686)
Because at the moment the way prompts are built is very much tailored for instruct models.

**Comment by okhat** [comment]
Hey @psykhi , I think these two issues are separate. I left some comments in the other issue.

**Comment by yash-srivastava19** [comment]
Any PR that is working on this issue?

**Comment by aretrace** [comment]
Perhaps [litellm](https://github.com/BerriAI/litellm) could be an avenue to explore

**Comment by rolandtannous** [comment]
yes definitely support for Anthropic Claude and hopefully a direct integration (ie don't mix in langchain or any other framework)

**Comment by aretrace** [comment]
[litellm](https://github.com/BerriAI/litellm) could be a useful avenue for LLM integrations

**Comment by TweedBeetle** [comment]
I would also love anthropic support!

**Comment by AyushmunotSG18** [comment]
@okhat, has support for the anthropic models been added to DSPy? I thought it was added, but I was not able to find it.
