### ISSUE TITLE
HFClientTGI does not work anymore in skycamp2023.ipynb

### ISSUE THREAD

**Issue by jeromemassot** [stanfordnlp/dspy#275]
Hi DSPy team,

it seems that the following code is not working anymore. May be due to some change on the HF side.
Any idea of an update of the notebook to have it working fine?
Thanks.
Jerome

`llama = dspy.HFClientTGI(model="meta-llama/Llama-2-13b-chat-hf", port=[7140, 7141, 7142, 7143], max_tokens=150)`

**Comment by okhat** [comment]
Ah just make sure you pass the actual port(s) you selected. 7140 etc are probably not your ports

**Comment by jeromemassot** [comment]
Hi,
sorry but I do not understand the fix that you proposed. On Colab or on the HF side for the ports ?
Thx
Jerome

**Comment by jeromemassot** [comment]
The error message is : 
ConnectionError: HTTPConnectionPool(host='future-hgx-1', port=7140): Max retries exceeded with url: /generate (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f70ab12be50>: Failed to resolve 'future-hgx-1' ([Errno -2] Name or service not known)"))

**Comment by arnavsinghvi11** [comment]
Hi @jeromemassot,

You'll want to override these default kwargs in your call of HFClientTGI: port=[**{your port(s)}**], url=**'your hosted TGI url'**

`dspy.HFClientTGI(model="meta-llama/Llama-2-13b-chat-hf", port=[{your port(s)}], url='your hosted TGI url',  max_tokens=150)`

Let us know if this helps!

**Comment by jeromemassot** [comment]
Thanks for your comment. Ok so if I understand correctly, I can deploy my endpoint on HF and update the parameters accordingly. Am I right?

**Comment by arnavsinghvi11** [comment]
Yes that's correct!

**Comment by jeromemassot** [comment]
Explanations clarify the notebook code. I think that we can close the issue. Thanks.

**Comment by tom-doerr** [comment]
Had the same issue, might be good to explain it in the notebook
