### ISSUE TITLE
Using PEFT models/Adapters

### ISSUE THREAD

**Issue by seanbenhur** [stanfordnlp/dspy#286]
Hi, is there a way to use trained Adapters?, i have trained an adapter model and servind it via [lorax](https://github.com/predibase/lorax). I would like to know is there any default support for using adapters

**Comment by okhat** [comment]
Hi @seanbenhur ! Do you basically have a new LM (trained with adapters etc) and you want to prompt it with DSPy? Or what are you trying to achieve?

**Comment by seanbenhur** [comment]
Yes I basically have a new LM trained with adapters and I am serving the LM with [lorax](https://github.com/predibase/lorax) now I would like to use Dspy along with it.

**Comment by okhat** [comment]
I think this is just a matter of being able to load your model and then have a client to prompt it. DSPy isn't very involved there, it just treats the frozen LMs as a client (prompt -> completions).

**Comment by okhat** [comment]
Maybe it sounds like you want to add a lorax client basically

**Comment by seanbenhur** [comment]
Yes, is there a recommended way to do?
