### ISSUE TITLE
HFClientTGI does not seem compatible with HF Protected endpoint

### ISSUE THREAD

**Issue by jeromemassot** [stanfordnlp/dspy#287]
Hi DSPy team,

I continue to fight with the HFClientTGI object. I have created a protected endpoint and I try to set up the client for using it.

It seems in the code that the HFClientTGI cannot handle the Authorization token as it creates its headers JSON object passed during the request call.

With my modest code understanding, I cannot see how today I can use the client with a protected endpoint. But I guess that you have a solution for me :)

Thanks
Best regards
Jerome

**Comment by okhat** [comment]
Hey @jeromemassot!

Yes, we don't have any handling for TGI protected endpoints. I never heard of them until now.

But let's look into this. The function that sends requests to TGI is:

```python
@CacheMemory.cache(ignore=['arg'])
def send_hftgi_request_v01(arg, url, ports, **kwargs):
    return requests.post(arg, **kwargs)
```

It's [here](https://github.com/stanfordnlp/dspy/blob/072b20e5daca85a19ccf4db89f4b3994f516d952/dsp/modules/hf_client.py#L94). Do you have some notes on what a protected endpoint is different for? Maybe we just need to add one keyword argument for the Authorization token in the request?

**Comment by jeromemassot** [comment]
Hi Omar,
I think that the only modification to the current HFClientTGI is to include the authorization token in the headers.
Something like:

`
 def __init__(self, model, port, url="http://future-hgx-1", http_request_kwargs=None, **kwargs):
        super().__init__(model=model, is_client=True)

        self.url = url
        self.ports = port if isinstance(port, list) else [port]
        self.http_request_kwargs = http_request_kwargs or {}

        self.headers = {
            "Content-Type": "application/json",
            "Authorization": <TOKEN>
        }

        self.kwargs = {
            "temperature": 0.01,
            "max_tokens": 75,
            "top_p": 0.97,
            "n": 1,
            "stop": ["\n", "\n\n"],
            **kwargs,
        }
`
I will try it on my side... and let you know about my success or failure :)

Best regards

Jerome

**Comment by jeromemassot** [comment]
Hi Omar,

ok, so I have investigated and found a way to connect to a protected HF endpoint.
I have also found some potential deprecated code in the hf_client.py module.
In particular, the use of ports seems no longer needed and in my case ends with a TimeOut.
Some unused variables in the send_hftgi_request_v01_wrapped and send_hftgi_request_v01 too.

I attach here the update code here:

`
class HFClientTGI(HFModel):
    def __init__(self, model, port, url=None, token=None, http_request_kwargs=None, **kwargs):
        super().__init__(model=model, is_client=True)

        self.url = url
        self.ports = port if isinstance(port, list) else [port]
        self.http_request_kwargs = http_request_kwargs or {}

        self.headers = {
            "Accept" : "application/json",
            "Content-Type": "application/json"
        }

        if token:
            self.headers["Authorization"] = f"Bearer {token}"

        self.kwargs = {
            "temperature": 0.01,
            "max_tokens": 75,
            "top_p": 0.97,
            "n": 1,
            "stop": ["\n", "\n\n"],
            **kwargs,
        }

        #print(self.kwargs)

    def _generate(self, prompt, **kwargs):
        kwargs = {**self.kwargs, **kwargs}

        payload = {
            "inputs": prompt,
            "parameters": {
                "do_sample": kwargs["n"] > 1,
                "best_of": kwargs["n"],
                "details": kwargs["n"] > 1,
                # "max_new_tokens": kwargs.get('max_tokens', kwargs.get('max_new_tokens', 75)),
                # "stop": ["\n", "\n\n"],
                **kwargs,
            }
        }

        payload["parameters"] = openai_to_hf(**payload["parameters"])

        payload["parameters"]["temperature"] = max(
            0.1, payload["parameters"]["temperature"]
        )

        # print(payload['parameters'])

        response = send_hftgi_request_v01_wrapped(
            f"{self.url}/generate",
            #url=self.url,
            #ports=tuple(self.ports),
            json=payload,
            headers=self.headers,
            **self.http_request_kwargs,
        )

        try:
            json_response = response.json()
            
            # completions = json_response["generated_text"]

            completions = [json_response["generated_text"]]

            if (
                "details" in json_response
                and "best_of_sequences" in json_response["details"]
            ):
                completions += [
                    x["generated_text"]
                    for x in json_response["details"]["best_of_sequences"]
                ]

            response = {"prompt": prompt, "choices": [{"text": c} for c in completions]}
            return response
        except Exception as e:
            print("Failed to parse JSON response:", response.text)
            raise Exception("Received invalid JSON response from server")


@CacheMemory.cache(ignore=['arg'])
def send_hftgi_request_v01(arg, **kwargs):
    return requests.post(arg, **kwargs)

# @functools.lru_cache(maxsize=None if cache_turn_on else 0)
@NotebookCacheMemory.cache(ignore=['arg'])
def send_hftgi_request_v01_wrapped(arg, **kwargs):
    return send_hftgi_request_v01(arg, **kwargs)
`

I have run the DSPy local models & custom training data.ipynb with this updated code and a protected HF endpoint running LLama2 and it is ok after I increased the maximum number of tokens.

Best regards

Jerome

**Comment by okhat** [comment]
Ah that’s really helpful @jeromemassot !

Do you want to make this a pull request?

**Comment by jeromemassot** [comment]
Ok. In which branch do you want me to request the pull?
Sorry if my question looks silly but I am not very fluent with GitHub process :)
Best regards
Jerome

**Comment by jeromemassot** [comment]
```
class HFClientTGI(HFModel):
    def __init__(self, model, port=None, url=None, token=None, http_request_kwargs=None, **kwargs):
        super().__init__(model=model, is_client=True)

        self.url = url
        self.ports = port if isinstance(port, list) else [port]
        self.http_request_kwargs = http_request_kwargs or {}

        self.headers = {
            "Accept" : "application/json",
            "Content-Type": "application/json"
        }

        if token:
            self.headers["Authorization"] = f"Bearer {token}"

        self.kwargs = {
            "temperature": 0.01,
            "max_tokens": 75,
            "top_p": 0.97,
            "n": 1,
            "stop": ["\n", "\n\n"],
            **kwargs,
        }

        #print(self.kwargs)

    def _generate(self, prompt, **kwargs):
        kwargs = {**self.kwargs, **kwargs}

        payload = {
            "inputs": prompt,
            "parameters": {
                "do_sample": kwargs["n"] > 1,
                "best_of": kwargs["n"],
                "details": kwargs["n"] > 1,
                # "max_new_tokens": kwargs.get('max_tokens', kwargs.get('max_new_tokens', 75)),
                # "stop": ["\n", "\n\n"],
                **kwargs,
            }
        }

        payload["parameters"] = openai_to_hf(**payload["parameters"])

        payload["parameters"]["temperature"] = max(
            0.1, payload["parameters"]["temperature"]
        )

        # print(payload['parameters'])

        response = send_hftgi_request_v01_wrapped(
            f"{self.url}/generate",
            json=payload,
            headers=self.headers,
            **self.http_request_kwargs,
        )

        try:
            json_response = response.json()
            
            # completions = json_response["generated_text"]

            completions = [json_response["generated_text"]]

            if (
                "details" in json_response
                and "best_of_sequences" in json_response["details"]
            ):
                completions += [
                    x["generated_text"]
                    for x in json_response["details"]["best_of_sequences"]
                ]

            response = {"prompt": prompt, "choices": [{"text": c} for c in completions]}
            return response
        except Exception as e:
            print("Failed to parse JSON response:", response.text)
            raise Exception("Received invalid JSON response from server")


@CacheMemory.cache(ignore=['arg'])
def send_hftgi_request_v01(arg, **kwargs):
    return requests.post(arg, **kwargs)

# @functools.lru_cache(maxsize=None if cache_turn_on else 0)
@NotebookCacheMemory.cache(ignore=['arg'])
def send_hftgi_request_v01_wrapped(arg, **kwargs):
    return send_hftgi_request_v01(arg, **kwargs)

```

Tested with both Public and Protected HF endpoints. Worked fine.

**Comment by okhat** [comment]
Branch main. Thanks so much!
