### ISSUE TITLE
Bedrock support

### ISSUE THREAD

**Issue by JamesScharf** [stanfordnlp/dspy#300]
Adding support for AWS Bedrock and potentially AWS sagemaker.

**Comment by JamesScharf** [comment]
I have a branch with support for AWS Bedrock and logging utilities for the Bedrock-base LMs--Can I make a PR?
I also added support for a general AWS LM class so Sagemaker can be supported as well in the future.

**Comment by ndronen** [comment]
I'm not with the project, but I'd suggest just making the PR!

**Comment by ldong87** [comment]
I'd like to see such a PR too!

**Comment by JamesScharf** [comment]
Relevant PR: https://github.com/stanfordnlp/dspy/pull/330
Thanks!

**Comment by okhat** [comment]
Thank you @JamesScharf ! Left some comments there.
