### ISSUE TITLE
BootstrapFewShot compile fails with 'numpy.float64' object has no attribute 'split' Error

### ISSUE THREAD

**Issue by geemi725** [stanfordnlp/dspy#311]
I am working with a pipeline where I'm using my own retriever class instead of the dspy retrievers. The goal is to develop a RAG model to extract data from PDFs. However when I try to compile the teleprompter it fails. I am following the [intro.ipynb](https://colab.research.google.com/github/stanfordnlp/dspy/blob/main/intro.ipynb) notebook. Please help?

```
class RAG(dspy.Module):
    def __init__(self, k=3, create_db=True, chunk_size=200,
                 vectdb_path=None):
        self.k = k
        self.create_db = create_db
        self.vectdb_path = vectdb_path
        self.chunk_size = chunk_size

        self.retrieve = TextRetriever()

        self.generate_answer = dspy.ChainOfThought(GenerateAnswer)
    
    def forward(self, question,filename):
        context = self.retrieve.forward(query=question,filename=filename)
        
        prediction = self.generate_answer(context=context, question=question,
                                          filename=filename)
        print(prediction.answer)
        
        return dspy.Prediction(context=context, answer=prediction.answer)
    

def validate_context_and_answer(example, pred):
    answer_EM = dspy.evaluate.answer_exact_match(example, pred)
    return answer_EM

teleprompter = BootstrapFewShot(metric=validate_context_and_answer, max_rounds=2)

compiled_rag = teleprompter.compile(RAG(), trainset=trainset)
```

ERROR:
![Screenshot from 2024-01-31 10-02-14](https://github.com/stanfordnlp/dspy/assets/49410838/118824f1-78e7-4498-9ee7-ca5ca71ce6eb)
![Screenshot from 2024-01-31 10-03-13](https://github.com/stanfordnlp/dspy/assets/49410838/fbeb749d-2b6f-4b60-a879-7677253884d4)
![Screenshot from 2024-01-31 10-04-28](https://github.com/stanfordnlp/dspy/assets/49410838/cf2df696-44be-4e59-a268-f95dea1a686b)
![Screenshot from 2024-01-31 10-05-08](https://github.com/stanfordnlp/dspy/assets/49410838/c1a92370-c27e-4181-9d54-46bbbac44184)

**Comment by arnavsinghvi11** [comment]
Hi @geemi725 ,

Thanks for the question! This error could be likely because your specified `filename` is of type `'numpy.float64'` while it should be in fact `str` type. Could you confirm your input field values and types?
