### ISSUE TITLE
Any potential ideas on what contributions/improvements can be made?

### ISSUE THREAD

**Issue by vaventt** [stanfordnlp/dspy#324]
Hi there! I decided to open an issue, because didn't know where can I find a better place to chat with DSPy developers. I have heard about DSPy two month ago and really liked the idea about automatic prompt engineering even though still hadn't an opportunity to learn about all DSPy modules and capabilities. I'm currently pursuing my Master's degree in Ukraine and looking for some interesting topics to make it's my master thesis and protect it. 

So my main question is that does someone have any ideas with their more in-depth knowledge about DSPy what can be done/imporved in my next 9 month of writing and coding my master thesis? For example I have seen Chain-of-Thought module in DSPy, is building Graph-of-Thought module a good idea? Or maybe try to build another module or several of them or improve somehow on existing ones? If my code would be enough quality than I could also create a PR with my work that I have done and adding it to the DSPy repo. I would be very grateful for some ideas, propositions, views related to this.

**Comment by okhat** [comment]
Hey @vaventt ! Thank you for opening this issue. Yes there are many features and experiments that we need help with. Graph of Thoughts is suitable but I’m not a fan currently because it tends to be a very expensive approach? That’s my uneducated impression. Supporting complex agents and optimizing them is one direction. Another direction is AutoDSPy, where it can create examples and metrics for any program automatically so people can optimize without having to get any data. What are your current thoughts?

**Comment by vaventt** [comment]
@okhat Yes, I agree with you about the Graph of Thought substantial drawback, AutoDSPy sounds interesting actually and about supporting complex agents, you mean agents like what LangChain has module agents, but in case of DSPy there will be no hardcoded prompts for the agents to do different actions like trigger Google API search or other tools?

**Comment by okhat** [comment]
Another interesting direction: #314

**Comment by JamesScharf** [comment]
@okhat 
I'd like to extend DSPy to support other kinds of agents. There seem to be a bunch of new methods out there--do you have any thoughts on what might be best to pursue?

**Comment by okhat** [comment]
@JamesScharf awesome that’s a fun direction, what’s an agent, if you found interesting recently

**Comment by JamesScharf** [comment]
[SayCan](https://arxiv.org/pdf/2204.01691.pdf) is quite neat. I think it might require adding some additional probability utilities to DSPy though.

**Comment by okhat** [comment]
Maybe something text-only for a start?
