### ISSUE TITLE
Docstrings

### ISSUE THREAD

**Issue by thomasahle** [stanfordnlp/dspy#328]
Having doc-strings on methods and classes would be very helpful.
E.g., I'm currently trying to figure out how the `parse_structure`, `attach` and `add_field` methods on `Signature` work.
But they are defined quite generally like
```
def attach(self, **kwargs):
      ...
```
so it's hard to even read anything from the type signature.

I know writing documentation is a chore, and particularly in a rapidly evolving codebase like this.
Just thought I'd drop this in the Issues to gather the interest from other people in the same situation.

**Comment by INF800** [comment]
+1

**Comment by okhat** [comment]
Yeah this is is true, we do need those ASAP. I think I see the order like this:

1. Complete these docs: https://dspy-docs.vercel.app/
2. Do a bunch of refactoring that's pretty urgent, especially around Signatures, LMs, and Modules
3. New code should have docstrings
