### ISSUE TITLE
Advanced Retrieval techniques

### ISSUE THREAD

**Issue by rolandtannous** [stanfordnlp/dspy#334]
Greetings folks,

I've been watching some of the videos on dspy, and I couldn't figure out an answer to the following:
Does Dspy allow to customize it's retrieve method if one wishes to introduce advanced retrieval techniques such as sentence-window retrieval or auto-merging retrieval. Can't seem to figure it out.

Thank you.

**Comment by okhat** [comment]
DSPy is a bit more of "bring your own program" framework.

So yes you can customize these fully, but in your own logic/code. The `forward` method of your module can do anything you want. DSPy is just optimizing the LM calls for you.

**Comment by rolandtannous** [comment]
oh makes perfect sense . I am still trying to wrap my head around it as it's a new paradigm. 
watched your presentation a couple of months ago. just recently got the time to try it out. Thank you !

**Comment by BlueKiji77** [comment]
Hello, still on the same subject; I assume we could implement advanced retrieval techniques from frameworks like llamaindex (Hybrid Search, Fusion...)
