### ISSUE TITLE
[feat] Adding toolkits to llms

### ISSUE THREAD

**Issue by AniLeo-01** [stanfordnlp/dspy#336]
Is there any future provision for adding toolkits to DSPy, like calendar, calculators, google search, etc?

**Comment by okhat** [comment]
Not in the short term; you can just use these tools. They don’t need to be part of dspy.

does that make sense? In dspy there’s no need that tools are integrated in the library itself

**Comment by AniLeo-01** [comment]
Oh I see, thanks!
