### ISSUE TITLE
Updating the DSPy program doesn't always trigger re-compilation on the next run

### ISSUE THREAD

**Issue by bjsi** [stanfordnlp/dspy#337]
I noticed that if I update things like `dspy.Suggest`s it doesn't seem to trigger re-compilation. It just uses the cached output from the last execution.

**Comment by okhat** [comment]
Are you using the latest main branch? Or pypi?

**Comment by bjsi** [comment]
Ah yeah I'm using pypi. I'll switch to using the git repo 👍

**Comment by okhat** [comment]
In general assertions are (for ~1 week) still fairly experimental. We're planning a big-ish release next week so with that it'll probably be possible to have things be a bit more smooth/ergonomic.

**Comment by okhat** [comment]
I assume this is resolved but let us know if not
