### ISSUE TITLE
program with knn and annotate requires too many tokens

### ISSUE THREAD

**Issue by ylchin** [stanfordnlp/dspy#34]
hi, I would like to ask how do you keep to the token size for program 5 in intro.ipynb because when i try to run it with my own questions it returns
`InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 456171 tokens. Please reduce the length of the messages.`

**Comment by ylchin** [comment]
yes, it's using turbo, but even when i was running text-davinci-002, the token window often exceeded

**Comment by okhat** [comment]
I see. Before we dig into that, why/how is it 456,00 tokens? I'd understand if it was 5,000 for example. Are you able to share more information? How many demonstrations are you using?

**Comment by ylchin** [comment]
i'm using 5 demonstrations

**Comment by ylchin** [comment]
even when I reduced the number of demos to 1 
`x.demos = dsp.annotate(multihop_attempt)(demos, k=1, return_all=True)`
it still exceeds the count 
`InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 456675 tokens. Please reduce the length of the messages.`

**Comment by okhat** [comment]
Can you return_all = False?

**Comment by ylchin** [comment]
ive tried and the same thing still returns

**Comment by okhat** [comment]
Okay… can you print the prompt inside the generate function? This is a bit absurd, with  450,000 tokens! That’s like 200 times more than it normally is

**Comment by ylchin** [comment]
I'm not sure why but after the first retrieval of passages for the annotation of the demos after sampling, the program passes all the questions and answers of the entire training set to gpt

**Comment by ylchin** [comment]
in multihop_demonstrate, i have changed it to 
'x.demos = dsp.annotate(multihop_attempt)(demos, k=1, return_all=False)
assert len(x.demos) == 1, "Output length is not 1'
but the same error is appearing
