### ISSUE TITLE
Evaluate should take multiple metrics

### ISSUE THREAD

**Issue by thomasahle** [stanfordnlp/dspy#344]
Right now `Evaluate(...)` only take one metric, but often we have multiple different scores we want to test at the same time.
Like "accuracy" and "gold_passages_retrieved" and "q/s" etc.

While it's not obvious how to support multiple metrics for compilation, it should be easier to do for evaluation.

**Comment by thomasahle** [comment]
I'm happy to send some PRs.
Right now I'm just a bull in a china shop hitting random obstacles, and creating issue reports to keep track of them.
I don't think this one is super important to fix right now, but I just wanted to register it.
If I'm creating too much spam on the issue tracker, I'm also happy to just keep a personal list of things to look into down the line :-)

**Comment by bhuvana-ak** [comment]
hello there, I am also looking for something similar to this.. any recent updates?

**Comment by dhanishetty** [comment]
metric= evaluate.combine(["accuracy", "recall", "precision", "f1"])

**Comment by psimm** [comment]
Would be great to have documentation of this here: https://dspy.ai/learn/evaluation/metrics/

**Comment by Goooyi** [comment]
Can someone explain why is this marked as closed? I haven't found mulitple metrics for eval in the codebase?
