### ISSUE TITLE
add system prompt design to GPT model

### ISSUE THREAD

**Issue by xdite** [stanfordnlp/dspy#355]
It seems missing a key feature: "system prompt"
"system prompt" impacts gpt-model significantly
at least let as can put in config or somewhere else?

**Comment by okhat** [comment]
Good point. We need to think harder about chat model support. We may put the instructions in the system prompt, or something else.

Out of curiosity, what would you like to put in the system prompt?

**Comment by xdite** [comment]
> Good point. We need to think harder about chat model support. We may put the instructions in the system prompt, or something else.
> 
> Out of curiosity, what would you like to put in the system prompt?

My best scenarios are almost:

Packing what I want GPT to do into a Prompt Class structure, similar to object-oriented programming, but with a very programmatic way of writing prompts.

And putting the data and context in the User Prompt.

`system prompt = method`, `user prompt = user input data`

GPT API will be significantly work that way.It is much stronger than putting everything in the user prompt.

**Comment by jmaushake** [comment]
It may not just be the specific LM, but also the native language. I work at S&N (Germany)

**Comment by adam-simple** [comment]
+1. Have experimented with guiding behavior in system prompt as well as in user prompt. For certain behaviors, putting them in the system prompt works, whereas shoving it in the user prompt results in "I'm sorry, I cannot assist.." etc.

DSPy is unusable for building complex gpt-based chatting products at the moment, imo. Will explore other models or other tools in the meantime

**Comment by xdite** [comment]
Implemented. #618
