### ISSUE TITLE
Weaviate RM should NOT assume that "content" contains the text of the passage

### ISSUE THREAD

**Issue by gopidon** [stanfordnlp/dspy#359]
Hi @CShorten 

File: dspy.retrieve.weaviate_rm, line 74

Give the flexibility to pass the the name of the text field as a parameter along with the collection name. Something like below:

WeaviateRM(
    weaviate_collection_name= "<collection_name>", 
    weaviate_collection_text_field="<field-name>",
    weaviate_client=weaviate.Client("<weaviate-url>")
)

**Comment by CShorten** [comment]
Hey Gopi! Thanks for bringing this up, this will resolve it! 

https://github.com/stanfordnlp/dspy/pull/360
