### ISSUE TITLE
Retrieve should enable return of "things" other than passages

### ISSUE THREAD

**Issue by gopidon** [stanfordnlp/dspy#364]
The retrieveEnsemble method focusses only on the long_text key. It ignores any other keys provided along with long_text key. I have a custom retriever that returns some metadata along with long_text. retrieveEnsemble should "pass through" this metadata all the way till self.retrieve(question). I mean self.retrieve(question) should return an object that has both passages and metadata keys. While passages can be used to provide the context to the LLM, metadata can be used by the consumer in whichever way he wants to. 

Is there a way to achieve this other than overriding the retrieveEnsemble method?

**Comment by domci** [comment]
Just implemented this for chromaDB. Happy to also work on the other retrievers but I would need the schema of the returned search object for each of them. I don't have accounts for all these vector stores :-)
