### ISSUE TITLE
No matching distribution for Vectorstores

### ISSUE THREAD

**Issue by Dyke-F** [stanfordnlp/dspy#375]
pip install dspy-ai[qdrant]

zsh: no matches found: dspy-ai[qdrant]

pip install dspy-ai[pinecone] 
zsh: no matches found: dspy-ai[pinecone]

**Comment by bclavie** [comment]
Hey, this is a `zsh` thing. Its behaviour is to assume anything inside squared brackets is for pattern matching.

You can either escape or have the name of the package inside inverted commas, e.g.:

```python
pip install "dspy-ai[pinecone]
```
or
```python
pip install dspy-ai\[qdrant\]
```

**Comment by Dyke-F** [comment]
thank you so much!
