### ISSUE TITLE
Type annotations

### ISSUE THREAD

**Issue by bencrouse** [stanfordnlp/dspy#382]
I really like the idea of this library - super cool, I appreciate the effort you've put into making it available.

I'm thinking about adoption into my current app/workflow. Related to the `deployment` tag issues and general software engineering practices, I'm wondering if the omission of type annotations is a proactive choice or more a consequence of this being a young project.

Is this something the author(s) have an opinion on and/or open to in the future? Thanks!

**Comment by KCaverly** [comment]
This would help me broadly reason about the application a bit better as well.
If the team is keen, I am happy to help out.

Would it make sense to get started on something like this, before the refactor though?

**Comment by bencrouse** [comment]
I should've noted I'm also happy to help, wasn't aware of "the refactor" though!
