### ISSUE TITLE
cant use any model

### ISSUE THREAD

**Issue by yxs8495** [stanfordnlp/dspy#395]
For the models in the intro.ipynb I get:

AttributeError: module 'dspy' has no attribute 'OpenAI'

**Comment by okhat** [comment]
I'm not able to reproduce this problem

**Comment by leoschwarz** [comment]
Did you by any chance `pip install dspy` instead of `pip install dspy-ai`, which is another package?

**Comment by yxs8495** [comment]
Thanks for responding. I deleted the virtual environment and started over again. It works. Again thanks for responding. Have a great one!

**Comment by yxs8495** [comment]
I simply deleted the poetry project and started again.

**Comment by cugxxspotato** [comment]
can you show the version you use? I get this trouble too. but i can't come over it through your way
