### ISSUE TITLE
How to use a local finetuned model

### ISSUE THREAD

**Issue by yxs8495** [stanfordnlp/dspy#414]
I have a model that was downloaded from hugging face and finetuned. How do I choose it as my llm? thanks

**Comment by smwitkowski** [comment]
Have a look at this example notebook: [**Local Models & Custom Datasets**](https://colab.research.google.com/github/stanfordnlp/dspy/blob/main/skycamp2023.ipynb)

**Comment by IAmLior** [comment]
There is an error while trying to load this Colab notebook, could you please provide an updated link?

**Comment by arnavsinghvi11** [comment]
@IAmLior https://github.com/stanfordnlp/dspy/blob/62d42597fe7ba7acbe646e8a7c93197849a5d92d/examples/outdated_v2.4_examples/skycamp2023.ipynb
