### ISSUE TITLE
Ollama withdspy.ChainOfThought: slower after some initial runs?

### ISSUE THREAD

**Issue by excubo-jg** [stanfordnlp/dspy#433]
I am running attached py as standalone which loads the attached data file. Execution should be very fast as there should be no training but isn't. An earlier version of the code runs without issues but the attached when processing the 5th case suddenly seems to switch to training. From what I see in the debugger this happens in the with-loop line 69 which calls dspy.ChainOfThought

[PIA_test.txt](https://github.com/stanfordnlp/dspy/files/14365796/PIA_test.txt)
[score.zip](https://github.com/stanfordnlp/dspy/files/14365810/score.zip)

**Comment by okhat** [comment]
Sorry I don’t understand. What model are you using? If you rerun again, does the issue to away? OpenAI has been slow and unstable today

**Comment by excubo-jg** [comment]
Apologies for being imprecise. This is using phi-2/Ollama (line #4 model=phi)
No this is reproducible, changing the data file only changes when the bug hits.

**Comment by okhat** [comment]
Awesome! And the error is where? Feel free to post code here or stacktrace of ctrl-c 

What do you mean by it switches to training. That seems unlikely to be something that happens

**Comment by excubo-jg** [comment]
Full Code is in the zip-file I included in the first post. Fwiw line 69ff. is were the problem happens. 

Processing time goes from 150**it/s** down to 30**s/it** on my machine... So it does not crash but runs very slowly.

**Comment by okhat** [comment]
What is num_threads? Maybe the servwr js overwhelmed 

also when is it 150/s? At the start?

**Comment by excubo-jg** [comment]
This is running on my local machine. No server involved.
Yes the first runs are at that speed (as per the Average Metric line) and then it falls off a cliff.

**Comment by okhat** [comment]
Yes ollama is the server and basically gets overwhelmed. What is your num_threads ?

**Comment by excubo-jg** [comment]
Ah thanks for the clarification. num_threads = 1

**Comment by okhat** [comment]
Got it. It’s possible your laptop begins to overheat or just reduce power.

this doesn’t seem crazy — do you have another reason to believe there are issues? 30 iters per sec isn’t bad I think

**Comment by excubo-jg** [comment]
It goes down to 30 and more seconds per it...

**Comment by excubo-jg** [comment]
The laptop does throttle down under heavy load but not that much. Also, the error hits before the fan begins to spin up.

**Comment by excubo-jg** [comment]
I have replaced phi with gemma:2b and am experiencing the same issue - right from the first run. The delay happens first in line #73 " detail = dspy.ChainOfThought(Assess)(context=context, assessed_question=detail, assessed_answer=predicted_answer)"

Attached is the update code which uses gemma:2b (and also the data file which get processed):
[py file.zip](https://github.com/stanfordnlp/dspy/files/14371798/py.file.zip)
[PIA_test.txt](https://github.com/stanfordnlp/dspy/files/14371803/PIA_test.txt)

**Comment by excubo-jg** [comment]
closing this - might in related to (mis)using openai and not Ollamalocal

**Comment by paulacanva** [comment]
I'm doing something similar, using GPT-4, and using `dspy` vs "raw" call to OpenAi is extremely slow. With 10k points, I get a result with OpenAI in 30 minutes. With `dspy`, it's been 1 hour and it has processed only 1/5 of the data. 

```
class Theme(dspy.Signature):
    """
    Classify user queries in following themes:
    [Restricted -- cannot share]
    """ 
    sentence = dspy.InputField()
    theme = dspy.OutputField(desc="THEME name only. No explanations.")

model = dspy.OpenAI(
        model=config.COMPLETION_CONFIG["model"],
        max_tokens=config.COMPLETION_CONFIG["max_tokens"],
    )
    dspy.settings.configure(
        lm=model, trace=[], temperature=config.COMPLETION_CONFIG["temperature"]
    )
    classify = dspy.ChainOfThought(Theme)

    df_out = df.copy()
    df_out["Theme"] = ""

    start_time = time.time()
    for i, row in tqdm(df.iterrows()):
        sentence = row["Prompt"]
        response = classify(sentence=sentence)
        extracted_theme = extract_theme(response.theme)
        logger.debug(extracted_theme)
        df_out.loc[i, "Theme"] = extracted_theme
    logger.info(f"Finished processing in {time.time() - start_time:.2f} secs")
```

Using the content of docstring with OpenAI directly is a lot faster. And I'm not even optimizing anything. Is there anything I can do to have more control? For instance, with OpenAI + standard python I use asyncio for threading.

**Comment by ArslanS1997** [comment]
@paulacanva were you able to make requests faster
