### ISSUE TITLE
Integrate vertexai

### ISSUE THREAD

**Issue by Demontego** [stanfordnlp/dspy#463]
Do you plan to integrate Google's VertexAI?
If not, I can add little by little based on this https://github.com/langchain-ai/langchain/blob/master/libs/partners/google-vertexai/langchain_google_vertexai/llms.py

**Comment by arnavsinghvi11** [comment]
@Demontego VertexAI would be great. Feel free to open a PR for it! You'll find this documentation useful for [integrating an LM within DSPy](https://dspy-docs.vercel.app/docs/deep-dive/language_model_clients/custom-lm-client) or following the format of existing LM client integrations.

**Comment by CShorten** [comment]
Hey both, would it be an idea to name this googlevertexai.py? And the LM `GoogleVertexAI`? Inspired by the azurecognitivesearch.py file, but I also see we have hf_client / hf_server.

**Comment by arnavsinghvi11** [comment]
> Hey both, would it be an idea to name this googlevertexai.py? And the LM `GoogleVertexAI`? Inspired by the azurecognitivesearch.py file, but I also see we have hf_client / hf_server.

Yeah that sounds great!

**Comment by Demontego** [comment]
Ok, I will start writing the integration bit by bit in the evenings during my free time.

**Comment by chaitanya-parsana** [comment]
This would be super helpful. @Demontego happy to help test the integration when you have a PR.

**Comment by Demontego** [comment]
https://github.com/stanfordnlp/dspy/pull/616 check please
