### ISSUE TITLE
Fix dspy chain of thought doc

### ISSUE THREAD

**Issue by adityalahiri** [stanfordnlp/dspy#475]
Seems like the hint is not required for vanilla Cot?
https://dspy-docs.vercel.app/docs/cheatsheet#dspychainofthoughtwithhint

Happy to open a PR for the fix, seems minor. Any recommended workflow for that?

**Comment by okhat** [comment]
Thank you! What are you trying to fix? Looks OK to me

**Comment by adityalahiri** [comment]
Hey!
dspy.ChainOfThought
and dspy.ChainOfThoughtwithHint
have the exact same docs!

My guess was that the former does not need the hint variable?

**Comment by adityalahiri** [comment]
We don't end up passing the hint. So it is kind of confusing for the standard CoT

**Comment by okhat** [comment]
ah got it! thanks so much @adityalahiri , fixed in the folder docs/ , but not sure how fast this will propagate to the site4
