### ISSUE TITLE
BootstrapFewShotWithRandomSearch does not produce rationales for demos

### ISSUE THREAD

**Issue by adityalahiri** [stanfordnlp/dspy#476]
I noticed that on using Cot with BootstrapFewShotWithRandomSearch, the selected or generated(?) demos in the prompt do not have reasoning, whereas the standard BootstrapFewShot has reasoning in all its demos inside the prompt. Is this intended? Having rationale for examples automatically is kind of sweet, and I hate to lose it when using the better bootstrapping procedure.

**Comment by okhat** [comment]
Some will have and some may not! It depends on what performs best. Can you check again int the produced prompt?

**Comment by okhat** [comment]
Basically the title is not correct in general, BootstrapFewShotWithRandomSearch does produce rationales for demos, but not sure what you saw in this specific case
