### ISSUE TITLE
Evaluate.py to return more information

### ISSUE THREAD

**Issue by excubo-jg** [stanfordnlp/dspy#477]
I am wondering if the returns in evaluate.py __code__

```
        if return_all_scores and return_outputs:
            return round(100 * ncorrect / ntotal, 2), results
        elif return_all_scores:
            return round(100 * ncorrect / ntotal, 2), [score for *_, score in reordered_devset]
        elif return_outputs:
            return round(100 * ncorrect / ntotal, 2), results

        return round(100 * ncorrect / ntotal, 2)
```
could be changed so that
 ```
       if return_all_scores and return_outputs:
            return round(100 * ncorrect / ntotal, 2), results, [score for *_, score in reordered_devset]
        ....
```
returns all information at once

**Comment by excubo-jg** [comment]
Currently, two subsequent calls are necessary to extract the information but they don't extract information from the same base. This is confusing as there are instances when correct answers get scored as wrong and vice versa and even the total score might differ...
`total_score, results = evaluate(my_qa, return_outputs=True)
total_score, scores = evaluate(my_qa, return_all_scores=True)
`

**Comment by okhat** [comment]
Interesting, I didn't know that this was like that. Looks like a mini-bug to me
