### ISSUE TITLE
Load LLMs served on Databricks with DSPY

### ISSUE THREAD

**Issue by chouksep** [stanfordnlp/dspy#491]
I am trying to load language model  in dspy framework and LLM I am trying to use is the "databricks-mixtral-8x7b-instruct" served on databricks as endpoint. How I can integrate dspy with databricks language model? I looked into modules and there is a module for databricks (https://github.com/stanfordnlp/dspy/blob/main/dsp/modules/databricks.py ) but when trying to load class "Databricks", it shows dspy has no attribute "Databricks". I wanted to know how I can resolve it.

**Comment by arnavsinghvi11** [comment]
Hi @chouksep , what version of `dspy` are you using? I believe some recent updates to the library may have fixed it. Feel free to try again and see if that resolves this!
