### ISSUE TITLE
Augmented attribute error in template call

### ISSUE THREAD

**Issue by diicellman** [stanfordnlp/dspy#504]
I'm getting the same issue as in #181. Saved and loaded compiled model and on `__call__` I'm getting this error:
```bash
    ("augmented" not in demo or not demo.augmented)
AttributeError: 'dict' object has no attribute 'augmented'
```

- python 3.10
- dspy-ai = "2.3.4"

**Comment by okhat** [comment]
I believe this has been fixed on the main branch but not published to pypi yet

**Comment by diicellman** [comment]
Okay, thank you for the reply!
