### ISSUE TITLE
ollama+llama2:13b redundant output

### ISSUE THREAD

**Issue by Ren-Xin** [stanfordnlp/dspy#506]
![image](https://github.com/stanfordnlp/dspy/assets/48504366/a1d22ed8-1f6c-45be-bd85-6a9449c9efc0)
![image](https://github.com/stanfordnlp/dspy/assets/48504366/f5ff917d-993f-4c38-9043-700fe2597274)
![image](https://github.com/stanfordnlp/dspy/assets/48504366/1db90ad5-ad77-43e2-90a4-8f938b9d9757)

**Comment by insop** [comment]
Hello @Ren-Xin 
I think the output is the model property.

**Comment by Ren-Xin** [comment]
So, what should I do to reproduce the results of llama2:13b in the paper? Now his results are very poor.

**Comment by Ren-Xin** [comment]
Thanks， @insop 
So, what should I do to reproduce the results of llama2:13b in the paper? Now his results are very poor.

**Comment by insop** [comment]
I think if you'd use few-shot learning examples, say through `BootstrapFewShot`, and the model will perform better.

**Comment by travishsu** [comment]
Hi, any other local LLM recommended?
