### ISSUE TITLE
I cannot install pkg_resources

### ISSUE THREAD

**Issue by erlebach** [stanfordnlp/dspy#508]
I just came across `dSPY` and am looking forward to trying it out. I started by running `intro.ipynb`. I then found that `pkg_resources` is not part of the requirements.txt file. I cannot find `pkg_resources` using PIP. On the other hand, I read that this package is deprecated. Could you please provide instructions on how to install `pkg_resources` on a Mac M1? Presumably, the process is the same on all systems. Thanks.

**Comment by insop** [comment]
I think you can install using ([link](https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources))
```
pip install setuptools
```

**Comment by thomasahle** [comment]
Maybe we need to add `setuptools` to the requirements.txt

**Comment by insop** [comment]
> Maybe we need to add `setuptools` to the requirements.txt

100%
