### ISSUE TITLE
WARNING: Not all input fields were provided to module. - Should this be an error?

### ISSUE THREAD

**Issue by thomasahle** [stanfordnlp/dspy#514]
Currently, if you call a module without all the input fields it requires, you get a warning, e.g. `WARNING: Not all input fields were provided to module. Present: []. Missing: ['question'].`
But is there really any reason to continue the program if the module doesn't have the inputs it needs?
Normally if a python function is called without all it's arguments, it just throws an error like `TypeError: f() missing 1 required positional argument: 'question'`.
Should DSPy modules be the same?

**Comment by okhat** [comment]
Yes, eventually I can see this becoming an error. But there are blockers temporarily, like some assertions implementation details
