### ISSUE TITLE
Postgres PGvector retriever hardcodes old embedding model

### ISSUE THREAD

**Issue by josh-mantovani** [stanfordnlp/dspy#517]
The `PgVectorRm` hardcodes the embedding model to be `text-embedding-ada-002`. They have new embedding models and it'd be great to allow users to specify this. https://github.com/stanfordnlp/dspy/blob/01455bd20f5770819aff9edc0b43915203f71cbd/dspy/retrieve/pgvector_rm.py

**Comment by Joshmantova** [comment]
Resolved in this PR: https://github.com/stanfordnlp/dspy/pull/614
