### ISSUE TITLE
BootstrapFewShot failing due to lm.copy for AzureOpenAI

### ISSUE THREAD

**Issue by insop** [stanfordnlp/dspy#521]
### Summary

BootstrapFewShot failing due to lm.copy for AzureOpenAI, likely due to positional argument issue from recent changes.

### Environment
- code: 98304a2eb9d1dddaaa846e30258cd5d8fc6b5d8d
- model azure openai

### Error message
- during `BootstrapFewShot` run, code errored out due to missing arguments, `api_version`

```
>[dspy/dsp/modules/lm.py](https://file+.vscode-resource.vscode-cdn.net/Users/insop/Projects/Github/NLP/dspy/dsp/modules/lm.py)(106)copy()
    102         model = kwargs.pop('model')
    105 
--> 106         return self.__class__(model, **kwargs)
```

### Analysis

AzureOpenAI expects positional arguments, so it is failing.
I will add my fixes and see if that will impact other models.

```
class AzureOpenAI(LM):
...

    def __init__(
        self,
        api_base: str,
        api_version: str,
        model: str = "gpt-3.5-turbo-instruct",
        api_key: Optional[str] = None,
        model_type: Literal["chat", "text"] = "chat",
        **kwargs,
    ):

**Comment by okhat** [comment]
Resolved? Closing but lmk @insop , thanks a lot btw

**Comment by insop** [comment]
> Resolved? Closing but lmk @insop , thanks a lot btw

Thank you @okhat.

**Comment by insop** [comment]
Update.

Related to the issue (https://github.com/stanfordnlp/dspy/issues/543) that caused by the PR (https://github.com/stanfordnlp/dspy/pull/522) from this issue:


I tried to reproduce the issue I ran into earlier, https://github.com/stanfordnlp/dspy/issues/521, but I am not able to reproduce it.

The strange thing is that the code gets to this part as part of `BootstrapFewShot`, but it doesn't seem like `copy()` is called. It seems as if something to do with cache, but I am not able to find it.

https://github.com/stanfordnlp/dspy/blob/669ecd7e04431a0e890ca61c60afafcae1544517/dsp/modules/lm.py#L104
