### ISSUE TITLE
error when using azure api 

### ISSUE THREAD

**Issue by amirhossein-yousefi** [stanfordnlp/dspy#543]
Completions.create() got an unexpected keyword argument 'api_base'

**Comment by qianzheng12** [comment]
I think they shouldn't include api_key, api_base and api_version in the kwargs in azure_opanai.py.
Until it's being resolved, you can manually remove them at line 110 in azure_openai.py, which will get things working for the time being

**Comment by insop** [comment]
This code is working for me the latest code (I am using 244a81705f1bb84eb3ccff24c2d18aa539fa1aa1)

```
        model_arg = {
            "engine": model_name,
            "deployment_id": model_name,
            "api_version": openai.api_version,
            "api_base": openai.api_base,
        }

        # provider_name = "azure"
        lm = dspy.AzureOpenAI(
            model=model_name,
            api_key=openai.api_key,
            **model_arg,
        )
```

**Comment by gauthamk28** [comment]
> This code is working for me the latest code (I am using [244a817](https://github.com/stanfordnlp/dspy/commit/244a81705f1bb84eb3ccff24c2d18aa539fa1aa1))
> 
> ```
>         model_arg = {
>             "engine": model_name,
>             "deployment_id": model_name,
>             "api_version": openai.api_version,
>             "api_base": openai.api_base,
>         }
> 
>         # provider_name = "azure"
>         lm = dspy.AzureOpenAI(
>             model=model_name,
>             api_key=openai.api_key,
>             **model_arg,
>         )
> ```

Still I am facing the same issue :(
dspy-ai 2.3.6

**Comment by ClaartjeBarkhofTNO** [comment]
Running into the same issue here, could it be due to this OPENAI_LEGACY global variable? 

[It is use in this line](https://github.com/stanfordnlp/dspy/blob/ee646535c232c5ced9e1e948754843e5af5f0d46/dsp/modules/azure_openai.py#L74)

**Comment by JLKaretis** [comment]
Same issue for me as well with dspy-ai 2.3.6

I've tried Insop's code with no success. It seems Qianzheng12 is right, api_base is only useful to initialize the client, then it shouldn't be kept in kwargs after that

**Comment by insop** [comment]
I am using openai `0.28.1`.
Are you using new API?

**Comment by ClaartjeBarkhofTNO** [comment]
I am using a newer version `openai==1.13.3`
