### ISSUE TITLE
Can't able to import the dspy package

### ISSUE THREAD

**Issue by shriyokesh** [stanfordnlp/dspy#558]
Hi, I've been exploring DSPy framework for the past 2 days. Today when I tried to import the DSPy package, it throws error. I can't even able to run the code which I wrote yesterday. I attached the error message below. Does anyone facing same issues today?  Is this related to any recent updates in the package?

Error Message:
**Traceback (most recent call last):

  File [~\AppData\Roaming\Python\Python311\site-packages\IPython\core\interactiveshell.py:3577](https://file+.vscode-resource.vscode-cdn.net/d%3A/AI%26ML%20Learnings/DSPy%20Framework/~/AppData/Roaming/Python/Python311/site-packages/IPython/core/interactiveshell.py:3577) in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  Cell In[1], [line 1](vscode-notebook-cell:?execution_count=1&line=1)
    import dspy

  File [c:\Users\Shriyokesh.T\AppData\Local\Programs\Python\Python311\Lib\site-packages\dspy\__init__.py:12](file:///C:/Users/Shriyokesh.T/AppData/Local/Programs/Python/Python311/Lib/site-packages/dspy/__init__.py:12)
    from dspy.player import Player

  File [c:\Users\Shriyokesh.T\AppData\Local\Programs\Python\Python311\Lib\site-packages\dspy\player.py:38](file:///C:/Users/Shriyokesh.T/AppData/Local/Programs/Python/Python311/Lib/site-packages/dspy/player.py:38)
    print 'Too many generators to append another'
    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?**

**Comment by okhat** [comment]
Please install dspy-ai not dspy. This is not an issue from our end
