### ISSUE TITLE
Error when running Evaluate:  'str' object has no attribute '_store'

### ISSUE THREAD

**Issue by gramster** [stanfordnlp/dspy#568]
I am trying out DSPy 2.3.6 with a simple transcript summarization example:

```python
class Summarizer(dspy.Module):
    def __init__(self):
        super().__init__()
        self.summarizer = dspy.Predict('transcript -> summary')
        
    def forward(self, transcript):
        return dspy.Prediction(summary=self.summarizer(transcript=transcript))
```

I created a number of test examples, with:

```python
testset=[x.with_inputs('transcript') for x in [
    dspy.Example(transcript='...', summary='...'),
    ...
]]
```

I also created a metric function, which I have verified is working as expected.

However, when I run this code:

```
evaluate = dspy.evaluate.Evaluate(devset=testset, metric=metric, num_threads=1, display_progress=True, display_table=True)
evaluate(Summarizer())
```

I get this error, repeating once for each of test case:

```
Error for example in dev set: 		 'str' object has no attribute '_store'
```

I have verified that the test cases in `testset` each have a `_store` attribute, so its not that. So I'm a bit stumped, and hoping someone has the answer before I go step through all the code line by line.

**Comment by gramster** [comment]
Okay, so bizzarely I have narrowed it down to the metric. This is despite the fact that I can manually call my metric function and it works, but for some reason when called from the optimizer it doesn't work. Code is based pretty much on the DSPy documentation [here](https://dspy-docs.vercel.app/docs/building-blocks/metrics#intermediate-using-ai-feedback-for-your-metric). Here's a fairly minimal version:

```python
class Assess(dspy.Signature):
    """Assess the quality of a summary of a transcript along the specified dimension."""
    summary = dspy.InputField()
    assessment_question = dspy.InputField()
    assessment_answer = dspy.OutputField(desc="No or Yes")
    

def metric(example: dspy.Example, prediction, trace=None):
        
    transcript, answer, summary = example.transcript, example.summary, prediction.summary
    
    assessor = dspy.Predict(Assess)    
    with dspy.context(lm=ollama):
        # This next line is the one that results in the error when called from the optimizer.
        content_eval = assessor(summary=summary, assessment_question=\
                            f"Is the assessed text a good summary of this transcript, capturing all the important details?\n\n{transcript}?")
    return content_eval.to_lower().endswith('yes')
```

**Comment by younes-io** [comment]
@gramster : did you try CoT instead of Predict ? I remember testing that as well but forgot the outcome.. (just to un-block you until the bug is fixed)

**Comment by gramster** [comment]
Good idea, but it still results in the same error.

**Comment by gramster** [comment]
I think I may have found the issue. In my Summarizer.forward method, I am returning a `Prediction`. I based my code off the RAG sample in the tutorial in the docs here: https://dspy-docs.vercel.app/docs/tutorials/rag

This seems to be the problem. If I just return the result from `dspy.ChainOfThought` (or presumably also `dspy.Predict`), I get through the evaluation stage. 

Perhaps the turtorial is out of date.

**Comment by gramster** [comment]
Also I had to remove the `display_table=True` argument to `Evaluate` as that threw an exception in pandas.

**Comment by dkimmunichre** [comment]
Also ran in to the same problem. @gramster  Did you end up not using the module set up of init and forward set up but directly use chainofthought? Just trying to understand the solution clearly

**Comment by seanzhang-zhichen** [comment]
i has same problem...how to solve it?

please help me:

**Comment by leonardtang** [comment]
same :(

**Comment by gramster** [comment]
The solution for me was to not wrap the result in a `Prediction`. So I changed my code to:

```
class Summarizer(dspy.Module):
    def __init__(self):
        super().__init__()
        self.summarizer = dspy.Predict('transcript -> summary')
        
    def forward(self, transcript):
        return self.summarizer(transcript=transcript)
```

**Comment by dkimmunichre** [comment]
That's strange because `self.summarizer(transcript=transcript)` itself returns a Prediction object. 

Calling the forward function vs Wrapping it again in Prediction should not make a difference... especially in its _store attribute...

This seems to be a bug?
