### ISSUE TITLE
Upgrade pydantic to ^2.6

### ISSUE THREAD

**Issue by mwildehahn** [stanfordnlp/dspy#570]
The project is pinned to pydantic 2.5.0. Any reason it can't be upgraded to the latest version ^2.6?

**Comment by isaacbmiller** [comment]
There used to be tests with the pydantic version name in them, but those seem to have been removed. IMO good to upgrade but I would defer to @thomasahle

**Comment by thomasahle** [comment]
Yes, I fixed those tests.
I'm happy to upgrade pydantic if the tests pass.

**Comment by nlaffey** [comment]
👀 I'm also needing pydnatic at 2.6 so that I can generate an OpenApi 3.1 spec

**Comment by thomasahle** [comment]
Yes, I don't see any reason to now upgrade. I don't think we are using any newer features though, so maybe we can just put the requirement `pydantic >= 2.0`?
