### ISSUE TITLE
Support python 3.12

### ISSUE THREAD

**Issue by mwildehahn** [stanfordnlp/dspy#572]
Python 3.12 has significant improvements for asyncio: https://docs.python.org/3/whatsnew/3.12.html

"The [asyncio](https://docs.python.org/3/library/asyncio.html#module-asyncio) package has had a number of performance improvements, with some benchmarks showing a 75% speed up."

I know dspy doesn't support asyncio yet but given the discussions around supporting it, it's worth supporting 3.12.

From doing this on a branch, seems like the one missing dependency is onnx, which recently added support for 3.12 and will support it officially with their 1.16 release: https://github.com/onnx/onnx/issues/5884

**Comment by okhat** [comment]
Thanks a lot! Sorry I'm missing some context, why do you say we don't support 3.12? I might be forgetting something but I think we support `>= 3.9`

**Comment by mwildehahn** [comment]
It looks like waiting on that 1.16 release isn't necessary: https://github.com/stanfordnlp/dspy/pull/582. Just bumping fast embed was enough and running: `poetry lock --no-update`.
