### ISSUE TITLE
Adding `self.history = []` in the custom LM doc example 

### ISSUE THREAD

**Issue by ovshake** [stanfordnlp/dspy#573]
https://github.com/stanfordnlp/dspy/blob/b2816c4a35e3144a06752423de1afb8e68e1005f/docs/docs/deep-dive/language_model_clients/custom-lm-client.mdx#L54

In the code above, should `self.history = []` be added? Since it is being referenced in the other function.

**Comment by okhat** [comment]
@arnavsinghvi11

**Comment by arnavsinghvi11** [comment]
Thanks @ovshake ! updated in docs.
