### ISSUE TITLE
max_tokens error

### ISSUE THREAD

**Issue by lakshmanok** [stanfordnlp/dspy#576]
This appears to be an internal error:
```
  File "/opt/conda/lib/python3.10/site-packages/dspy/primitives/program.py", line 27, in __call__
    return self.forward(*args, **kwargs)
  File "/home/jupyter/lakblogs/bridge_bidding_advisor/bidding_advisor.py", line 107, in forward
    return self.prog(definitions=definitions,
  File "/opt/conda/lib/python3.10/site-packages/dspy/predict/predict.py", line 49, in __call__
    return self.forward(**kwargs)
  File "/opt/conda/lib/python3.10/site-packages/dspy/predict/chain_of_thought.py", line 60, in forward
    return super().forward(signature=signature, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/dspy/predict/predict.py", line 90, in forward
    x, C = dsp.generate(template, **config)(x, stage=self.stage)
  File "/opt/conda/lib/python3.10/site-packages/dsp/primitives/predict.py", line 101, in do_generate
    max_tokens = kwargs.get("max_tokens", dsp.settings.lm.kwargs["max_tokens"])
KeyError: 'max_tokens'
```
I tried to pass in max_tokens as follows:
```
dspy.settings.configure(lm=gemini, max_tokens=1024)
```
and by trying:
```
def forward(self, question):
        ...
        return self.prog(..., max_tokens=1024)
```
Neither works.

**Comment by arnavsinghvi11** [comment]
Hi @lakshmanok , 

> `dspy.settings.configure(lm=gemini, max_tokens=1024)`
this will add max_tokens to the settings arguments, not to the LM.

> `def forward(self, question):
        ...
        return self.prog(..., max_tokens=1024)`
I'm assuming `self.prog` is a DSPy module, which doesn't integrate kwargs as well. 

You'd want to set these kwargs in the initialization of your lm. 
For instance, 

`turbo = dspy.OpenAI(model='gpt-3.5-turbo', max_tokens=1024)
`
You can do similar behavior for any integrated LM in DSPy!

**Comment by AjayKumarGogineni** [comment]
I am facing the same error while using 'gemini-pro" model.

**Comment by danmarg** [comment]
@arnavsinghvi11 I don't think that suggestion works. I haven't dug into this a lot, but if I do what you suggest:

`dspy.Google(api_key=API_KEY, max_tokens=3700)`

I get the error,  `TypeError: GenerationConfig.__init__() got an unexpected keyword argument 'max_tokens'`

Which makes sense: [GenerationConfig](https://ai.google.dev/api/python/google/generativeai/GenerationConfig) takes an arg called `max_output_tokens`, but not one called `max_tokens`.

However, it seems to me that elsewhere in the code you assume this to always be consistently named:

```
            max_tokens = kwargs.get("max_tokens", dsp.settings.lm.kwargs["max_tokens"])
```

It seems to me there's a bit of a design issue here with passing the lm args directly to Google's API (which of course may not match yours) and using the *same* arg names for internal use (as in the above case), but I may be misunderstanding the intention here. I guess an easy--but hackish!--fix would be to just do something like

```
            max_tokens = kwargs.get("max_tokens", dsp.settings.lm.kwargs["max_tokens"] if "max_tokens" in dsp.settings.lm.kwargs else dsp.settings.lm.kwargs["max_output_tokens"])
``` 

SUPER HACKISH! But...

**Comment by arnavsinghvi11** [comment]
ah I think this [recently-merged PR](https://github.com/stanfordnlp/dspy/commit/67b54f4d5efdf17c791be841252a347cace01218) should fix this @danmarg ! 

lmk if it doesn't.

**Comment by danmarg** [comment]
Seems to. Thanks!

(I will say, this still seems like a brittle approach, since if I understand correctly the name of that config field is basically dictated by the third-party LLM clients!)

**Comment by XiaoConstantine** [comment]
I encountered the same issue playing with gemini today, @arnavsinghvi11 I m not seeing proposed fix land either in
main: https://github.com/stanfordnlp/dspy/blob/main/dsp/primitives/predict.py#L95

nor on
v2.4.12: https://github.com/stanfordnlp/dspy/blob/v2.4.12/dsp/primitives/predict.py#L95

Any idea what's going on here?

**Comment by sumandas0** [comment]
Facing same issue everytime there is a possibility of larger output

**Comment by davidbakerrobinson** [comment]
Also facing the same issue

**Comment by DiyarD** [comment]
Same issue

**Comment by fouadtrad** [comment]
Same issue
