### ISSUE TITLE
How to remove and disable cache?

### ISSUE THREAD

**Issue by JPonsa** [stanfordnlp/dspy#578]
Hi team.

I would like to:
1. remove existing change. I was recommended to remove the ~/cache_lib folder but I cannot find it.
2. disable the generation of cache. So I don't need to do step 1 in future iterations.  

Possible use case for disabling cache.  Get slightly different answer versions for the same question. Currently getting duplicates.

      def generate_qa(context: str, n_qa_pairs: int = 5) -> list:
          """Given a context generate n question and answer pairs"""
      
          query_generator = dspy.Predict("context -> question")
          answer_generator = dspy.Predict("context, query -> answer")
      
          qa_pairs = []
          for i in range(n_qa_pairs):
              dspy.settings.configure(lm=lm, temperature=0.7 + (0.1 * i))
              query = query_generator(context=context)
              answer = answer_generator(context=context, query=query.question)
              qa_pairs.append((query.question, answer.answer))
      
          return qa_pairs

**Comment by okhat** [comment]
I believe you should pass `temperature=0.7 + (0.1 * i)` as follows:

```python
query = query_generator(context=context, config=dict(temperature=0.7 + (0.1 * i)))
```

**Comment by meditans** [comment]
Could there be a flag `cache=False` that we can control from the single generation?

It seems to me that we have two solutions for now:
- manually editing the source code to change the cache flag
- doing the trick above slightly varying the temperature
 
If it was a per-generation flag we could write:
```
Predict(Signature)(input1="the input", dspy_cache=False)
```

**Comment by meditans** [comment]
I have found a workaround I'm satisfied with: I defined
```
def t():
    return dict(temperature=0.7 + 0.0001 * random.uniform(-1, 1))
```
and I call:
```
Predict(MySignature, **t)(input1="the input")
```

**Comment by mohamedScikitLearn** [comment]
if anyone still looking for a solution:

From v2.5, you can turn off the cache by setting cache parameter in dspy.LM to False:

`dspy.LM('openai/gpt-4o-mini',  cache=False)`

https://dspy.ai/faqs/
