### ISSUE TITLE
how to use hf client

### ISSUE THREAD

**Issue by ColinS97** [stanfordnlp/dspy#58]
Hi, I hope this is the correct place to ask but I can't figure out how to run dsp with hf-client.
So far I have managed to get the hf-server running. 
But I can't figure out how to use the hf-client.

I start the server with:
`python -m dsp.modules.hf_server --port 4242 --model "google/flan-t5-base"`

With curl everything is fine:
**Client**:
`curl -d '{"prompt":"What is the answer to life, the universe, and everything?"}' \
   -X POST "<my-server-ip>" \
   -H 'Content-Type: application/json' `

`{"prompt":"What is the answer to life, the universe, and everything?","choices":[{"text":"atoms"}],"latency":22557.142734527588}`
   
   
**Server**:
```#> Prompt: "What is the answer to life, the universe, and everything?"
#> Response: "{'prompt': 'What is the answer to life, the universe, and everything?', 'choices': [{'text': 'atoms'}]}"
INFO:     <ip>:0 - "POST / HTTP/1.1" 200 OK
```

Afterward I tried to use the hf_client similar to the intro notebook.

**Client:**
```
>import dsp

>colbert_server = 'http://ec2-44-228-128-229.us-west-2.compute.amazonaws.com:8893/api/search'
>lm = dsp.HFModelClient(port="4242", model="google/flan-t5-base", url="<my-server-ip>")
>rm = dsp.ColBERTv2(url=colbert_server)

>dsp.settings.configure(lm=lm, rm=rm)
> lm._generate(prompt="What is 5+7?")
{'detail': 'Not Found'}
```
**Server:**
`INFO:     141.56.132.131:0 - "POST /%3A HTTP/1.1" 404 Not Found`

**Comment by ColinS97** [comment]
Update: I just figured out the reason it is not working was somehow related to my usage of ngrok, if I have the the server and client running on the same machine it works fine. I will try to get it running through ngrok as well now.

**Comment by okhat** [comment]
Thanks for looking into this! This HF side of DSP is not very mature right now, so let us know if you face any issues. The FLAN models may not be ideal here based on our initial testing

**Comment by ColinS97** [comment]
Why are the FLAN models not ideal? Just because they lack the "emergent abilities" to really make use of DSP programs or some technical reason? I wasn't planning on using FLAN for my experiments but Llama and Open Assistant type models. So I am wondering if there is anything i should watch out for.

**Comment by okhat** [comment]
Yeah, you may see better results with decoder-only models, like the ones you mentioned, especially if you use closed LLMs as the demonstrator. We’ll share more soon

**Comment by ColinS97** [comment]
Very nice, I am excited to see you further progress.
(I hope "compiling" LoRa adapters on consumer GPUs is somewhere on your roadmap, since that would be a really exciting feature for me)

In my fork of DSP I have now adapted the hf_client.py a little bit so that you can pass an ngrok url to the object and it will just work with the hf_server.py.

This is very useful for me since I am serving the models in a HPC cluster an then ngrok them out to the public internet so I can access my models from any device so I think this may be useful for others as well :)

**Comment by okhat** [comment]
Yup we already have these LoRAs — @paridhimaheshwari2708 maybe we should merge something soon?

**Comment by okhat** [comment]
You’re right about this. We are pushing a number of fixes for HF server and clients soon. We’re just starting to play with them — expect many rough edges for a couple of weeks, but then should become something stable

**Comment by okhat** [comment]
By the way things are much more stable now with TGI client in DSPy. Feel free to let us know if you face problems in the new version of the framework.
