### ISSUE TITLE
Azure OpenAI (1.12.0) `Completions.create() got an unexpected keyword argument 'api_base'` Error

### ISSUE THREAD

**Issue by msaleem18** [stanfordnlp/dspy#580]
I have been trying to use Azure OpenAI model (1.12.0) and i keep getting the Completions.create() got an unexpected keyword argument 'api_base'.

It looks like within the Azure OpenAI class:
https://github.com/stanfordnlp/dspy/blob/c2d639fb1c1dafa7d6a12b3fe730b3564580fbfe/dsp/modules/azure_openai.py#L110

depending on the version, the 'api_base' parameter should be 'azure_endpoint' for the new versions.

Wondering if anyone else is having this issue?

Appreciate the help and advice

**Comment by chaitanya-parsana** [comment]
Seeing the same issue. Seems like there's logic to handle it [here](https://github.com/stanfordnlp/dspy/blob/c2d639fb1c1dafa7d6a12b3fe730b3564580fbfe/dsp/modules/azure_openai.py#L89) but it's not propagated downstream.

**Comment by insop** [comment]
Related PR, https://github.com/stanfordnlp/dspy/pull/584

**Comment by arnavsinghvi11** [comment]
@insop with #584 merged, did you want to circle back to adding these kwargs now? related to #591

**Comment by insop** [comment]
> @insop with #584 merged, did you want to circle back to adding these kwargs now? related to #591

Thank you @arnavsinghvi11.
Yes, I will add note to issue #591.

**Comment by insop** [comment]
@arnavsinghvi11 
you can close this and I will work with #591
