### ISSUE TITLE
Docs Discrepancy / Clarification Needed

### ISSUE THREAD

**Issue by mgbvox** [stanfordnlp/dspy#587]
How are we currently building docs? 

I see [Vercel](https://dspy-docs.vercel.app/) is what’s publicly facing, but we also have a mkdocs.yml in the root of the dspy repo. Running `mkdocs serve` used to produce documentation locally that was very different from the vercel documentation (fully different landing page, different UI, UX, etc); now it doesn't build at all. 

If we can clarify how/where docs are generated, and how the community can contribute to said docs, awesome. I'm down to implement and PR if this can be first clarified here.

@krypticmouse tagging you at @okhat 's request.

**Comment by okhat** [comment]
Thank you @mgbvox

**Comment by okhat** [comment]
Adding @arnavsinghvi11 too

**Comment by arnavsinghvi11** [comment]
Tagging the corresponding [README](https://github.com/stanfordnlp/dspy/tree/main/docs#readme) for updating docs as well!

**Comment by insop** [comment]
> Hi @mgbvox, we've migrated away from mkdocs so that file will be removed as well in upcoming PR. Thanks for flagging!
> 
> Regarding contributing to docs you need to `cd docs` and run `npm install` to install the docusaurus dependancies.
> 
> Pull the changes from the subtree but running `git subtree pull ...` command as mentioned in the README of that folder.
> 
> Once done run `npm start` and start modifiying or adding the md content in docs or api folders.
> 
> Once you're done with changes do `npm run build` to make sure there are no breaking changes. If there are you can fix them or feel free tag us so we can help!
> 
> On there is no breaking change in build. Make a PR and we'll review it!
> 
> Hope it helps!

@krypticmouse 
Thank you for the description.
Do we have this documented ?
It'd be great to have that.

I also was confused on the documentation and the public facing web through separate repo previously and mentioned it to @okhat.

**Comment by krypticmouse** [comment]
@insop Good point lemme add this to the docs readme!
