### ISSUE TITLE
BootstrapFewShot failing due to lm.copy for AzureOpenAI

### ISSUE THREAD

**Issue by insop** [stanfordnlp/dspy#591]
Since https://github.com/stanfordnlp/dspy/issues/521 is closed state, creating a new issue.

Now, the initial PR https://github.com/stanfordnlp/dspy/pull/522 for the issue was reverted by this PR, https://github.com/stanfordnlp/dspy/pull/584 recently, I think we need to keep this issue.

----

BootstrapFewShot failing due to lm.copy for AzureOpenAI, likely due to positional argument issue from recent changes.

- Issue: https://github.com/stanfordnlp/dspy/issues/521

### Environment
- code: 98304a2eb9d1dddaaa846e30258cd5d8fc6b5d8d
- model azure openai

### Error message
- during `BootstrapFewShot` run, code errored out due to missing arguments, `api_version`

```
>[dspy/dsp/modules/lm.py](https://file+.vscode-resource.vscode-cdn.net/Users/insop/Projects/Github/NLP/dspy/dsp/modules/lm.py)(106)copy()
    102         model = kwargs.pop('model')
    105
--> 106         return self.__class__(model, **kwargs)
```

### Changes

AzureOpenAI expects positional arguments, so it is failing. I am putting my change for review if that will impact other models.

```
class AzureOpenAI(LM):
...

    def __init__(
        self,
        api_base: str,
        api_version: str,
        model: str = "gpt-3.5-turbo-instruct",
        api_key: Optional[str] = None,
        model_type: Literal["chat", "text"] = "chat",
        **kwargs,
    ):

**Comment by arnavsinghvi11** [comment]
thanks for circling back on this @insop . What were the proposed changes for handling this?

**Comment by insop** [comment]
Thank you @arnavsinghvi11 .

I catch up the latest main and will propose soon.

**Comment by snimu** [comment]
I've run into the same issue, and it looks to me like the problem isn't8 that `api_base` needs to be renamed to `azure_endpoint`, but that `dspy.AzureOpenAI` hasn't redefined the `LM.copy`-method, so it falls back on that. For that method to work, `self.kwargs` in `AzureOpenAI` would have to include `api_base` and `api_version`, but they don't. So either, `AzureOpenAI.copy` should be implemented (preferred), or `api_base` and `api_version` have to be added to `AzureOpenAI.kwargs`.
