### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by gramster** [stanfordnlp/dspy#598]
It seems that versioning for this project is done in a very ad-hoc way by updating setup.py. I would like to suggest that releases get tagged in github too, to make it a bit easier to make sure that when trying to debug an issue in a specific version, that the right code snapshot is being looked at.

**Comment by insop** [comment]
Thank you @gramster.
I second this suggestion.

I think having proper tagging will help many people especially the repo's moving very fast.

@okhat , @arnavsinghvi11 , @CShorten

**Comment by isaacbmiller** [comment]
Right now @okhat manually updates the version in setup.py and pyproject.toml. I would love to set up an automated build/deploy system.

**Comment by bschulth** [comment]
Another upvote on this request

**Comment by kujenga** [comment]
It appears that the latest release had a git tag and GitHub release added: https://github.com/stanfordnlp/dspy/releases/tag/v2.4.3

Great to see! Will that be standard going forward?

**Comment by hmoazam** [comment]
Yes that will be the standard going forward! Marking this issue as resolved as we've implemented the flow for automatic releases and tagging
