### ISSUE TITLE
GSM8k metric expects the answer in first line

### ISSUE THREAD

**Issue by UtkarshGarg-UG** [stanfordnlp/dspy#651]
Hi,

In the file https://github.com/stanfordnlp/dspy/blob/main/dspy/datasets/gsm8k.py

gsm8k_metric() calls parse_integer_answer()
In parse_integer_answer, the default value of only_first_line is True. What if the answer is not in first line? There does not seem to be a way to directly change only_first_line to False if using gsm8k_metric. When using with Evaluate or compile, we cannot use the imported metric directly. We need to override the metric definition below manually to only_first_line = False. 

```
def parse_integer_answer(answer, only_first_line=True): # I manually change only_first_line to False so that reasoning answer work
    try:
        if only_first_line:
            answer = answer.strip().split('\n')[0]

        # find the last token that has a number in it
        answer = [token for token in answer.split() if any(c.isdigit() for c in token)][-1]
        answer = answer.split('.')[0]
        answer = ''.join([c for c in answer if c.isdigit()])
        answer = int(answer)

    except (ValueError, IndexError):
        # print(answer)
        answer = 0
    
    return answer


def gsm8k_metric(gold, pred, trace=None):
    return int(parse_integer_answer(str(gold.answer))) == int(parse_integer_answer(str(pred.answer)))
```

**Comment by okhat** [comment]
Thank you @UtkarshGarg-UG . Discussed before at #363
