### ISSUE TITLE
SQL retriever -  Feature Request / Question

### ISSUE THREAD

**Issue by JPonsa** [stanfordnlp/dspy#661]
Not sure if I am using the right terminology.

User Story: As developer I would like to create a RAG system based of txt-to-SQL. To do this I need be able to connect to a SQL db

I saw llamaindex lifted and shifted langchain's SQL wrapper. Wondering if the same would need to happen for DSPy.  
https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/utilities/sql_wrapper.py

This would not be enough for the SQL based RAG system but it is a necessary component. Still digging into llamaindex's implementation to understand it better.

**Comment by thomasahle** [comment]
```python

import datasets
ds = datasets.load_dataset("b-mc2/sql-create-context")

import dspy
demos = [dspy.Example(**d).with_inputs("context", "question") for d in ds['train']]
train, test = demos[:100], demos[100:200]

import dspy, dotenv, os
dotenv.load_dotenv(os.path.expanduser("~/.env"))  # load OpenAI API key from .env file
lm = dspy.OpenAI(model="gpt-3.5-turbo", max_tokens=4000)
dspy.settings.configure(lm=lm)

from dspy.evaluate import Evaluate
exact_match = lambda ex, pred, _trace=None: ex.answer == pred.sql_query

evaluator = Evaluate(
    devset=test,
    num_threads=30,
    metric=exact_match,
    display_progress=True,
)
program = dspy.TypedPredictor("context, question -> sql_query")
print(evaluator(program))

from dspy.teleprompt.bootstrap import BootstrapFewShot
compiled = BootstrapFewShot(
    metric=exact_match,
    max_rounds=1,
).compile(
    program,
    trainset=train,
)
print(evaluator(compiled))
```

**Comment by JPonsa** [comment]
Thanks for the example. I could not reproduce it because I am having an issue with datasets. it does not matter what version I tried I cannot download any dataset. 

However, I tried with a small dataset of 7 examples. if I increase the max_round to > 1 it gives me an error (see bellow). Mentioning it as you may want to test on your end.

File ...\Lib\site-packages\dspy\teleprompt\bootstrap.py:109, in BootstrapFewShot._bootstrap(self, max_bootstraps)
    106     break
    108 if example_idx not in bootstrapped:
--> 109     success = self._bootstrap_one_example(example, round_idx)
...
    101 kwargs = {**self.kwargs, **kwargs}
--> 102 model = kwargs.pop('model')
    104 return self.__class__(model=model, **kwargs)

KeyError: 'model'

**Comment by arnavsinghvi11** [comment]
Hi @JPonsa , 

this error is not related to the datasets but with the configuration of lm in DSPy. Do you specify the model name when using an LM in DSPy? 

For instance with the code above:
```
lm = dspy.OpenAI(model="gpt-3.5-turbo", max_tokens=4000)
dspy.settings.configure(lm=lm)
```

**Comment by JPonsa** [comment]
Confirmed user error. I must have missed setting the LLM. I can no longer reproduce the issue.

**Comment by pragyan019** [comment]
@thomasahle How do we pass test context and question after compiling , `compiled = BootstrapFewShot(
    metric=exact_match,
    max_rounds=1,
).compile(
    program,
    trainset=train,
)
print(evaluator(compiled))`
