### ISSUE TITLE
Support terminal for displaying table when evaluating metrics 

### ISSUE THREAD

**Issue by sandangel** [stanfordnlp/dspy#663]
Right now the Evaluate class only support displaying in Colab. It would be nice if we also support terminal output given it is already supported in pandas.

**Comment by thomasahle** [comment]
There was a recent discussion of this, I forget where.
I think this could be nice as well.

**Comment by sandangel** [comment]
Yeah, I think we will need this feature to display when running in CI and output to markdown or github comments

**Comment by okhat** [comment]
Happy to merge a PR on this, sounds like it's already in pandas
