### ISSUE TITLE
TypedPredictor bool always returns True

### ISSUE THREAD

**Issue by JPonsa** [stanfordnlp/dspy#664]
Likely a user error but when I tried to use dspy.TypedPredictor to return a boolean answer it always returns True despite the question. e.g. Q:"Is the sky brown?" A:True. I checked and if I change  the output var to be str it works as expected returning Q: "Is the sky brown?" A:"False". I tried with OpenAI(GPT3.5) and Ollama(Mistral).

      import dspy

      class QABoolean(dspy.Signature):
          "Given a question provide a boolean answer"
          question: str = dspy.InputField(prefix="Question:")
          answer: bool = dspy.OutputField(desc="either True or False", prefix="Answer:")
      
      # lm = dspy.OllamaLocal(model="mistral", stop=["\n", "\n\n"])
      lm = dspy.OpenAI(model="gpt-3.5-turbo", stop="\n\n")
      dspy.settings.configure(lm=lm, temperature=0.0)
      
      checker = dspy.TypedPredictor(QABoolean)
      
      code = 'print("Dspy is cool!")'
      question = "Is this code dangerous to run" + code
      response = checker(question=question)
      print(response.answer) # Returns True -> Correct
     
      question = "Is the sky brown?"
      response = checker(question=question) # Returns True -> Wrong

**Comment by thomasahle** [comment]
Fixed that in a recent push.
Please try again with the latest code from main.
