### ISSUE TITLE
Image not showing up in Deep-Dive Blogs

### ISSUE THREAD

**Issue by shuklaji28** [stanfordnlp/dspy#666]
I was going through deep dives but had to go back to images folder twice to see manually what exactly it's about :)
Please fix this issue xd. Not a big one but actually affects user experience :)

![image](https://github.com/stanfordnlp/dspy/assets/66516678/acafcd9d-08c4-4380-8f56-7bcda1e18cfd)

**Comment by okhat** [comment]
@krypticmouse

**Comment by krypticmouse** [comment]
@shuklaji28 I think you are viewing md files on github and not website

Here is the link to the docs website: https://dspy-docs.vercel.app/docs/deep-dive/teleprompter/signature-optimizer

![image](https://github.com/stanfordnlp/dspy/assets/43719685/aeca1bdc-fdca-422e-96db-1f5aeb85b652)
