### ISSUE TITLE
MIPRO compilation during token change

### ISSUE THREAD

**Issue by ivy113** [stanfordnlp/dspy#678]
I am running using Azure and have a token that needs to be refreshed every 30 min or so. Normally, this works for the Bootstrap / Bootstrap FewShot optimizers.. After refresh of token, compilation begins from where it was cut short. I've tried the same for MIPRO and while it jumps to where it left off, it is unable to make any further progress.. My suspicion is that the lm does not get refreshed to the existing optimizer in the same way that it does for the Bootstrap. 

Welcome to any suggestions.

**Comment by okhat** [comment]
Ah this is tricky. Do you restart your script or notebook?

**Comment by ivy113** [comment]
I don't restart the notebook. Usually I need to refresh the api key, rerun the cell and it will work (for Bootstrap).
