### ISSUE TITLE
Stop using `print`, start using `logger`

### ISSUE THREAD

**Issue by thomasahle** [stanfordnlp/dspy#681]
As discussed in https://github.com/stanfordnlp/dspy/issues/589 we have a lot of print statements around the code in dspy.

This [stackoverflow question](https://stackoverflow.com/questions/6918493/in-python-why-use-logging-instead-of-print) has a lot of good reasons for why we should use the standard practice of loggers instead:
```
- Easy to see where and when (even what line no.) a logging call is being made from.
- You can log to files, sockets, pretty much anything, all at the same time.
- You can differentiate your logging based on severity.

Also, if your project is meant to be imported by other python tools, it's bad practice for your package to print things to stdout, since the user likely won't know where the print messages are coming from. With logging, users of your package can choose whether they want to propogate logging messages from your tool or not.
```

**Comment by nbqu** [comment]
Many Python libraries support logging modules, which dspy does not support yet. We may refer to such packages (e.g. [transformers](https://github.com/huggingface/transformers/blob/main/src/transformers/utils/logging.py), [litellm](https://github.com/BerriAI/litellm/blob/main/litellm/_logging.py), [optuna](https://github.com/optuna/optuna/blob/master/optuna/logging.py)) to implement it if needed.

**Comment by hasalams** [comment]
[loguru](https://github.com/Delgan/loguru) is a simple yet powerful library.

**Comment by KCaverly** [comment]
I think logging would be great to add.

I took a look at the above, and for transformers/litellm/optuna all use the `logging` library.
While `loguru` does look super ergonomic, they route their logs to stderr as opposed to stdout: https://loguru.readthedocs.io/en/stable/resources/migration.html

Idk if this is a significant concern (I imagine it can be changed via config somehow), but I imagine we may want something that aligns with logging to ensure, all most of the logs play nicely with `logging`.

[structlog](https://www.structlog.org/en/stable/index.html) is another popular option that wraps `logging` for improved ergonomics.

**Comment by krypticmouse** [comment]
+1 for loguru!!

**Comment by saen-ai** [comment]
btw i know a way of disabling logger when its in production mode so you only need to write enable or disable from .env any file
