### ISSUE TITLE
`lm.py` does too much special casing based on `self.provider`

### ISSUE THREAD

**Issue by thomasahle** [stanfordnlp/dspy#688]
`dsp.modules.lm` is nearly all special cases:

<img width="520" alt="Screenshot 2024-03-20 at 4 06 54 PM" src="https://github.com/stanfordnlp/dspy/assets/946355/ce61a25a-f07c-4aac-83cb-fcd740762f2c">
<img width="858" alt="Screenshot 2024-03-20 at 4 07 18 PM" src="https://github.com/stanfordnlp/dspy/assets/946355/49b93df2-1649-4491-b3a3-6da4ade123c4">

We should think about how to move those decisions into the LM subclasses instead.

Maybe this is already happening in the backend refactor @KCaverly ?

**Comment by KCaverly** [comment]
Currently the new `BaseLM` returns a list of choices. But I think we could probably just simplify this to return a list of strings. As the strings are parsed and managed by the Backend.

No `inspect_history` has been written either.

While we do track the prompt, and everything generated, I am unsure if it makes sense to recreate the entire text this way. I would expect most OpenAI calls moving forward for example to go through the `JSONBackend`, which returns JSON, in this scenario, we could regenerate the templated text or show the prompt + generated data, whichever is most useful.

**Comment by nbqu** [comment]
This issue would be related to [this](https://github.com/stanfordnlp/dspy/issues/390#issuecomment-1947542304), as litellm would provide consistent output format.

**Comment by okhat** [comment]
This is now addressed via the new dspy.LM
