### ISSUE TITLE
TypedPredictor asking for 'very succinct' object leads to incomplete object in output

### ISSUE THREAD

**Issue by conradlee** [stanfordnlp/dspy#691]
When a typed predictor creates examples, it uses the following promt [here](https://github.com/stanfordnlp/dspy/blob/7227e7081d8edc3d0ffc2729f7c97871aa61338b/dspy/functional/functional.py#L103),  which states:

> `"Make a very succinct json object that validates with the following schema"`

This is problematic.  In my case I have a quite complex schema with many fields, a few of which are nested.  Sometimes the prompt works, but often the object that's output is missing required fields.   I think the root cause is that the example that's created by that prompt is also missing fields.

Note that it seems the model (GPT4) is aware of this. Beneath the LLM-generated example, the model notes that

> Please note that the JSON schema provided in the input does not directly apply to the output structure, as the output structure is a simplified version of the schema that only includes the necessary fields based on the given input. The output does not include fields such as `database_lookups` or specific workflow actions since they are not required in this case.

I think your intention with `very succinct` is that this is just an example, so the model should not waste tokens creating a long/verbose/expressive example.  That totally makes sense.  But empirically I'm observing that the example has become so succinct that it's actually not valid, leading to the output also being invalid.

Thus I would suggest modifying this prompt a bit to something like 
> `"Make a succinct yet complete json object that validates with the following schema"`

cc @thomasahle

**Comment by thomasahle** [comment]
Sounds good to me. Feel free to make a PR!

Did you already test that it works with this changed prompt?
Otherwise, I've been thinking it would be nice to use https://pypi.org/project/polyfactory/ to create the demo instance.
Const: It would add yet another dependency to dspy. Pros: the generation would be grounded by something not an LLM.

Also, I'm not sure what the best way to handle those "internal prompts" are. Ideally we don't want DSPy to be a "prompt library". Once we have a bunch of magical built in prompts, we need to tune them, translate them etc.
Maybe that's another argument in favor of using polyfactory.

**Comment by invinciible** [comment]
This issue isn't resolved yet. 

I've a complex type for the output and most of the time claude 3.5 sonnet adds some text at the end of the json in first output. second output it misses some fields and then dspy module resend the full prompt again and it gets the final output. 

Takes time as well as more tokens. Hoping team to fix this. complex output types with lists are useless atm.

**Comment by okhat** [comment]
Typed Predictors are deprecated. Use types with normal dspy.Predict and dspy.ChainOfThought. They work much better.

**Comment by invinciible** [comment]
But if I have a custom type list in the output field, it gives exception
even with the latest version that it’s not able to find format_handler. I
can’t find any relevant docs either with the usage.
