### ISSUE TITLE
Azure Cognitive Search Retrieval Example

### ISSUE THREAD

**Issue by binga** [stanfordnlp/dspy#697]
Firstly, thank you for the amazing project. It's nice to see the prompting paradigm going away.

I wanted to check if there is an example demonstrating ACS as a retriever model?

I looked up in the [docs](https://dspy-docs.vercel.app/docs/deep-dive/retrieval_models_clients/Azure#sending-retrieval-requests-via-azure-client) and it has a TODO marked in there. Thank you for your time.

**Comment by hasalams** [comment]
Few months back I had a PR for this. 
Pls check below.
https://github.com/hasalams/dsp/blob/azure_cognitive_search/dsp/modules/azurecognitivesearch.py
