### ISSUE TITLE
Upgrade Weaviate client to v4

### ISSUE THREAD

**Issue by jettro** [stanfordnlp/dspy#699]
At the moment, the Weaviate Retriever module uses the v3 drivers. I want to upgrade them to the latest release, v4.

Some improvements in the latest and greatest version:
- Performance upgrade through the use of gRPC
- More consistent and more accessible to write queries
- more type safety
- Removal of builder patterns

Documentation for the migration is available here:
https://weaviate.io/developers/weaviate/client-libraries/python/v3_v4_migration

**Comment by jettro** [comment]
I want to pick this up myself, will post a pull request shortly

**Comment by tanmay17061** [comment]
@jettro were you able to achieve this?
my current logic to populate the vector DB uses client v4.
I would love to be able to use the same client version in my dspy logic.

**Comment by jettro** [comment]
@tanmay17061 yes, it is merged in main.
