### ISSUE TITLE
Using dspy.Google for RAG is an issue

### ISSUE THREAD

**Issue by aryamansriram** [stanfordnlp/dspy#702]
The dspy.Google wrapper does not seem to have the max_tokens argument which the other providers (like OpenAI) does seem to have. This seems to cause an issue when using dspy modules like ChainofThrought and Predict.
Please let me know if there's a workaround

**Comment by nbqu** [comment]
#646 Is this work for you?
fyi, google API accepts `max_output_tokens` rather than `max_tokens`.

**Comment by Arbaaz-Mahmood** [comment]
I think the way we set up LLM clients inside dspy should be standardised irrespective of what the provider accepts on the BE

**Comment by aryamansriram** [comment]
I did some digging and found the issue. The template.extract() method is not able to find a field in the signature in the COT() module for some questions because the key for that field is not returned in the completion.
The field name is hard coded to ‘\n’ + field name

**Comment by Athe-kunal** [comment]
In the latest pull, I think it has been resolved. Here in this [line](https://github.com/stanfordnlp/dspy/blob/main/dsp/primitives/predict.py#L111), before we had only `max_tokens` which is a parameter to OpenAI, but now there is `max_output_tokens`.

**Comment by hacker-4-good** [comment]
just few hours back resolve the error, in google.py file genai is not imported so for this we have to install (pip install google-generativeai). Now we can use dspy.Google(model="models/gemini-1.0-pro") and this is by default model. I hope this resolve issue for everyone who want to use Google gemini in dspy.
