### ISSUE TITLE
Predictors hang when errors happen in multithreading

### ISSUE THREAD

**Issue by thomasahle** [stanfordnlp/dspy#715]
Consider these three programs:

**Program 1:**
```python
def worker():
    pred = dspy.TypedPredictor("question -> answer")
    print(pred(question="What is the capital of France?").answer)

if __name__ == "__main__":
    dotenv.load_dotenv(os.path.expanduser("~/.env"))
    dspy.settings.configure(lm=dspy.OpenAI(model="gpt-4-turbo-preview"))
    with ThreadPoolExecutor() as executor:
        executor.submit(worker)
    time.sleep(1)
```

**Program 1:**
```python
def worker():
    pred = dspy.TypedPredictor("question -> answer")
    print(pred("What is the capital of France?").answer)

if __name__ == "__main__":
    dotenv.load_dotenv(os.path.expanduser("~/.env"))
    dspy.settings.configure(lm=dspy.OpenAI(model="gpt-4-turbo-preview"))
    with ThreadPoolExecutor() as executor:
        executor.submit(worker)
    time.sleep(1)
```

**Program 3:**
```python
if __name__ == "__main__":
    dotenv.load_dotenv(os.path.expanduser("~/.env"))
    dspy.settings.configure(lm=dspy.OpenAI(model="gpt-4-turbo-preview"))
    pred = dspy.TypedPredictor("question -> answer")
    print(pred("What is the capital of France?").answer)
```

Program 1 works.
Program 2 throws an error (TypeError: TypedPredictor.forward() takes 1 positional argument but 2 were given)
Program 3 just hangs forever.

I'm not sure what in dspy's multithreading is causing this, but I spent an hour today debugging a problem because of it.

I know dspy and threading is a bit complicated right now, and maybe not supported at all, but if there's any way to at least give some more information when it fails, it would be greatly appreciated.

**Comment by okhat** [comment]
Threading is only supported through Evaluate. But the general pattern that does it inside Evaluate will allow parallelism in any context (but maybe not nested parallelism).

This is critical. Can’t do threading without that pattern. It’s basically all about managing dspy.settings

**Comment by thomasahle** [comment]
Actually this turns out to not be a dspy problem at all.
It's just that I forgot ThreadPoolExecutor returns futures that needs to be awaited. (https://stackoverflow.com/a/70151093/205521)

```python
def worker():
    pred = dspy.TypedPredictor("question -> answer")
    print(pred("What is the capital of France?"))

if __name__ == "__main__":
    dotenv.load_dotenv(os.path.expanduser("~/.env"))
    lm = dspy.OpenAI(model="gpt-4-turbo-preview", max_tokens=4000)
    dspy.settings.configure(lm=lm)

    threading.Thread(target=worker).start()
    time.sleep(1)
```
works.
