### ISSUE TITLE
Opaque output truncation as `max_tokens` is not explicitally included in the __init__ for GPT3 (OpenAI) 

### ISSUE THREAD

**Issue by harrysalmon** [stanfordnlp/dspy#730]
Currently the output tokens for Openai is set to 75, half of the value of the max tokens specified here in gpt3.py 

```
...
self.kwargs = {
    "temperature": 0.0,
    "max_tokens": 150,
    "top_p": 1,
    "frequency_penalty": 0,
    "presence_penalty": 0,
    "n": 1,
    **kwargs,
}  # TODO: add kwargs above for </s>
...
```

As this is only setable through kwargs, there's no indication to the user in the OpenAI class why the output is being truncated or how to modify it. 

I might be missing a reason for this, but I'll open a PR to modify it and see what folks think.

**Comment by okhat** [comment]
Thank you @harrysalmon ! Left some quick comments on the PR. It's a bit more complex than it seems.
