### ISSUE TITLE
How to use DSPy on Databricks cluster with HFClientVLLM

### ISSUE THREAD

**Issue by manjubsavanth** [stanfordnlp/dspy#736]
While we can use the below code for [local](http://localhost) installation. Can you suggest what needs to be replaced instead of local host when we are hosting Mistral7B on Databricks cluster?

>>> import dspy
>>> lm = dspy.HFClientVLLM(model="NousResearch/Llama-2-7b-chat-hf", port=8000, url="http://localhost")
>>> lm("My name is ")

This throws a port exception error given I have a cluster of GPU

**Comment by arnavsinghvi11** [comment]
@manjubsavanth You'll likely have to set your url to the Databricks cluster endpoint you are hosting the model on. localhost is just a default for now.

**Comment by manjubsavanth** [comment]
@arnavsinghvi11 I was able to launch the model on Databricks cluster using the [guide ](https://dspy-docs.vercel.app/docs/deep-dive/language_model_clients/local_models/HFClientVLLM) written by you. However the kwargs passed with dspy configuration settings does not seem to work and model produces unwanted output without accounting for the max_tokens.
