### ISSUE TITLE
Reduce number of files in main folder

### ISSUE THREAD

**Issue by thomasahle** [stanfordnlp/dspy#740]
We're ragging up a lot of files in the main folder in our github repository. (See screenshot below.)
The issue is that this pushes down the README and DSPy logo below the fold; and generally adds noise that most people don't care about.
Compare with something like [sglang](https://github.com/sgl-project/sglang) which has about half as many files on the github front page.

<img width="761" alt="Screenshot 2024-03-29 at 10 43 56 AM" src="https://github.com/stanfordnlp/dspy/assets/946355/e11e51d9-9381-455f-b66c-062c3acd2bd4">

It would suggest that the main files we really want to keep in the top level folder are:

- README.md
- LICENSE
- CONTRIBUTING.md
- intro.ipynb
- examples
- docs

A few files we might have to include, for technical reasons are

- .github
- .gitignore
- pyproject.toml
- setup.py
- tests

And then a bunch of stuff that's just noise:

- cache
- .pre-commit-config.yaml
- pyserini.ipynb
- .devcontainer
- inspect-app
- mkdocs.yml
- poetry.lock
- requirements.txt
- testing

The files `skycamp2023.ipynb` and `skycamp2023_completed.ipynb` presumably belongs in the `examples/` folder.
The `testing/` could be moved into `dspy/` or `dsp/`.
In fact, if we could move `dsp/` into `dspy/` it would also clear some things up, and emphasize that this is low level stuff that new users probably don't need to know about.

Happy to all of your thoughts about what's ideal and/or feasible.

**Comment by Josephrp** [comment]
it's been a pain guessing what's in `dsp/` and what's in `dspy/` (for me) a forward thinking refactor of evaluation/ should be a smart thing to do at the same time and there's also likely a list of refactors that might be suitable to produce a single release with all the changes.

> that's because the project grew quicky and there's scope creep and possible dozens of integrations that may be contributed this year.
