### ISSUE TITLE
unable to connect to the host: future-hgx-1

### ISSUE THREAD

**Issue by yoshitavarmaannam** [stanfordnlp/dspy#757]
I have been trying to run DSPy from local machine, however, unable to connect to the host: future-hgx-1.

Error: ConnectionError: HTTPConnectionPool(host='future-hgx-1', port=7141): Max retries exceeded with url: /generate (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002828E0D3B10>: Failed to resolve 'future-hgx-1' ([Errno 11001] getaddrinfo failed)"))

Can someone please help me with this issue?

Errors out when try to connect open source model.

llama = dspy.HFClientTGI(model="meta-llama/Llama-2-7b-chat-hf", port=[7140, 7141, 7142, 7143], max_tokens=150)
colbertv2 = dspy.ColBERTv2(url='http://20.102.90.50:2017/wiki17_abstracts')

dspy.settings.configure(rm=colbertv2, lm=llama)

**Comment by arnavsinghvi11** [comment]
Hi @yoshitavarmaannam , you need to specify your corresponding HFClientTGI endpoint URL and port(s). This [documentation](https://dspy-docs.vercel.app/docs/deep-dive/language_model_clients/local_models/HFClientTGI) will be helpful. The current code is just an example of querying to a local endpoint (`future-hgx-1`).

**Comment by yoshitavarmaannam** [comment]
I think I understood the issue. Thanks!
