### ISSUE TITLE
There is a small error in the example in signature-optimizer.mdx.

### ISSUE THREAD

**Issue by gujie01** [stanfordnlp/dspy#782]
https://github.com/stanfordnlp/dspy/blob/main/docs/docs/deep-dive/teleprompter/signature-optimizer.mdx

![image](https://github.com/stanfordnlp/dspy/assets/70249499/22654634-6646-4351-a396-5c922d6b1d55)
Here it should be imported as COPRO, not COPRP.

**Comment by arnavsinghvi11** [comment]
Fixed!
