### ISSUE TITLE
Inspect_history only shows the last history regardless of n/skip

### ISSUE THREAD

**Issue by noobHappylife** [stanfordnlp/dspy#784]
While I'm using the inspect_history to check the output history, regardless of the n, and skip I chose. It always only return the last history. 

```python
        for idx, (prompt, choices) in enumerate((printed)):
            # skip the first `skip` prompts
            if (n - idx - 1) > skip:
                continue
            printing_value = ""
```

A changed to the inspect_history function as above would make it works to show the last n-th history after considering the skip.

**Comment by arnavsinghvi11** [comment]
@noobHappylife could you elaborate on your test?

Specifying `n` should print the last `n` generations. Specifying `skip` will jump over the past `skip` generations and then print out the last `n` generations.

**Comment by noobHappylife** [comment]
Hi, for your reference. here is the scenario i met. 

```
# lm response history
print([x['response'] for x in nous_lm.history])
```
[{'prompt': 'hi',
  'choices': [{'text': 'Hello! How can I help you today? If you have any questions or need assistance with a problem, feel free to ask.'}]},
 {'prompt': 'who are you?',
  'choices': [{'text': 'I am a super assistant designed to help you with a wide range of tasks, from answering questions to providing guidance and recommendations. My goal is to assist you in the most efficient and helpful way possible.'}]},
 {'prompt': 'who am i?',
  'choices': [{'text': "As a super assistant, I can't directly tell you who you are. However, I can help you discover more about yourself by providing self-reflection prompts or assisting with personal growth and self-discovery tasks. If you'd like, I can offer some resources or activities to help you better understand yourself."}]},
 {'prompt': 'what is 1 + 1?', 'choices': [{'text': '1 + 1 is equal to 2.'}]}]

- followings are inspect_history on different n, and skip.

```
# regardless of n, the inspect_history shows the same output
print(nous_lm.inspect_history(n=1))

what is 1 + 1?1 + 1 is equal to 2.

print(nous_lm.inspect_history(n=2))

what is 1 + 1?1 + 1 is equal to 2.

print(nous_lm.inspect_history(n=4))

what is 1 + 1?1 + 1 is equal to 2.

# including skip, results in None output
print(nous_lm.inspect_history(n=1, skip=1))
# empty output

print(nous_lm.inspect_history(n=3, skip=2))
# empty output
```

After making the changes mentioned earlier, the inspect_history can response with the n, skip correctly (at least in my testing). 

```
[x['response'] for x in nous_lm.history]
```
[{'prompt': 'hi',
  'choices': [{'text': 'Hello! How can I help you today? If you have any questions or need assistance with a problem, feel free to ask.'}]},
 {'prompt': 'who are you?',
  'choices': [{'text': 'I am a super assistant designed to help you with a wide range of tasks, from answering questions to providing guidance and recommendations. My goal is to assist you in the most efficient and helpful way possible.'}]},
 {'prompt': 'who am i?',
  'choices': [{'text': "As a super assistant, I can't directly tell you who you are. However, I can help you discover more about yourself by providing self-reflection prompts or assisting with personal growth and self-discovery tasks. If you'd like, I can offer some resources or activities to help you better understand yourself."}]},
 {'prompt': 'what is 1 + 1?', 'choices': [{'text': '1 + 1 is equal to 2.'}]}]

```
# changing of n will 
print(nous_lm.inspect_history(n=1))

what is 1 + 1?1 + 1 is equal to 2.

print(nous_lm.inspect_history(n=2))

who am i?As a super assistant, I can't directly tell you who you are. However, I can help you discover more about yourself by providing self-reflection prompts or assisting with personal growth and self-discovery tasks. If you'd like, I can offer some resources or activities to help you better understand yourself.


print(nous_lm.inspect_history(n=4))

hiHello! How can I help you today? If you have any questions or need assistance with a problem, feel free to ask.

# including skip, will skip the skip number of history, and show the skip+n-th histroy
print(nous_lm.inspect_history(n=1, skip=1))

who am i?As a super assistant, I can't directly tell you who you are. However, I can help you discover more about yourself by providing self-reflection prompts or assisting with personal growth and self-discovery tasks. If you'd like, I can offer some resources or activities to help you better understand yourself.

print(nous_lm.inspect_history(n=2, skip=2))

hiHello! How can I help you today? If you have any questions or need assistance with a problem, feel free to ask.
```

Do let me know if i'm using the inspect_history incorrectly. 

Thank you.
