### ISSUE TITLE
Application logs unexpectedly redirected to `groq_usage.log`

### ISSUE THREAD

**Issue by conradlee** [stanfordnlp/dspy#798]
I am using DSPY in an app.  The app is not writing logs to stdout as expected.  After wasting some time trying to figure out why, it seems the logs are being redirected to a file called `groq_usage.log`.

My usage of DSPY has nothng to do with groq.  It seem's that the the module `groq_client.py` causes this issue [here](https://github.com/stanfordnlp/dspy/blob/696f2d2e1f96f173abb36302c71a725d564dfadb/dsp/modules/groq_client.py#L21).  I believe that the logging configuration there needs to be scoped down to not redirect all logging into that file.

**Comment by arnavsinghvi11** [comment]
@conradlee Thanks for raising this issue! This will be fixed in an upcoming [logging PR](https://github.com/stanfordnlp/dspy/pull/796/files#diff-e244f079504b22c5a63be8dadceafc794ac1e647da81df80fb36d65e82cc1d28L18).
