### ISSUE TITLE
[Request] Support for Python3.8

### ISSUE THREAD

**Issue by kalpit-konverge** [stanfordnlp/dspy#802]
Hi,

Can DSPy support Python3.8? It currently supports >=3.9 according to the documentation.

**Comment by arnavsinghvi11** [comment]
Hi @kalpit-konverge , do you have a specific use-case? We used to support 3.8 but have since upgraded to 3.9. We can lower it if needed but will require some updates to pypi.

**Comment by federicocagnola** [comment]
@arnavsinghvi11 i'd also be interested in python3.8 support, Ubuntu20.04 LTS comes bundled with this python version and it is found in many production setups

**Comment by av** [comment]
One specific example where I've experienced a desire to run DSPy with 3.8 was when using official `transformers-pytorch-gpu` docker images that are still shipped with 3.8 (in a context of reproducible setup for local dev).
