### ISSUE TITLE
pypi.org version does not match

### ISSUE THREAD

**Issue by talalryz** [stanfordnlp/dspy#805]
https://pypi.org/project/dspy-ai/2.4.5/ does not match or include the latest changes to the project. It also does not match the 2.4.3 here: https://github.com/stanfordnlp/dspy/releases/tag/v2.4.3

**Comment by qhoxie** [comment]
I noticed the same earlier today.  It seems to be missing at least a couple of weeks worth of changes.  Something strange appears to have happened a few days ago with many yanked releases: https://pypi.org/project/dspy-ai/2.4.5/#history

**Comment by okhat** [comment]
yeah working on this

**Comment by okhat** [comment]
nothing major, we're just 2 weeks behind and it's challenging to publish some stuff to pypi, WIP!

**Comment by vietvudanh** [comment]
And there is no tag to track `2.4.5`. 
I installed `2.4.5` and there are some documented features missing (e.q: GROQ intergration), went to code to check and confused what commit is related to this version.

**Comment by arnavsinghvi11** [comment]
Resolved with latest updates!
