### ISSUE TITLE
CoT reasoning in other Languages

### ISSUE THREAD

**Issue by natmonroyr** [stanfordnlp/dspy#809]
Hellow, I would like to know if there is a way to prompt the model to do Chain of Thought reasoning in a language different of english, like spanish, so instead of "Let's think step by step..." it would say "Pensemos paso a paso...", in that way the few ahots are all in spanish not a mixture of spanish and english. Is there a way to achieve this with DSPy?
Thank u in advance

**Comment by okhat** [comment]
Yes you can pass rationale_type yourself to the ChainOfThought module when initializing it.

See here: https://github.com/stanfordnlp/dspy/blob/1a56e69465ef14ab9b7554184e99712766dd77dd/dspy/predict/chain_of_thought.py#L32

**Comment by natmonroyr** [comment]
That's what I needed, thank u!
