### ISSUE TITLE
Tool use?

### ISSUE THREAD

**Issue by jon-chuang** [stanfordnlp/dspy#81]
It seems that DSP would be applicable to tool use.

Demonstrate:
1. Sucessful instances of tool use 

Search:
1. Use tool

Predict:
1. Utilizing output, generate grounded output

**Comment by okhat** [comment]
Yes indeed

**Comment by jon-chuang** [comment]
Possible benchmark: https://github.com/OpenBMB/ToolBench

**Comment by okhat** [comment]
Yes these are excellent, @jon-chuang. There's a whole bunch of these now.

One thing that I haven't looked into is how they divide train/dev/test. Is there a clean split?
