### ISSUE TITLE
Change example model to non gated model

### ISSUE THREAD

**Issue by tom-doerr** [stanfordnlp/dspy#814]
When I try to instantiate a model with the example from the documentation (https://dspy-docs.vercel.app/docs/building-blocks/language_models) with 
```
llama = dspy.HFModel(model = 'meta-llama/Llama-2-7b-hf')
```
I'm getting
```
Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-2-7b-hf/resolve/main/config.json.
Repo model meta-llama/Llama-2-7b-hf is gated. You must be authenticated to access it.
```
How about just changing the model to `mistralai/Mistral-7B-Instruct-v0.2`? 
Seems to work without issues.

**Comment by okhat** [comment]
Makes sense. Thanks @tom-doerr! We'd merge this PR :D

**Comment by arnavsinghvi11** [comment]
Hi @tom-doerr , will merge the PR to ensure we have examples of accessible, non-gated models :).

However, you can actually pass your HuggingFace token to fix this issue, as mentioned in the [documentation](https://dspy-docs.vercel.app/docs/deep-dive/language_model_clients/local_models/HFClientTGI#prerequisites---launching-tgi-server-locally). lmk if that helps!
