### ISSUE TITLE
TypeError: Population must be a sequence.  For dicts or sets, use sorted(d).

### ISSUE THREAD

**Issue by KaifAhmad1** [stanfordnlp/dspy#816]
``` Python 
from dspy.teleprompt import BootstrapFewShot
def validate_context_and_answer(example, pred, trace=None):
    answer_EM = dspy.evaluate.answer_exact_match(example, pred)
    answer_PM = dspy.evaluate.answer_passage_match(example, pred)
    return answer_EM and answer_PM

teleprompter = BootstrapFewShot(metric=validate_context_and_answer)
compiled_rag = teleprompter.compile(RAG(), trainset=history_data)
```

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-21-2aca59f21d97>](https://localhost:8080/#) in <cell line: 14>()
     12 
     13 # Compile!
---> 14 compiled_rag = teleprompter.compile(RAG(), trainset=history_data)

3 frames
[/usr/lib/python3.10/random.py](https://localhost:8080/#) in sample(self, population, k, counts)
    464                 population = tuple(population)
    465             else:
--> 466                 raise TypeError("Population must be a sequence.  For dicts or sets, use sorted(d).")
    467         n = len(population)
    468         if counts is not None:

TypeError: Population must be a sequence.  For dicts or sets, use sorted(d).

**Comment by okhat** [comment]
Hm that's a strange error. Are you just running the intro notebook without changes?

**Comment by KaifAhmad1** [comment]
Hey, @okhat! I'm in the process of developing my solution for Indic languages. Just stuck in this exception

**Comment by arnavsinghvi11** [comment]
Hi @KaifAhmad1 , could you print out the full stack trace so we can see where this exception is coming from?

I suspect `history_data` is not formatted correctly. Feel free to check out the [documentation on Data types in DSPy](https://dspy-docs.vercel.app/docs/building-blocks/data#dspy-example-objects) to ensure the data you are loading in matches expected `dspy.Example` types.

**Comment by KaifAhmad1** [comment]
Thanks! @arnavsinghvi11
