### ISSUE TITLE
generic Retriever class

### ISSUE THREAD

**Issue by DSLituiev** [stanfordnlp/dspy#837]
It would be great to have a generic class for retriever that is subclassed for FaissRM, PyseriniRetriever etc.
I have an application, where I need to indicate a generic retriever as an input, and I am not able to find one. The classes above seem to have a parent class

**Comment by okhat** [comment]
Thank you for the suggestion! Yeah that’s on the agenda but not in the very short term. Closing but feel free to reopen if you have other thoughts
