### ISSUE TITLE
Feature request: more models 

### ISSUE THREAD

**Issue by SaraiQX** [stanfordnlp/dspy#84]
Many thanks for this amazing work!  Eye-opening for a newbie who just got to know RAGstack.
So is it possible or suggested to use open source LLMs such as vicuna, llama 2, and open source embed models like BGE?
Thank you in advance~~

**Comment by okhat** [comment]
Yes, we are releasing these very very soon. We've been working on making sure they work effectively and efficiently for the past 2 months!

**Comment by okhat** [comment]
btw these are all supported now

**Comment by okhat** [comment]
see the PR by @arnavsinghvi11 on how to use models with HF, TGI, VLLM
