### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by habanoz** [stanfordnlp/dspy#841]
In [ChainOfThought](https://dspy-docs.vercel.app/api/modules/ChainOfThought) page:

The following section is no longer reflects the actual code.
```python
DEFAULT_RATIONALE_TYPE = dsp.Type(prefix="Reasoning: Let's think step by step in order to",
                                          desc="${produce the " + last_key + "}. We ...")
```

The actual code uses following instead:

```python
rationale_type = rationale_type or dspy.OutputField(
            prefix="Reasoning: Let's think step by step in order to",
            desc="${produce the " + last_key + "}. We ...",
        )
```

As a result :
`rationale_type (dsp.Type, optional): Rationale type for reasoning steps. Defaults to None.` in the page should be changed to refer to `dspy.OutputField`.

**Comment by okhat** [comment]
Great point. Thank you. Do you wanna make a PR? All docs are in the `docs/` folder on this repo

**Comment by habanoz** [comment]
> Great point. Thank you. Do you wanna make a PR? All docs are in the `docs/` folder on this repo

OK. I will prepare a PR.

**Comment by habanoz** [comment]
I created PR #851 to fix this issue.

Also please note that `git subtree pull` command provided in `docs/README.md` does NOT work, raising `fatal: refusing to merge unrelated histories`.
