### ISSUE TITLE
logging output not showing on console when calling DSPy modules

### ISSUE THREAD

**Issue by sujitpal** [stanfordnlp/dspy#842]
I generally set up my logging following this pattern:

```
import logging
logging.basicConfig(format='%(levelname)s:%(message)s', level=logging.INFO)
```

then in my main ...

```
logger = logging.getLogger(__name__)
# here debug parameter is sent in through CLI
logger.setLevel(logging.DEBUG if args.debug else logging.INFO)
```

I would then make calls to `logger.info(...)` or `logger.debug(...)` within the code (passing in a reference to logger to functions called from main). Expectation is to see INFO outputs on console always and DEBUG when debug == True. This works with non-DSPy code (LCEL) but not when calling DSPy code, i.e. when calling DSPy code I don't see any console output and I have to replace them with `print` calls.

Is there a recommended strategy similar to the above that I could use for logging to work with DSPy code?

**Comment by okhat** [comment]
cc @KCaverly

**Comment by KCaverly** [comment]
We use structlog on the backend for dspy logging, and should have fully standard library compatible logs. We do set the basicConfig for logging ourselves (this makes it a bit easier as people are frequently looking for dspy output in notebooks), but I imagine this may be a conflict with your existing setup.

We do have a logger enabled for dspy, we can access like so:

````
dspy.logger.info("this is a logging info message")
dspy.logger.debug("this is a logging debug message")
````

This avoids us using __name__ boilerplate everywhere, and opens up for us to track additional json data etc.

**Comment by DavidGeorge528** [comment]
A best practice for libraries is to never touch the base logging (Root loggers or call basicConfig). This is because once logging is set, the `logging.basicConfig` does nothing unless `force=True`, which a lot of people might not have set. 

I'd strongly recommend removing the call to `logging.basicConfig` from the library as it will cause people headaches going forward, trying to debug why their loggers have unexpected behaviours.

**Comment by KCaverly** [comment]
Makes sense to me, I think its an artifact of this being more of a demo repo than a framework. Ill put over a pr today to remove it.

**Comment by sujitpal** [comment]
Thank you, I will try `dspy.logger.*` as @KCaverly suggested and remove the `logging.basicConfig` from my calling code as @DavidGeorge528 suggested.

I ran some quick-and-dirty validation using the REPL and I notice that:
1. `import dspy` results in creation of `openai_usage.log`, `azure_openai_usage.log` and `assertion.log`.
2. `dspy.settings.configure(log_openai_usage=False)` results in no more logs being written to `openai_usage.log` following the command.
3. `dspy.settings.configure(log_azure_openai_usage=False)` works but logs continue being written to `azure_openai_usage.log`
4. I have to set the level in my code as `dspy.logger.level = logging.INFO` (or `logging.DEBUG`) then calls to `dspy.logger.info / spy.logger.debug` get written out to `assertion.log`

Ideally, though I think the openai and azure logs should be created when I call `dspy.settings.configure(log_openai_usage=True)` and `spy.settings.configure(log_azure_openai_usage=True)`.

It would also be nice to have a setting where the log messages show up on console rather than `assertion.log`.

But I can live with the state as it is now. Thank you for all the help and guidance. @KCaverly your comment indicates that maybe you want to do something on this, but if not, please feel free to close (or let me know, I can close).

**Comment by KCaverly** [comment]
These extra log files are from an old way of managing logging, we will work through to remove them and keep it standardized.

**Comment by KCaverly** [comment]
@okhat a bit of background on why the 'basicConfig' calls were removed, and thus dspy no longer by default prints logs to console.

**Comment by rysloan4** [comment]
adding that calls to https://api.openai.com (i.e. plain vanilla openai not azure openai) end up getting logged to azure_openai_usage.log with the default settings. seems related.

```
fake_useragent not found, using default user agent.To get a realistic header for requests, `pip install fake_useragent`.
HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Loading faiss.
Successfully loaded faiss.
```
