### ISSUE TITLE
Typo in Docs

### ISSUE THREAD

**Issue by LeonieFreisinger** [stanfordnlp/dspy#844]
**Typo in Docs of Signature Optimizer**

**Link:**
https://dspy-docs.vercel.app/docs/deep-dive/teleprompter/signature-optimizer

**Issue:** COPRO is misspelled as COPRP
```
from dspy.teleprompt import COPRP

teleprompter = COPRO(
    metric=validate_context_and_answer,
    verbose=True,
)
```

**Comment by okhat** [comment]
Feel free to open a PR to fix this file! We’ll merge it right away. Thank you!
