### ISSUE TITLE
How to use OpenAI compatible 3rd party APIs (e.g. tgi/OpenRouter/VLLM etc)?

### ISSUE THREAD

**Issue by scalers-ai** [stanfordnlp/dspy#852]
Appreciate any help with this.

While looking at this documentation: https://dspy-docs.vercel.app/api/language_model_clients/OpenAI

It was not clear how to set api base URL/key etc (e.g. OPENROUTER key instead of OpenAI key)

Copied from docs

```
Constructor
The constructor initializes the base class LM and verifies the provided arguments like the api_provider, api_key, and api_base to set up OpenAI request retrieval. The kwargs attribute is initialized with default values for relevant text generation parameters needed for communicating with the GPT API, such as temperature, max_tokens, top_p, frequency_penalty, presence_penalty, and n.

class OpenAI(LM):
    def __init__(
        self,
        model: str = "text-davinci-002",
        api_key: Optional[str] = None,
        api_provider: Literal["openai"] = "openai",
        model_type: Literal["chat", "text"] = None,
        **kwargs,
    ):

Parameters:

api_key (Optional[str], optional): API provider authentication token. Defaults to None.
api_provider (Literal["openai"], optional): API provider to use. Defaults to "openai".
model_type (Literal["chat", "text"]): Specified model type to use.
**kwargs: Additional language model arguments to pass to the API provider.
```

**Comment by scalers-ai** [comment]
Thanks, closing for now

**Comment by yash98** [comment]
The documentation explains it well! Just sharing a snippet for OpenRouter if anyone wants to use it directly https://gist.github.com/yash98/15753a7f2df1368a2e53825d37cb434b

**Comment by mohamedScikitLearn** [comment]
@arnavsinghvi11 would you please mind updating the link to the documentation? it seems to be expired

**Comment by arnavsinghvi11** [comment]
Hi @mohamedScikitLearn , here's the updated docs link for LMs! https://dspy.ai/learn/programming/language_models

**Comment by osamasajid** [comment]
> The documentation explains it well! Just sharing a snippet for OpenRouter if anyone wants to use it directly https://gist.github.com/yash98/15753a7f2df1368a2e53825d37cb434b

I tried using it but getting error 

TypeError: OpenRouterClient.__call__() missing 1 required positional argument: 'prompt'

**Comment by kgourgou** [comment]
Because of litellm, you can now just do 

```python
lm = dspy.LM(
    model="openrouter/openai/gpt-4.1",
    api_key=os.environ.get("OPENROUTER_API_KEY"),
    cache=True,
)
```

with openrouter.

**Comment by haocoder** [comment]
> Feel free to check out [various compatible 3rd party LM APIs](https://dspy-docs.vercel.app/docs/category/language-model-clients). DSPy supports remote LMs, TGI, vLLM, etc.
> 
> `dspy.OpenAI` is particularly for querying using OpenAI SDK.

link is 404
