### ISSUE TITLE
Using DSPy with V3 weaviate??

### ISSUE THREAD

**Issue by 52THANOS** [stanfordnlp/dspy#860]
![image](https://github.com/stanfordnlp/dspy/assets/117810189/6a75c239-664a-41c9-a35b-ab0d4f720553)
![image](https://github.com/stanfordnlp/dspy/assets/117810189/f9cf3860-a7f2-4536-a62f-2f2df5c0a9a3)
![image](https://github.com/stanfordnlp/dspy/assets/117810189/6824523d-e43a-423f-8078-c43aca421599)
weaviate_client.collections only support V4 connection,but i can only use v3 in weaviate

**Comment by jayar95** [comment]
awww


mad npc can't make puter work


:,--(
