### ISSUE TITLE
structured output is a json

### ISSUE THREAD

**Issue by bhomass** [stanfordnlp/dspy#868]
I want to declare this signature
```
class Icd_code(pydantic.BaseModel):
    code_description: str

class Dual_code_list(pydantic.BaseModel):
    dual_list: Dict[str, List[Icd_code]]

class PosAndNegCodeList(dspy.Signature):
    """Your task is to search for a positive list of codes that match the question, and a negaive list of codes that are  to the input question."""
    
    question: str = dspy.InputField()
    context: str = dspy.InputField()
    answer: Dual_code_list = dspy.OutputField(desc="a json structure of two lists..")

It keeps on throwing errors like "ValueError('json output should start and end with { and }')"

I tried List[List[Icd_code]], but get the same error. 

What is the proper way to declare this?
```

**Comment by ko0stik** [comment]
You should try to see what is the value returned by the LM, high chances that the returned string is not a properly formatted json that the typed prediction can understand. It's been a huge issue for me as well. DSPY already injects in the prompt the expected format, but in my experience, if your model is a 7B or less, it has trouble respecting the instruction.

My workaround has been adding some retries, even more explicit instructions for json in the signature and upgrading the models I use to Mixtral or the likes.

**Comment by anushka192001** [comment]
from pydantic import BaseModel, Field
   
class Input(BaseModel):
    speech: str = Field(description="speech text")

class Output(BaseModel):    
    extracted_words: list[str] = Field(description="a list of extracted words from speech")
    label: int = Field(ge=0, le=2, description="a signle integer--> 0,1 or 2")       


class extract_words_and_label_signature(dspy.Signature):
    """take this speech text and output extracted_words and label"""
 
    input: Input = dspy.InputField() 
    output: Output = dspy.OutputField()


def validate_Signature(example, pred, trace=None):   
    if type(pred.label) != type(example.label):
       return False  
    else:
       return False


import dspy
from dspy.evaluate import Evaluate
from dspy.teleprompt.signature_opt_typed import optimize_signature

# Define the evaluator
evaluator = Evaluate(devset=converted_dataset, metric=validate_Signature, num_threads=1, display_progress=True)

# Optimize the signature
result = optimize_signature(
    student=dspy.TypedPredictor(extract_words_and_label_signature),
    evaluator=evaluator, 
    initial_prompts=20,
    n_iterations=100,  # Increased number of iterations
    max_examples=30,
    verbose=True,
    prompt_model=gpt2,  # Set do_sample=True here
)










Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Found 1 typed predictors to optimize.
Generating 20 initial signatures for base...
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-163-7ce07138d679>](https://localhost:8080/#) in <cell line: 9>()
      7 
      8 # Optimize the signature
----> 9 result = optimize_signature(
     10     student=dspy.TypedPredictor(extract_words_and_label_signature),
     11     evaluator=evaluator,

2 frames
[/usr/local/lib/python3.10/dist-packages/dspy/functional/functional.py](https://localhost:8080/#) in forward(self, **kwargs)
    233                     {key: [r[key] for r in parsed_results] for key in signature.output_fields},
    234                 )
--> 235         raise ValueError(
    236             "Too many retries trying to get the correct output format. " + "Try simplifying the requirements.",
    237             errors,

ValueError: ('Too many retries trying to get the correct output format. Try simplifying the requirements.', {'proposed_signatures': "ValueError('json output should start and end with { and }')"})



...................
converted_dataset[0]
Example({'speech': 'the uk has threatened to return radioactive waste to the eu if an agreement cannot be reached can not we keep the radioactive waste and send back all the paki migrants instead', 'extracted_tokens': ['send', 'back', 'all', 'the', 'paki', 'migrants', 'instead'], 'label': 0}) (input_keys={'speech'}).  


let me know how to resolve this issue?

**Comment by bhomass** [comment]
I tried extending retries with dspy.Suggest, that it is very hard to have a clear prompt for this double list structure I want. Turns out it's a matter of context window size. By using command-r+ with a higher window size, it started to work using TypedChainOfThought.
