### ISSUE TITLE
Are there any TypedChainOfThoughtHint?

### ISSUE THREAD

**Issue by ChirsHuanhuan** [stanfordnlp/dspy#878]
Thank you for your wonderful work.
I would like to ask, you created TypedChainOfThought based on typed predictor. But I don’t seem to have found a way to add hints to this COT. Do you have anything similar to TypedChainOfThoughtHint?

**Comment by okhat** [comment]
There isn’t, all predictors will become implicitly typed within a few months…

**Comment by ChirsHuanhuan** [comment]
Thanks for your reply, but I'm still confused about what the 'implicitly typed' means. Can you be more specific? Thank you.
