### ISSUE TITLE
AI feedback using logprobs

### ISSUE THREAD

**Issue by tom-doerr** [stanfordnlp/dspy#879]
Whenever I use a LM to evaluate something I ask a Yes/No question and do `logprob_yes - logprob_no`. This worked very well for me in the past. How can I access logprobs in my metric function?

**Comment by arnavsinghvi11** [comment]
Hi @tom-doerr , logprobs are indeed quite useful. Currently, DSPy doesn't support returning additional parameters besides the [response content](https://github.com/stanfordnlp/dspy/blob/d09d984ecaf17f7262294d50fe46fd8105fbf291/dsp/modules/gpt3.py#L188), but you can extract the logprobs from [the response](https://github.com/stanfordnlp/dspy/blob/d09d984ecaf17f7262294d50fe46fd8105fbf291/dsp/modules/gpt3.py#L178) (subject to different LM configurations). 

Feel free to push a PR that enables some flag for returning completions with logprobs while maintaining internal behavior!

**Comment by arthurgreef** [comment]
This no longer works with the LiteLLM client on 2.5.13.

```python
output = gpt("Hello, world!", logprobs=True, top_logprobs=1)
print (output)
```

Expected: Logprobs after the text object.
Actual: Just the text: `['Hello! How can I assist you today?']`

**Comment by tranhoangnguyen03** [comment]
```
from google.colab import userdata

lm = dspy.OpenAI(
    model='gpt-4o', 
    max_tokens=512, 
    api_key=userdata.get('openai_api_key')
)

dspy.settings.configure(lm=lm)

system_prompt = "answer in a single word.\n"
test_text = system_prompt + "The answer to the ultimate question to the meaning of life, the universe, and everything is ..."
test_output = lm(test_text, logprobs=True, top_logprobs=20)
print("test_output:", test_output)
```
The script above is working in terms of outputing the logprobs, but it triggers the deprecation warning.

```
from google.colab import userdata

lm = dspy.LM(
    'openai/gpt-4o', 
    max_tokens=512, 
    api_key=userdata.get('openai_api_key')
)
dspy.configure(lm=lm)

system_prompt = "answer in a single word.\n"
test_text = system_prompt + "The answer to the ultimate question to the meaning of life, the universe, and everything is ..."
test_output = lm(test_text, logprobs=True, top_logprobs=20)
print("test_output:", test_output)
```
This script doesn't produce the logprobs.

Are there plans to fix this? Is there a way for me to apply a patch locally on my machine to hotfix this?

**Comment by okhat** [comment]
Support for logprobs is merged now.
