### ISSUE TITLE
Abstraction for Finetuning

### ISSUE THREAD

**Issue by sutyum** [stanfordnlp/dspy#885]
DSPy supports both prompt tuning, as well as finetuning currently. Currently the finetuning class is a very specific, it would be nice to turn it into a general abstraction so that one could write their own finetuning backend. For instance, one could write a fine tuning backend on top of RunPod's API, OpenAI's API, Predibase's API, etc.

Just creating this issue in order to see if the new backend rewrite that's underway has this taken into account/plan in some way. If not, would like to add this.

Also worth noting: DSPy + multi-LORA could be a great combination. multi-LORA allows for a single GPU to host 100s of LORA adapters. For instance, the entire Predibase platform supports all its users with just 1 A100 (heard this from their team in a youtube video). vLLM, [LORAx](https://github.com/predibase/lorax) provide open source solutions. SgLang also has it on their current [roadmap](https://github.com/sgl-project/sglang/issues/157).

**Comment by isaacbmiller** [comment]
This is something I am looking into more deeply currently. Will update this issue as info comes
