### ISSUE TITLE
Support OpenAI Batch requests. 

### ISSUE THREAD

**Issue by pranavchat14** [stanfordnlp/dspy#886]
Can we support OpenAI Batch requests. 

Example use cases are classification, translation etc. 

Reference: 
https://twitter.com/OpenAIDevs/status/1779922566091522492

https://platform.openai.com/docs/api-reference/batch

**Comment by arnavsinghvi11** [comment]
Feel free to open a PR @pranavchat14 ! `dspy.OpenAI` points to request-calling logic in [gpt3.py](https://github.com/stanfordnlp/dspy/blob/d09d984ecaf17f7262294d50fe46fd8105fbf291/dsp/modules/gpt3.py), which can be adapted to batched requests. If this would not support the current caching logic, we can look into adapting an OpenAIBatched class to handle this.

**Comment by maximus-powers** [comment]
I'd love to see this added, I can help if you end up working on an OpenAIBatched class.

**Comment by okhat** [comment]
Not really a priority now, after some thinking.

**Comment by ArslanS1997** [comment]
Hi is something like this available?

**Comment by williambrach** [comment]
Any updates on this?

**Comment by dentroai** [comment]
would also be interested being able to use the batch api of openai with dspy!

**Comment by simon-lowe** [comment]
This would be very useful. If I want to use some DSPy pipeline on larger datasets, it would really be great to have this.

**Comment by josancamon19** [comment]
not implemented yet? @okhat
