### ISSUE TITLE
Async Metric

### ISSUE THREAD

**Issue by BrianSemiglia** [stanfordnlp/dspy#892]
Is there any way to provide an async function as a metric? I haven't seen anything yet

**Comment by sutyum** [comment]
DSPy currently does not support async execution. Though if all you need is to use an async function without using it in an async manner - you could just do:

```py
async def my_metric(...) -> bool:
  ...

loop = asyncio.get_event_loop()
loop.run_until_complete(my_metric(...))
```

is this useful?

**Comment by BrianSemiglia** [comment]
I think that'll work. Thanks 🏄‍♀️
