### ISSUE TITLE
ReAct Tools

### ISSUE THREAD

**Issue by bwhartlove** [stanfordnlp/dspy#900]
I'd like to request some additional information on how to write custom tools for the ReAct module in DSPy. I've seen a few examples, but I've been struggling to wrap my head around how to write tools that take in multiple inputs in particular. Any and all information would be greatly appreciated. Thanks!

**Comment by timothyvinzent** [comment]
Hello @bwhartlove

Ive shared my code to get custom ReAct Tools working -> ReAct calls custom tools twice #804 

I simply used a list to have multiple inputs.

I hope my code helps you out!
