### ISSUE TITLE
Llama3 Bugs: Output contains input & Endless generating

### ISSUE THREAD

**Issue by quanshr** [stanfordnlp/dspy#904]
I used ```dspy.HFModel``` to load ```Llama3-8B-Instruct``` but encountered two issues.
1. The .generate method in Llama3 returns input + output, but DSPy didn't filter the input part, making the rationale and answer parse fail.
2. In few-shot settings, after Llama3 finishes the answering, it outputs '---' and continues to generate the next sample and next. Making the output endless and the inference time relatively long. Are there some methods to set '---' as a signal to end the model generating?

Following is a case example: 
```
Prediction(
rationale="Given a context and a question, return the answer, you must follow the principle. \n    Principle:\n    1. There are several few-shot examples, you only need to give the answers of the final question and don't output other imformation.\n    2. you must give a right answer of the problem.\n\n---\n\nFollow the following format.\n\nContext: \n\nQuestion: \n\nReasoning: Let's think step by step in order to ${produce the answer}. We...",
    answer='---\n\nContext: the wind, ranging from 0 (calm) to 12 (hurricane). The scale was devised in 1805 as a means of describing the effect of different wind velocities on ships at sea. [PAR] Beaufort scale [PAR] (wind scale) A scale that rates the force of wind from 0 to 12, a rating of 0 being absolute calm and one of 12 being hurricane force. [PAR] ...
```

How to solve these two problems?

**Comment by detaos** [comment]
This isn't a DSPy issue ... it's a model config issue.  We ran into the same thing just sending plain requests to Llama 3 hosted with vLLM: https://github.com/vllm-project/vllm/issues/4180

**Comment by quanshr** [comment]
@detaos Not the same problem. Your solution seems to be focused on problem 2, but actually it didn't output ```<|eot_id|>``` either. Due to the integrated prompt not knowing that the current question is the last one, it will continue to generate new ones.

**Comment by detaos** [comment]
You can stop inference on "---" by setting the stop parameter:

```
lm = dspy.OpenAI(
    model = my_model,
    api_base my_vllm_server,
    stop = "---",
    [...]
)
```

**Comment by quanshr** [comment]
@detaos It can solve both problems. Thanks a lot
