### ISSUE TITLE
Cache appears to be permanently turned on in dspy-ai-2.4.5

### ISSUE THREAD

**Issue by oekekezie** [stanfordnlp/dspy#907]
In this version of DSPy, this looks like a bug in the file "dsp/modules/cache_utils.py":
```python
cache_turn_on = True
```

It should probably be:
```python
cache_turn_on = os.environ.get('DSP_CACHEBOOL', 'True').lower() != 'false'
```

Otherwise, it seems like the cache can't be turned off? I made the change and my program is no longer retrieving cached responses.

**Comment by arnavsinghvi11** [comment]
Hi @oekekezie , the current pypi version for dspy is not updated with latest PR changes. Please install from source as needed while we work through updating dspy-ai!
