### ISSUE TITLE
dspy misses newlines, especially with longer context and smaller models

### ISSUE THREAD

**Issue by den-run-ai** [stanfordnlp/dspy#910]
DSPy misses newlines, especially with longer context and smaller models. 

So is there any possibility to enforce newline character treatment in the few-shot in-context learning examples.

**Comment by okhat** [comment]
This is addressed in the FAQ. You will just need to pass format=str in your signature. Check out the FAQ in our docs

**Comment by n8duo** [comment]
Which FAQs? I don't see anything about `format=str` on either of these docs

- [https://github.com/stanfordnlp/dspy/blob/main/docs/docs/faqs.md](https://github.com/stanfordnlp/dspy/blob/main/docs/docs/faqs.md)
- [https://dspy.ai/faqs/](https://dspy.ai/faqs/)
