### ISSUE TITLE
How can I control the `Follow the following format` in the prompt?

### ISSUE THREAD

**Issue by dhilst** [stanfordnlp/dspy#913]
Hello

I have this code

```python
import dspy

backend_llm = dspy.OllamaLocal(
    model='llama3',  # The model we're going to use.
)

dspy.configure(lm=backend_llm)

class MySig(dspy.Signature):
    """
You are a binary classifier

You'll receive a list of tokens and should answer YES or NO based on previous examples.
    """
    tokens = dspy.InputField()
    answer = dspy.OutputField(desc="YES/NO", prefix="Answer:")

class CoT(dspy.Module):
    def __init__(self):
        super().__init__()
        self.prog = dspy.Predict(MySig)

    def forward(self, *args, **kwargs):
        print(args, kwargs)
        return self.prog(*args, **kwargs)

CoT().forward(tokens="foo,bar,tar")
backend_llm.inspect_history(n=1)
```
This produces this output 

![image](https://github.com/stanfordnlp/dspy/assets/392820/71931908-c4c4-45ab-85cc-677ddf52d6a8)

Where this `Follow the follow format` is coming from? And how can I change it?

I want to generate only the answer, not the `tokens`

**Comment by gidler** [comment]
The `Follow the following format` comes from [this line](https://github.com/stanfordnlp/dspy/blob/66573d66622acd73e8bfe68a6c098a5351826db2/dsp/templates/template_v2.py#L121) in the default `Template`, which is used by `Predict`. I don't see a way around it if you are using `Predict` in your Module/Pipeline.

You can prompt engineer your way into only getting "Yes" or "No" in your answer. For example, I did it with:
```
You are a binary classifier

You'll receive a list of tokens and should answer YES or NO based on previous examples.

Do not include "Tokens" in the answer, only reply with YES or NO.
```
but you are fighting against the template which is unfortunate.


Also, just so you know, the `__call__()` method on a `Module` calls `forward()`. I think this is a more standard way to generate the output:
```
cot_predictor = CoT()
output = cot_predictor(tokens="foo,bar,tar")
```

**Comment by dhilst** [comment]
Thank you for the fast response gidler!!

Okay no problem, I will adjust the signature

**Comment by marshmellow77** [comment]
You can set `dsp.settings.show_guidelines = False` to avoid the `Follow the following format` prompt template

**Comment by Zoher15** [comment]
> You can set `dsp.settings.show_guidelines = False` to avoid the `Follow the following format` prompt template

This is why I came hereee. Thank youuuuuuu

**Comment by Zoher15** [comment]
@marshmellow77 Where is this information? I would like to know all the settings I can change......

**Comment by marshmellow77** [comment]
@Zoher15  - I found this flag while debugging. Haven't found a good documentation for it or other flags, tho :(

**Comment by marshmellow77** [comment]
I just asked Gemini 1.5 to go through the entire repo and it found all the settings, listed and described them 😃

![image](https://github.com/user-attachments/assets/3c5eb5bb-f3e1-4978-9a45-2437827da27e)

**Comment by Zoher15** [comment]
@marshmellow77 haha love the initiative and creativity!

**Comment by ydbhsk** [comment]
I found the code for generating these prompts in the dspy library file. replacing it with "" works.![Image](https://github.com/user-attachments/assets/faf58def-9226-48b2-a94c-225e51ddfbf6)

![Image](https://github.com/user-attachments/assets/7340da30-493b-4167-a329-84cd244baf0d)

**Comment by kalinduaet** [comment]
> You can set `dsp.settings.show_guidelines = False` to avoid the `Follow the following format` prompt template

Hi, any idea how to do this in latest DSPy version (3.0)?. Seems like this has been removed.
