### ISSUE TITLE
Trivial RFE: add dspy.__version__ variable

### ISSUE THREAD

**Issue by rpgoldman** [stanfordnlp/dspy#939]
Not a huge problem, but it would be nice if we could introspect on the dspy version.

**Comment by okhat** [comment]
@hmoazam I wonder how easy for this to work with the way we publish versions?

**Comment by hmoazam** [comment]
Yes we can do this, I'll take a look.

**Comment by hmoazam** [comment]
Solved: https://github.com/stanfordnlp/dspy/pull/1963
