### ISSUE TITLE
Typo in docstring for mipro-optimizer.py

### ISSUE THREAD

**Issue by rpgoldman** [stanfordnlp/dspy#949]
In the Usage Suggestions, the same definition is given for two different parameters:

Note that this teleprompter takes in the following parameters:

* prompt_model: The model used for prompt generation. When unspecified, defaults to the model set in settings (i.e., dspy.settings.configure(lm=task_model)).
* task_model: The model used for prompt generation. When unspecified, defaults to the model set in settings (i.e., dspy.settings.configure(lm=task_model)).
 
See [the source code](https://github.com/stanfordnlp/dspy/blob/2cee6b6197fbb5ce6e3fec6de88dab3357d6565b/dspy/teleprompt/mipro_optimizer.py#L30-L34)

**Comment by okhat** [comment]
fixed in MIPROv2
