### ISSUE TITLE
biggest challenge in retrieval*

### ISSUE THREAD

**Issue by qrdlgit** [stanfordnlp/dspy#95]
Lots of cool stuff built around leveraging realtime human created knowledge.

The biggest challenge I'm running into is 'back propagation' for the entire RAG/REML/RAML/R* pipeline.  Always tricky to do when stitching together a bunch of disparate models. 

Not sure the REST based 3rd party models belong in lower level efforts, btw.   They are too much flux / unreliable.  Very useful for sure, but probably best to keep them high level.

**Comment by okhat** [comment]
Thanks for the note. Let me know if there's a particular issue we can help with
