### ISSUE TITLE
ValueError: temperature (=0.0) has to be a strictly positive float, otherwise your next token scores will be invalid. If you're looking for greedy decoding strategies, set do_sample=False

### ISSUE THREAD

**Issue by anushka192001** [stanfordnlp/dspy#969]
using 'meta-llama/Llama-2-7b-chat-hf' from hugging face. and in this below code

llama2= dspy.HFModel(model = 'meta-llama/Llama-2-7b-chat-hf')

colbertv2_wiki17_abstracts = dspy.ColBERTv2(url='http://20.102.90.50:2017/wiki17_abstracts')

dspy.settings.configure(lm=llama2, rm=colbertv2_wiki17_abstracts)

#teleprompeter to optimize the weights of this program using a metric defined validate_Pred_Imp_words
from dspy.teleprompt import BootstrapFewShot,Ensemble
#Define the validation logic for the hate speech classification task

def validate_hate_speech(example, pred, trace=None):
 for pred_token in pred.pred_extracted_tokens:
 token_count=0
 for example_tokens in example.extracted_tokens:
 if pred_token in example_tokens:
 token_count+=1
 if token_count<2:
 return False
 label_count=0
  for example_label in example.label:
     if str(pred.pred_label)== str(example_label):
      label_count+=1
  if label_count<2:
     return False

 target_count=0
  for pred_target in pred.pred_target:
    for example_targets in example.target:
       if pred_target in example_targets:
          target_count+=1
    if target_count<2:
       return False
 return True

#Set up the teleprompter
teleprompter = BootstrapFewShot(metric=validate_hate_speech)

#Compile the program
compiled_program = teleprompter.compile(HateSpeechClassifier(), trainset=extract_words_dataset_train[:])

THE ERROR--

##error---
ValueError Traceback (most recent call last)
in <cell line: 37>()
35
36 # Compile the program
---> 37 compiled_program = teleprompter.compile(HateSpeechClassifier(), trainset=extract_words_dataset_train[:])

16 frames
[/usr/local/lib/python3.10/dist-packages/transformers/generation/logits_process.py](https://localhost:8080/#) in init(self, temperature)
282 if isinstance(temperature, float) and temperature == 0.0:
283 except_msg += " If you're looking for greedy decoding strategies, set do_sample=False."
--> 284 raise ValueError(except_msg)
285
286 self.temperature = temperature

ValueError: temperature (=0.0) has to be a strictly positive float, otherwise your next token scores will be invalid. If you're looking for greedy decoding strategies, set do_sample=False.

**Comment by anushka192001** [comment]
please look into thisissue

**Comment by okhat** [comment]
I think this was resolved by #1056 thanks to Pasquale.
