### ISSUE TITLE
Understanding model history after MIPRO optimizer

### ISSUE THREAD

**Issue by dvd42** [stanfordnlp/dspy#980]
I am not sure as to how to interpret the model history for the MIPRO optimizer. Whenever I run the optimizer I get some logs that seems the input to the optimizer or teacher model:

For example:

You are an instruction optimizer for large language models. I will give you a ``signature`` of fields (inputs and outputs) in English. Specifically, I will give you some ``observations`` I have made about the dataset and task, along with some ``examples`` of the expected inputs and outputs. I will also provide you with the current ``basic instruction`` that is being used for this task.

Your task is to propose a new improved instruction and prefix for the output field that will lead a good language model to perform the task well. Don't be afraid to be creative.

Basic Instruction: blabalabla
Proposed Instruction: blabalbalbla

Proposed Prefix For Output Field: "Search Optimization Results:"

However after the optimization is done, If I inspect the model history via (`turbo.inspect_history(n=1)`).  I see the original prompt I created + some bootstrapped examples + few-shot examples (same as you would get with BootsrapFewShot).

What is being fed to the model exactly here? Why can't I see the proposed instruction in the model history?. 

Thanks in advance!

**Comment by dvd42** [comment]
Any help on this? Should I provide more information?

**Comment by okhat** [comment]
I'm not 100% sure I understand the question BUT the MIPRO optimizer is smart enough to keep the original instructions if, within its budget, it finds that generating new instructions is unnecessary/unhelpful. This may be happening in your case.

**Comment by dvd42** [comment]
Thanks for the response! So it could be that MIPRO does not offer much more value over BootstrapFewShot?

**Comment by JohannKaspar** [comment]
I agree with the OP, this is rather unintuitive.

> [I 2024-07-18 15:36:12,387] Trial 3 finished with value: 100.0 and parameters: {'139829881539552_predictor_instruction': 9, '139829881539552_predictor_demos': 3}. Best is trial 3 with value: 100.0.

The objhect returned by running teleprompter.compile includes a modified instruction, when using this object to make a prediction however, it always uses the original instruction.

I know MIPRO is deprecated, but MIPRO_v2 is pretty unstable in my case.
