### ISSUE TITLE
Support for batching for LM clients (OpenAI, vLLM etc)

### ISSUE THREAD

**Issue by AmoghM** [stanfordnlp/dspy#991]
I have seen conversations where it has been mentioned that Evaluate has `num_threads` parameters that can parallelize but I am not completely sure if it provides significant performance gains compared to batching.

Reasoning:
* Python doesn't truly support multi-threading.
* Bottleneck in performance is sending data over to the GPU.

Solution:
* Send a batch of data even when running the dspy.Predict()

For example:

```python
from typing import List
import dspy

vllm_llm = dspy.HFClientVLLM(model="meta-llama/meta-llama-3-8B-Instruct", port=8000, url="http://localhost", temperature=0.7)
dspy.settings.configure(lm=vllm_llm)

class SciGen(dspy.Signature):
    """context and answer on science questions"""
    question = dspy.InputField(desc="Input question")
    context = dspy.OutputField(desc="context") 
    answer = dspy.OutputField(desc="Answer using only the context")

context_generator = dspy.Predict(SciGen, n=5)
response = context_generator(question=["Why do we have a solar eclipse?", 
                                       "How are black holes formed", 
                                       "What is the big bang theory"]) #batching the call
 
print((response.completions)) # Prints 5 data generated results for the 3 questions asked. Total 15 responses

```

**Comment by mikeedjones** [comment]
The main blocker to this change would be that [graph compilation is not supported for `n>1`](https://github.com/stanfordnlp/dspy/blob/b05394bb20722444648a33b4447156bcef202fd6/dsp/primitives/predict.py#L157) - however, I'm not sure what you mean exactly in this case that python doesn't support multi-threading, and the bottleneck is sending data to the GPU? 

In your example, the loading of the tokens into gpu memory is handled by the huggingface client on `localhost:8000` - which has nothing to do with dspy or the process in which dspy is running. I'm not sure that sending the prompts across to that port is the bottleneck in performance? In any case, [vllm supports continuous batching](https://docs.vllm.ai/en/latest/index.html#welcome-to-vllm:~:text=Continuous%20batching%20of%20incoming%20requests) so the batch size for the actual inference will be determined by vLLM based on a whole host of things. 

As for threadpool executors - which is how dspy runs multiple `Predict`s at once - [its probably the best choice for sending off a bunch of concurrent http requests](https://docs.python.org/3/library/concurrent.futures.html#threadpoolexecutor-example) as dspy does. The polling overhead is pretty insubstantial when compared to inference time and `num_threads` is not likely to get anywhere near the sorts of numbers where it could become a problem.

**Comment by okhat** [comment]
Thank you @AmoghM , @mikeedjones ! We don't plan to add batching. But we will add utilities for easier parallelism. Multi-threading is actually perfectly fine since the bottleneck is always on the server not the client.

**Comment by phazei** [comment]
I just found out about batching, was super excited about it, then found this thread.  I use LM Studio for it's API, but I can't run agents with a single thread, so I guess I'm going to need to find an alternative, but it would be awesome if you could eventually support it.

**Comment by NiveditJain** [comment]
Hey @phazei I would love to know your use case, I am thinking to write a folk of DSPY with batch support to optimize model cost for us.

**Comment by phazei** [comment]
@NiveditJain 
Well, on my local system, I can run a 24B model at about 70tk/s.  But using batching, I can run 6 parallel requests at 50tk/s.  Each individual one is slower, but overall I'm now getting 300tk/s on my same card.  I just wanted to be able to take advantage of that with any agent tool I have.  I'm not sure I actually fully understood DSPy when I first commented, but it seems like it could improve the local optimization stage massively by being able to run multiple tests at the same time drastically cutting down on time.  The use case I was thinking about at the time was simply being able to have multiple agents sequentially rather than being limited to a single thread at a time which is very slow and makes having an orchestration agent and a task agent more complicated.

**Comment by vienneraphael** [comment]
Hey @phazei and @NiveditJain, I created this open-source lib that allows to convert most async workflows targetting frontier APIs to use their batch inference endpoint: https://github.com/vienneraphael/batchling

I just tried and it works perfectly with dspy, the example is live in docs: https://batchling.pages.dev/frameworks/dspy/
